name: 'Stop Services'
description: 'Stop Docker Compose services and clean up volumes'
inputs:
  compose-file:
    description: 'Path to the Docker Compose file'
    required: false
    default: './deployments/compose/compose.yml'
runs:
  using: 'composite'
  steps:
    - name: Stop services
      shell: bash
      run: |
        echo "🧹 Stopping services..."
        START_TIME=$(date +%s)
        echo "📅 Start: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        docker compose -f ${{ inputs.compose-file }} down -v
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "📅 End: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        echo "⏱️ Service cleanup completed in: ${DURATION}s"
