// Copyright (c) 2025-2026 Justin Cranford.
// Package magic contains magic constants for PKI CA service.
package magic

import "time"

// PKI CA service constants.
const (
	// OTLPServicePKICA is the OTLP service name for pki-ca telemetry.
	OTLPServicePKICA = "pki-ca"

	// PKICAServiceID is the canonical service identifier for pki-ca.
	PKICAServiceID = OTLPServicePKICA

	// PKIProductName is the product name component of the PKI product.
	PKIProductName = "pki"

	// PKICAServiceName is the service name component of the pki-ca service.
	PKICAServiceName = "ca"

	// PKICAServicePort is the default public API port for pki-ca service.
	// Port range for PKI CA: 8300-8399 (100-port block).
	PKICAServicePort = 8300

	// PKICADisplayName is the human-readable display name for the pki-ca service.
	PKICADisplayName = "Certificate Authority"
)

// PKI CA E2E Test Configuration.
const (
	// PKICAE2EComposeFile is the path to the pki-ca docker compose file (relative from e2e test directory).
	// Path: internal/apps/pki-ca/e2e → ../../../../deployments/pki-ca/compose.yml
	// Levels: e2e→pki-ca(1)→apps(2)→internal(3)→root(4), then deployments/pki-ca.
	PKICAE2EComposeFile = "../../../../deployments/pki-ca/compose.yml"

	// PKICAE2ESQLiteContainer is the SQLite instance 1 service name in compose.
	PKICAE2ESQLiteContainer = "pki-ca-app-sqlite-1"

	// PKICAE2ESQLite2Container is the SQLite instance 2 service name in compose.
	PKICAE2ESQLite2Container = "pki-ca-app-sqlite-2"

	// PKICAE2EPostgreSQL1Container is the PostgreSQL instance 1 service name in compose.
	PKICAE2EPostgreSQL1Container = "pki-ca-app-postgresql-1"

	// PKICAE2EPostgreSQL2Container is the PostgreSQL instance 2 service name in compose.
	PKICAE2EPostgreSQL2Container = "pki-ca-app-postgresql-2"

	// PKICAE2EHealthTimeout is the timeout for health checks during E2E tests.
	PKICAE2EHealthTimeout = 180 * time.Second

	// PKICAE2EHealthPollInterval is the interval between health check attempts.
	PKICAE2EHealthPollInterval = 2 * time.Second

	// PKICAE2ESQLitePublicPort is the SQLite instance 1 public HTTPS port (SERVICE level: 8300).
	PKICAE2ESQLitePublicPort = 8300

	// PKICAE2ESQLite2PublicPort is the SQLite instance 2 public HTTPS port (SERVICE level: 8301).
	PKICAE2ESQLite2PublicPort = 8301

	// PKICAE2EPostgreSQL1PublicPort is the PostgreSQL instance 1 public HTTPS port (SERVICE level: 8302).
	PKICAE2EPostgreSQL1PublicPort = 8302

	// PKICAE2EPostgreSQL2PublicPort is the PostgreSQL instance 2 public HTTPS port (SERVICE level: 8303).
	PKICAE2EPostgreSQL2PublicPort = 8303

	// PKICAE2EHealthEndpoint is the public health check endpoint.
	PKICAE2EHealthEndpoint = "/service/api/v1/health"

	// PKICAE2EPublicCACertPath is the path to the public HTTPS server CA cert generated by pki-init.
	// Path is relative to the e2e test directory (internal/apps/pki-ca/e2e/).
	// pki-init mounts output to deployments/pki-ca/certs/ on the host.
	PKICAE2EPublicCACertPath = "../../../../deployments/pki-ca/certs/pki-ca/public-https-server-issuing-ca/truststore/public-https-server-issuing-ca.crt"
)
