# identity-spa-app-sqlite-1.yml
# Instance-specific settings for identity-spa-app-sqlite-1 in compose.yml

cors-origins:
  - "https://localhost:8800"
  - "https://127.0.0.1:8800"
  - "https://[::1]:8800"

otlp-service: identity-spa-sqlite-1
otlp-hostname: identity-spa-sqlite-1

database-url: "sqlite://file::memory:?cache=shared"
