# identity-spa-app-postgresql-1.yml
# Instance-specific settings for identity-spa-app-postgresql-1 in compose.yml

cors-origins:
  - "https://localhost:8802"
  - "https://127.0.0.1:8802"
  - "https://[::1]:8802"

otlp-service: identity-spa-postgresql-1
otlp-hostname: identity-spa-postgresql-1
