# identity-spa-app-sqlite-2.yml
# Instance-specific settings for identity-spa-app-sqlite-2 in compose.yml

cors-origins:
  - "https://localhost:8801"
  - "https://127.0.0.1:8801"
  - "https://[::1]:8801"

otlp-service: identity-spa-sqlite-2
otlp-hostname: identity-spa-sqlite-2

database-url: "sqlite://file::memory:?cache=shared"
