global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['opentelemetry-collector:8889']
    scrape_interval: 30s
    metrics_path: /metrics
