# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: 'golangci-lint'
description: 'Run golangci-lint with auto-fix and final validation using official golangci-lint-action'
inputs:
  config-file:
    description: 'Path to golangci-lint configuration file'
    required: false
    default: '.golangci.yml'
  timeout:
    description: 'Timeout for golangci-lint runs'
    required: false
    default: '10m'
  version:
    description: 'golangci-lint version to use'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Run golangci-lint with auto-fix
      uses: golangci/golangci-lint-action@v8
      with:
        version: ${{ inputs.version }}
        args: --fix --timeout=${{ inputs.timeout }} --config=${{ inputs.config-file }}
        # Performance optimizations
        skip-cache: false
        skip-pkg-cache: false
        skip-build-cache: false
        # Only report new issues in PRs (disabled for now to see all issues)
        only-new-issues: false

    - name: Run golangci-lint final check
      uses: golangci/golangci-lint-action@v8
      with:
        version: ${{ inputs.version }}
        args: --timeout=${{ inputs.timeout }} --config=${{ inputs.config-file }}
        # Performance optimizations
        skip-cache: false
        skip-pkg-cache: false
        skip-build-cache: false
        # Only report new issues in PRs (disabled for now to see all issues)
        only-new-issues: false
