# $schema: https://json.schemastore.org/golangci-lint.json
# schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json
# doc: https://golangci-lint.run/docs/configuration/file/
# reference: https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
# github repo: https://github.com/golangci/golangci-lint/tree/main
#
# golangci-lint configuration for cryptoutil project
# This project uses Go 1.25.4 with golangci-lint v2.6.2
#
# Usage: golangci-lint run --timeout=10m

version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 0  # Use all available CPUs

output:
  formats:
    tab:
      path: stdout
  sort-order:
    - linter
    - severity
    - file

linters:
  enable:
    # Essential linters (fast static analysis)
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs (Go's built-in vet)
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple, stylecheck in v2)
    - unused        # Find unused constants, variables, functions and types

    # Code quality linters (fast)
    - revive        # Golint replacement with more rules
    - godot         # Check for missing periods in documentation comments
    - copyloopvar   # Check for loop variables captured by reference
    - goconst       # Find repeated strings that could be constants
    - importas      # Enforce consistent import aliasing

    # Security and error handling
    - gosec         # Security-focused static analysis
    - noctx         # Check for missing context in HTTP requests
    - wrapcheck     # Check error wrapping consistency
    - errorlint     # Find code that will cause problems with Go 1.13 error wrapping

    # Testing quality
    - thelper       # Check test helper functions
    - tparallel     # Check for parallel test issues
    - testpackage   # Test package naming conventions
    - gomodguard    # Prevent importing blocked modules
    - gomoddirectives # Validate Go module directives

    # Performance and style
    - prealloc      # Find slice declarations that could pre-allocate
    - bodyclose     # Check for HTTP response body closure
    - mnd           # Detect magic numbers
    - wsl           # Whitespace linter
    - nlreturn      # Enforce newlines after return statements

    # Maintainability
    - goheader      # Copyright header enforcement
    - depguard      # Enforce allowed/disallowed import dependencies

  disable:
    - dupl          # Code duplication
    - gocyclo       # Cyclomatic complexity
    - godox         # TODO/FIXME comments

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G204  # Subprocess launched with variable
        - G301  # Directory permissions too permissive
        - G302  # File permissions too permissive
        - G304  # Potential file inclusion via variable
        - G402  # TLS InsecureSkipVerify set true

    gocyclo:
      min-complexity: 15

    goconst:
      min-len: 1
      min-occurrences: 2
      numbers: true

    mnd:
      ignored-numbers:
        - '2'  # Common in bit operations
      ignored-functions:
        - 'math.*'
        - 'len'
        - 'make'

    dupl:
      threshold: 100

    misspell:
      locale: US

    revive:
      severity: warning

    godot:
      scope: declarations
      capital: false

    godox:
      keywords:
        - TODO
        - FIXME
        - BUG
        - HACK

    thelper:
      test:
        begin: true

    testpackage:
      skip-regexp: '.*_test\.go$'
