# $schema: https://json.schemastore.org/golangci-lint.json
# schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json
# doc: https://golangci-lint.run/docs/configuration/file/
# reference: https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
# github repo: https://github.com/golangci/golangci-lint/tree/main
#
# golangci-lint configuration for cryptoutil project
# This project uses Go 1.25.4 with golangci-lint v2.6.2
#
# Usage: golangci-lint run --timeout=10m

version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 0  # Use all available CPUs

output:
  formats:
    tab:
      path: stdout
  sort-order:
    - linter
    - severity
    - file
