# $schema: https://json.schemastore.org/golangci-lint.json
version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 0

output:
  formats:
    tab:
      path: stdout
  sort-order: [linter, severity, file]

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - godot
    - copyloopvar
    - goconst
    - importas
    - gosec
    - noctx
    - wrapcheck
    - errorlint
    - testpackage
    - gomodguard
    - gomoddirectives
    - prealloc
    - bodyclose
    - mnd
    - wsl_v5
    - nlreturn
    - goheader
    - depguard
  disable:
    - dupl
    - gocyclo
    - godox

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      severity: medium
      confidence: medium
      excludes: [G204, G301, G302, G304, G402]
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 1
      min-occurrences: 2
      numbers: true
    mnd:
      ignored-numbers: ['2']
      ignored-functions: ['math.*', 'len', 'make']
    dupl:
      threshold: 100
    misspell:
      locale: US
    revive:
      severity: warning
    godot:
      scope: declarations
      capital: false
    godox:
      keywords: [TODO, FIXME, BUG, HACK]
    thelper:
      test:
        begin: true
    testpackage:
      skip-regexp: '.*_test\.go$'
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: "Use Go 1.13+ error wrapping instead"
    importas:
      alias:
        # JOSE libraries
        - { pkg: "github.com/lestrrat-go/jwx/v3/jwe", alias: joseJwe }
        - { pkg: "github.com/lestrrat-go/jwx/v3/jwk", alias: joseJwk }
        - { pkg: "github.com/lestrrat-go/jwx/v3/jws", alias: joseJws }
        - { pkg: "github.com/lestrrat-go/jwx/v3/jwa", alias: joseJwa }
        # Third-party
        - { pkg: "github.com/google/uuid", alias: googleUuid }
        - { pkg: "encoding/json", alias: json }
        - { pkg: "encoding/xml", alias: xml }
        - { pkg: "net/http", alias: http }
        - { pkg: "github.com/gofiber/fiber/v2", alias: fiber }
        - { pkg: "github.com/stretchr/testify", alias: testify }
        # Cryptoutil API
        - { pkg: "cryptoutil/api/client", alias: cryptoutilOpenapiClient }
        - { pkg: "cryptoutil/api/model", alias: cryptoutilOpenapiModel }
        - { pkg: "cryptoutil/api/server", alias: cryptoutilOpenapiServer }
        # Cryptoutil cmd
        - { pkg: "cryptoutil/internal/cmd", alias: cryptoutilCmd }
        - { pkg: "cryptoutil/internal/cmd/cryptoutil", alias: cryptoutilCmdCryptoutil }
        - { pkg: "cryptoutil/internal/cmd/workflow", alias: cryptoutilWorkflow }
        - { pkg: "cryptoutil/internal/cmd/cicd/common", alias: cryptoutilCmdCicdCommon }
        - { pkg: "cryptoutil/internal/cmd/cicd/all_enforce_utf8", alias: cryptoutilCmdCicdAllEnforceUtf8 }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_check_circular_package_dependencies", alias: cryptoutilCmdCicdGoCheckCircularPackageDependencies }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_check_identity_imports", alias: cryptoutilCmdCicdGoCheckIdentityImports }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_enforce_any", alias: cryptoutilCmdCicdGoEnforceAny }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_enforce_test_patterns", alias: cryptoutilCmdCicdGoEnforceTestPatterns }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_fix_all", alias: cryptoutilCmdCicdGoFixAll }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_fix_copyloopvar", alias: cryptoutilCmdCicdGoFixCopyLoopVar }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_fix_staticcheck_error_strings", alias: cryptoutilCmdCicdGoFixStaticcheckErrorStrings }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_fix_thelper", alias: cryptoutilCmdCicdGoFixTHelper }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_generate_postmortem", alias: cryptoutilGoGeneratePostmortem }
        - { pkg: "cryptoutil/internal/cmd/cicd/go_update_direct_dependencies", alias: cryptoutilCmdCicdGoUpdateDirectDependencies }
        - { pkg: "cryptoutil/internal/cmd/cicd/github_workflow_lint", alias: cryptoutilCmdCicdGithubWorkflowLint }
        # Cryptoutil test
        - { pkg: "cryptoutil/internal/test/e2e", alias: cryptoutilE2E }
        - { pkg: "cryptoutil/internal/identity/test/testutils", alias: cryptoutilIdentityTestTestutils }
        # Cryptoutil common
        - { pkg: "cryptoutil/internal/common/apperr", alias: cryptoutilAppErr }
        - { pkg: "cryptoutil/internal/common/config", alias: cryptoutilConfig }
        - { pkg: "cryptoutil/internal/common/container", alias: cryptoutilContainer }
        - { pkg: "cryptoutil/internal/common/magic", alias: cryptoutilMagic }
        - { pkg: "cryptoutil/internal/common/pool", alias: cryptoutilPool }
        - { pkg: "cryptoutil/internal/common/telemetry", alias: cryptoutilTelemetry }
        - { pkg: "cryptoutil/internal/common/testutil", alias: cryptoutilTestutil }
        - { pkg: "cryptoutil/internal/common/util", alias: cryptoutilUtil }
        - { pkg: "cryptoutil/internal/common/util/combinations", alias: cryptoutilCombinations }
        - { pkg: "cryptoutil/internal/common/util/datetime", alias: cryptoutilDateTime }
        - { pkg: "cryptoutil/internal/common/util/files", alias: cryptoutilFiles }
        - { pkg: "cryptoutil/internal/common/util/network", alias: cryptoutilNetwork }
        - { pkg: "cryptoutil/internal/common/util/sysinfo", alias: cryptoutilSysinfo }
        # Cryptoutil crypto
        - { pkg: "cryptoutil/internal/common/crypto/asn1", alias: cryptoutilAsn1 }
        - { pkg: "cryptoutil/internal/common/crypto/certificate", alias: cryptoutilCertificate }
        - { pkg: "cryptoutil/internal/common/crypto/digests", alias: cryptoutilDigests }
        - { pkg: "cryptoutil/internal/common/crypto/jose", alias: cryptoutilJose }
        - { pkg: "cryptoutil/internal/common/crypto/keygen", alias: cryptoutilKeyGen }
        # Cryptoutil server
        - { pkg: "cryptoutil/internal/server/application", alias: cryptoutilServerApplication }
        - { pkg: "cryptoutil/internal/server/businesslogic", alias: cryptoutilBusinessLogic }
        - { pkg: "cryptoutil/internal/server/handler", alias: cryptoutilOpenapiHandler }
        - { pkg: "cryptoutil/internal/server/barrier", alias: cryptoutilBarrierService }
        - { pkg: "cryptoutil/internal/server/barrier/contentkeysservice", alias: cryptoutilContentKeysService }
        - { pkg: "cryptoutil/internal/server/barrier/intermediatekeysservice", alias: cryptoutilIntermediateKeysService }
        - { pkg: "cryptoutil/internal/server/barrier/rootkeysservice", alias: cryptoutilRootKeysService }
        - { pkg: "cryptoutil/internal/server/barrier/unsealkeysservice", alias: cryptoutilUnsealKeysService }
        - { pkg: "cryptoutil/internal/server/repository/orm", alias: cryptoutilOrmRepository }
        - { pkg: "cryptoutil/internal/server/repository/sqlrepository", alias: cryptoutilSQLRepository }
        # Cryptoutil identity
        - { pkg: "cryptoutil/internal/identity/apperr", alias: cryptoutilIdentityAppErr }
        - { pkg: "cryptoutil/internal/identity/config", alias: cryptoutilIdentityConfig }
        - { pkg: "cryptoutil/internal/identity/domain", alias: cryptoutilIdentityDomain }
        - { pkg: "cryptoutil/internal/identity/magic", alias: cryptoutilIdentityMagic }
        - { pkg: "cryptoutil/internal/identity/repository", alias: cryptoutilIdentityRepository }
        - { pkg: "cryptoutil/internal/identity/issuer", alias: cryptoutilIdentityIssuer }
        - { pkg: "cryptoutil/internal/identity/authz", alias: cryptoutilIdentityAuthz }
        - { pkg: "cryptoutil/internal/identity/authz/clientauth", alias: cryptoutilIdentityClientAuth }
        - { pkg: "cryptoutil/internal/identity/idp", alias: cryptoutilIdentityIdp }
        - { pkg: "cryptoutil/internal/identity/idp/auth", alias: cryptoutilIdentityAuth }
        - { pkg: "cryptoutil/internal/identity/server", alias: cryptoutilIdentityServer }
        # Crypto packages
        - { pkg: "crypto/aes", alias: aes }
        - { pkg: "crypto/ecdsa", alias: ecdsa }
        - { pkg: "crypto/hmac", alias: hmac }
        - { pkg: "crypto/rsa", alias: rsa }
        - { pkg: "crypto/sha256", alias: sha256 }
        - { pkg: "crypto/sha512", alias: sha512 }
        - { pkg: "crypto/rand", alias: crand }

issues:
  max-issues-per-linter: 100
  max-same-issues: 20

severity:
  default: error
  rules:
    - linters: [revive, godot]
      severity: warning
    - linters: [misspell]
      severity: info
