# golangci-lint configuration for cryptoutil project
# 
# Note: This project uses Go 1.25.1, but golangci-lint may be built with an older version.
# If you encounter "Go language version ... is lower than the targeted Go version" errors:
# 1. Install golangci-lint built with Go 1.25+, or
# 2. Use individual tools: gofumpt, goimports, go vet, gosec
#
# Usage: golangci-lint run --timeout=10m

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Security
    - gosec
    
    # Code quality
    - gocyclo
    - gofmt
    - goimports
    - revive
    - stylecheck
    
    # Performance
    - prealloc
    - bodyclose
    
    # Maintainability
    - dupl
    - goconst
    - misspell
    - unparam
    - unconvert
    - whitespace
    
    # Error handling
    - errorlint

  disable:
    # Disable to avoid Go version conflicts
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
      
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G101
      - G107
      
  gocyclo:
    min-complexity: 15
    
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
    
  dupl:
    threshold: 100
    
  misspell:
    locale: US
    ignore-words:
      - cryptoutil
      - keygen
      - jwk
      - jwe
      - jws
      - ecdsa
      - ecdh
      - rsa
      - hmac
      
  revive:
    severity: warning
    
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-dirs:
    - vendor
    - api  # Skip generated OpenAPI code
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  uniq-by-line: true
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
        
    - path: cmd/.*/main\.go
      linters:
        - gocyclo
        
    - path: .*_test_util\.go
      linters:
        - revive

severity:
  default-severity: error
  rules:
    - linters:
        - revive
        - stylecheck
      severity: warning
    - linters:
        - misspell
      severity: info