version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errorlint
    - goconst
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - gosec
    - importas
    - mnd
    - nlreturn
    - noctx
    - prealloc
    - revive
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - wrapcheck
    - wsl
  disable:
    - dupl
    - gocyclo
    - godox
  settings:
    depguard:
      rules:
        identity-domain-isolation:
          files:
            - internal/identity/**/*.go
          deny:
            - pkg: cryptoutil/internal/server
              desc: Identity module must not depend on cryptoutil KMS server
            - pkg: cryptoutil/internal/client
              desc: Identity module must not depend on cryptoutil KMS client
            - pkg: cryptoutil/api
              desc: Identity module must not depend on cryptoutil OpenAPI generated code
            - pkg: cryptoutil/cmd/cryptoutil
              desc: Identity module must not depend on cryptoutil CLI
            - pkg: cryptoutil/internal/common/crypto
              desc: Identity module must not depend on cryptoutil crypto utilities (use standard library instead)
            - pkg: cryptoutil/internal/common/pool
              desc: Identity module must not depend on cryptoutil resource pools
            - pkg: cryptoutil/internal/common/container
              desc: Identity module must not depend on cryptoutil container utilities
            - pkg: cryptoutil/internal/common/telemetry
              desc: Identity module must not depend on cryptoutil telemetry (use standard slog instead)
            - pkg: cryptoutil/internal/common/util
              desc: Identity module must not depend on cryptoutil utilities
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 1
      min-occurrences: 2
      numbers: true
    gocyclo:
      min-complexity: 15
    godot:
      scope: declarations
      capital: false
    godox:
      keywords:
        - TODO
        - FIXME
        - BUG
        - HACK
    goheader:
      template: |
        {{ LICENSE }}
      values:
        const:
          LICENSE: |
            Copyright (c) 2025 Justin Cranford
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
                - fmt
    gosec:
      excludes:
        - G204
        - G301
        - G302
        - G304
        - G402
      severity: medium
      confidence: medium
    importas:
      alias:
        - pkg: github.com/lestrrat-go/jwx/v3/jwe
          alias: joseJwe
        - pkg: github.com/lestrrat-go/jwx/v3/jwk
          alias: joseJwk
        - pkg: github.com/lestrrat-go/jwx/v3/jws
          alias: joseJws
        - pkg: github.com/lestrrat-go/jwx/v3/jwa
          alias: joseJwa
        - pkg: github.com/google/uuid
          alias: googleUuid
        - pkg: encoding/json
          alias: json
        - pkg: encoding/xml
          alias: xml
        - pkg: net/http
          alias: http
        - pkg: github.com/gofiber/fiber/v2
          alias: fiber
        - pkg: github.com/stretchr/testify
          alias: testify
        - pkg: cryptoutil/api/client
          alias: cryptoutilOpenapiClient
        - pkg: cryptoutil/api/model
          alias: cryptoutilOpenapiModel
        - pkg: cryptoutil/api/server
          alias: cryptoutilOpenapiServer
        - pkg: cryptoutil/internal/client
          alias: cryptoutilClient
        - pkg: cryptoutil/internal/cmd
          alias: cryptoutilCmd
        - pkg: cryptoutil/internal/cmd/cryptoutil
          alias: cryptoutilCmdCryptoutil
        - pkg: cryptoutil/internal/cmd/workflow
          alias: cryptoutilWorkflow
        - pkg: cryptoutil/internal/test/e2e
          alias: cryptoutilE2E
        - pkg: cryptoutil/internal/common/apperr
          alias: cryptoutilAppErr
        - pkg: cryptoutil/internal/common/config
          alias: cryptoutilConfig
        - pkg: cryptoutil/internal/common/container
          alias: cryptoutilContainer
        - pkg: cryptoutil/internal/common/magic
          alias: cryptoutilMagic
        - pkg: cryptoutil/internal/common/pool
          alias: cryptoutilPool
        - pkg: cryptoutil/internal/common/telemetry
          alias: cryptoutilTelemetry
        - pkg: cryptoutil/internal/common/util
          alias: cryptoutilUtil
        - pkg: cryptoutil/internal/common/util/combinations
          alias: cryptoutilCombinations
        - pkg: cryptoutil/internal/common/util/datetime
          alias: cryptoutilDateTime
        - pkg: cryptoutil/internal/common/util/network
          alias: cryptoutilNetwork
        - pkg: cryptoutil/internal/common/util/sysinfo
          alias: cryptoutilSysinfo
        - pkg: cryptoutil/internal/common/crypto/asn1
          alias: cryptoutilAsn1
        - pkg: cryptoutil/internal/common/crypto/certificate
          alias: cryptoutilCertificate
        - pkg: cryptoutil/internal/common/crypto/digests
          alias: cryptoutilDigests
        - pkg: cryptoutil/internal/common/crypto/jose
          alias: cryptoutilJose
        - pkg: cryptoutil/internal/common/crypto/keygen
          alias: cryptoutilKeyGen
        - pkg: cryptoutil/internal/server/application
          alias: cryptoutilServerApplication
        - pkg: cryptoutil/internal/server/businesslogic
          alias: cryptoutilBusinessLogic
        - pkg: cryptoutil/internal/server/handler
          alias: cryptoutilOpenapiHandler
        - pkg: cryptoutil/internal/server/barrier
          alias: cryptoutilBarrierService
        - pkg: cryptoutil/internal/server/barrier/contentkeysservice
          alias: cryptoutilContentKeysService
        - pkg: cryptoutil/internal/server/barrier/intermediatekeysservice
          alias: cryptoutilIntermediateKeysService
        - pkg: cryptoutil/internal/server/barrier/rootkeysservice
          alias: cryptoutilRootKeysService
        - pkg: cryptoutil/internal/server/barrier/unsealkeysservice
          alias: cryptoutilUnsealKeysService
        - pkg: cryptoutil/internal/server/repository/orm
          alias: cryptoutilOrmRepository
        - pkg: cryptoutil/internal/server/repository/sqlrepository
          alias: cryptoutilSQLRepository
        - pkg: cryptoutil/internal/identity/apperr
          alias: cryptoutilIdentityAppErr
        - pkg: cryptoutil/internal/identity/config
          alias: cryptoutilIdentityConfig
        - pkg: cryptoutil/internal/identity/domain
          alias: cryptoutilIdentityDomain
        - pkg: cryptoutil/internal/identity/magic
          alias: cryptoutilIdentityMagic
        - pkg: cryptoutil/internal/identity/repository
          alias: cryptoutilIdentityRepository
        - pkg: cryptoutil/internal/identity/issuer
          alias: cryptoutilIdentityIssuer
        - pkg: cryptoutil/internal/identity/authz
          alias: cryptoutilIdentityAuthz
        - pkg: cryptoutil/internal/identity/authz/clientauth
          alias: cryptoutilIdentityClientAuth
        - pkg: cryptoutil/internal/identity/idp
          alias: cryptoutilIdentityIdp
        - pkg: cryptoutil/internal/identity/idp/auth
          alias: cryptoutilIdentityAuth
        - pkg: cryptoutil/internal/identity/server
          alias: cryptoutilIdentityServer
        - pkg: crypto/aes
          alias: aes
        - pkg: crypto/ecdsa
          alias: ecdsa
        - pkg: crypto/hmac
          alias: hmac
        - pkg: crypto/rsa
          alias: rsa
        - pkg: crypto/sha256
          alias: sha256
        - pkg: crypto/sha512
          alias: sha512
        - pkg: crypto/rand
          alias: crand
    lll:
      line-length: 190
    misspell:
      locale: US
      ignore-rules:
        - cryptoutil
        - keygen
        - jwa
        - jwk
        - jwe
        - jws
        - ecdsa
        - ecdh
        - rsa
        - hmac
        - aes
        - pkcs
        - pkix
        - x509
        - pem
        - der
        - ikm
    mnd:
      ignored-numbers:
        - "2"
      ignored-functions:
        - math.*
        - len
        - make
    revive:
      severity: warning
    staticcheck:
      checks:
        - all
        - -ST1000
    testpackage:
      skip-regexp: .*_test\.go$
    thelper:
      test:
        begin: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - (*github.com/gofiber/fiber/v2.Ctx).JSON(
        - (*github.com/gofiber/fiber/v2.Ctx).SendStatus(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
        path: _test\.go
      - linters:
          - goconst
          - wrapcheck
        path: internal/cmd/cicd/cicd\.go
      - linters:
          - goconst
        path: internal/cmd/cicd/cicd_test\.go
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - .idea
      - .vscode
      - .project
      - .settings
      - .classpath
      - .buildpath
      - .git
      - .github
      - test/load
      - dast-reports
      - e2e-reports
      - load-reports
      - test-reports
      - test-results
      - workflow-reports
      - vendor
      - api/client
      - api/model
      - api/server
      - configs
      - deployments
      - .zap
      - docs
      - static
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 100
  max-same-issues: 20
  uniq-by-line: true
severity:
  default: error
  rules:
    - linters:
        - revive
        - staticcheck
      severity: warning
    - linters:
        - misspell
      severity: info
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.com/justincranford/cryptoutil
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - .idea
      - .vscode
      - .project
      - .settings
      - .classpath
      - .buildpath
      - .git
      - .github
      - test/load
      - dast-reports
      - e2e-reports
      - load-reports
      - test-reports
      - test-results
      - workflow-reports
      - vendor
      - api/client
      - api/model
      - api/server
      - configs
      - deployments
      - .zap
      - docs
      - static
      - third_party$
      - builtin$
      - examples$
