# golangci-lint configuration for cryptoutil project
# 
# This project uses Go 1.25.1 with golangci-lint v1.25.1
# Note: typecheck is disabled due to import resolution issues with module dependencies
# All other linters are compatible with the current Go version
#
# Usage: golangci-lint run --timeout=10m

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Security
    - gosec
    
    # Code quality
    - gofmt
    - goimports
    - revive
    - stylecheck
    
    # Performance
    - prealloc
    - bodyclose
    
    # Maintainability
    - goconst
    - misspell
    - unparam
    - unconvert
    - whitespace
    
    # Error handling
    - errorlint

  disable:
    # Disable due to import resolution issues with module dependencies
    - typecheck
    
    # Disabled for code quality/complexity management
    - dupl      # Code duplication detection
    - gocyclo   # Cyclomatic complexity

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
      
  gosec:
    severity: medium
    confidence: medium
      
  gocyclo:
    min-complexity: 15
    
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: false
    
  dupl:
    threshold: 100
    
  misspell:
    locale: US
    ignore-words:
      - cryptoutil
      - keygen
      - jwk
      - jwe
      - jws
      - ecdsa
      - ecdh
      - rsa
      - hmac
      
  revive:
    severity: warning
    
  stylecheck:
    checks: ["all", "-ST1000"]

issues:
  exclude-dirs:
    - vendor
    - api  # Skip generated OpenAPI code
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  uniq-by-line: true
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        
    - path: cmd/.*/main\.go
      linters:
        - gocyclo
        
    - path: .*_test_util\.go
      linters:
        - revive
        
    # SQL type names - too invasive to refactor (79+ references) 
    - path: internal/server/repository/sqlrepository/
      text: "ST1003"
      linters:
        - stylecheck
    - path: internal/server/application/application_core.go
      text: "SqlRepository should be SQLRepository"
      linters:
        - stylecheck

severity:
  default-severity: error
  rules:
    - linters:
        - revive
        - stylecheck
      severity: warning
    - linters:
        - misspell
      severity: info