# $schema: https://json.schemastore.org/golangci-lint.json
version: 2

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 0

output:
  format: tab
  sort-results: true
  sort-order: [linter, severity, file]
  show-stats: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - godot
    - copyloopvar
    - goconst
    - importas
    - gosec
    - noctx
    - wrapcheck
    - errorlint
    - testpackage
    - gomodguard
    - gomoddirectives
    - prealloc
    - bodyclose
    - mnd
    - wsl_v5
    - nlreturn
    # - goheader  # Temporarily disabled - causing file corruption with v2
    - depguard
    - exhaustive
    - nilnil
    - nilerr
    - makezero
  disable:
    - dupl
    - gocyclo
    - godox

  exclusions:
    paths:
      - api/client
      - api/model
      - api/server
      - api/idp
      - api/authz
      - test-output
      - workflow-reports
      - vendor
    rules:
      # Exclude nilnil from pool.go (intentional "nothing to report" pattern).
      - path: "internal/common/pool/pool\\.go$"
        linters: [nilnil]
      # Exclude nilnil from datetime.go (intentional "not found" pattern).
      - path: "internal/common/util/datetime/datetime\\.go$"
        linters: [nilnil]
      # Exclude nilnil from test files (mock implementations).
      - path: "_test\\.go$"
        linters: [nilnil]
      # Exclude nilnil from step_up_auth.go (intentional pattern).
      - path: "internal/identity/idp/userauth/step_up_auth\\.go$"
        linters: [nilnil]
      # Exclude nilnil from oam_orm_mapper.go (intentional pattern).
      - path: "internal/kms/businesslogic/oam_orm_mapper\\.go$"
        linters: [nilnil]
      # Exclude nilnil from nullable_uuid.go (sql.Scanner pattern).
      - path: "internal/identity/domain/nullable_uuid\\.go$"
        linters: [nilnil]
      # Exclude nilnil from secret_rotation_service.go (intentional pattern).
      - path: "internal/identity/rotation/secret_rotation_service\\.go$"
        linters: [nilnil]
      # Exclude nilerr from jwk_util.go (intentional type-check pattern).
      - path: "internal/jose/jwk_util\\.go$"
        linters: [nilerr]
      # Exclude nilerr from secret.go (intentional pattern).
      - path: "internal/crypto/secret\\.go$"
        linters: [nilerr]
      # Exclude nilerr from issuer service (intentional pattern).
      - path: "internal/identity/issuer/service\\.go$"
        linters: [nilerr]
      # Exclude wrapcheck from jose server handlers (Fiber HTTP response helpers).
      - path: "internal/jose/server/handlers\\.go$"
        linters: [wrapcheck]
      # Exclude wrapcheck from jose handler adapter (Fiber HTTP response helpers).
      - path: "internal/jose/server/handler_adapter\\.go$"
        linters: [wrapcheck]
      # Exclude wrapcheck from jose audit config handlers (Fiber HTTP response helpers).
      - path: "internal/jose/server/audit_config_handlers\\.go$"
        linters: [wrapcheck]
      # Exclude wrapcheck from jose server builder (template app Start/Shutdown delegation).
      - path: "internal/jose/server/server_builder\\.go$"
        linters: [wrapcheck]
      # Exclude wrapcheck from cipher-im session manager wrapper (internal package).
      - path: "internal/apps/cipher/im/server/businesslogic/session_manager_service\\.go$"
        linters: [wrapcheck]
      # Exclude wrapcheck from template registration handlers (Fiber HTTP response helpers).
      - path: "internal/apps/template/service/server/apis/registration_handlers\\.go$"
        linters: [wrapcheck]
      # Exclude revive package-comments from doc.go (false positive with block comments).
      - path: "internal/shared/crypto/digests/doc\\.go$"
        linters: [revive]
        text: "package-comments"
      # Exclude revive package-comments from hash/doc.go (false positive with block comments).
      - path: "internal/shared/crypto/hash/doc\\.go$"
        linters: [revive]
        text: "package-comments"

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      confidence: medium
      excludes: [G204, G301, G302, G304, G402]
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 1
      min-occurrences: 2
      numbers: true
    mnd:
      ignored-numbers: ['2']
      ignored-functions: ['math.*', 'len', 'make']
    dupl:
      threshold: 100
    misspell:
      locale: US
    revive: {}
    godot:
      scope: declarations
      capital: false
    godox:
      keywords: [TODO, FIXME, BUG, HACK]
    exhaustive:
      default-signifies-exhaustive: true
    thelper:
      test:
        begin: true
    testpackage:
      skip-regexp: '.*_test\.go$'
    goheader:
      template: |-
        Copyright (c) {{ YEAR }} Justin Cranford
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: "Use Go 1.13+ error wrapping instead"
    importas:
      alias:
        # JOSE libraries
        - { pkg: "github.com/lestrrat-go/jwx/v3/jwe", alias: joseJwe }
        - { pkg: "github.com/lestrrat-go/jwx/v3/jwk", alias: joseJwk }
        - { pkg: "github.com/lestrrat-go/jwx/v3/jws", alias: joseJws }
        - { pkg: "github.com/lestrrat-go/jwx/v3/jwa", alias: joseJwa }
        # Third-party
        - { pkg: "github.com/google/uuid", alias: googleUuid }
        - { pkg: "encoding/json", alias: json }
        - { pkg: "encoding/xml", alias: xml }
        - { pkg: "net/http", alias: http }
        - { pkg: "github.com/gofiber/fiber/v2", alias: fiber }
        - { pkg: "github.com/stretchr/testify", alias: testify }
        # Cryptoutil API
        - { pkg: "cryptoutil/api/client", alias: cryptoutilOpenapiClient }
        - { pkg: "cryptoutil/api/model", alias: cryptoutilOpenapiModel }
        - { pkg: "cryptoutil/api/server", alias: cryptoutilOpenapiServer }
        # Cryptoutil cmd
        - pkg: "cryptoutil/internal/cmd"
          alias: cryptoutilCmd
        - pkg: "cryptoutil/internal/cmd/cicd"
          alias: cryptoutilCmdCicd
        - pkg: "cryptoutil/internal/cmd/cryptoutil"
          alias: cryptoutilCmdCryptoutil
        - pkg: "cryptoutil/internal/cmd/workflow"
          alias: cryptoutilWorkflow
        - pkg: "cryptoutil/internal/cmd/cicd/common"
          alias: cryptoutilCmdCicdCommon
        - pkg: "cryptoutil/internal/cmd/cicd/all_enforce_utf8"
          alias: cryptoutilCmdCicdAllEnforceUtf8
        - pkg: "cryptoutil/internal/cmd/cicd/go_check_circular_package_dependencies"
          alias: cryptoutilCmdCicdGoCheckCircularPackageDependencies
        - pkg: "cryptoutil/internal/cmd/cicd/go_enforce_any"
          alias: cryptoutilCmdCicdGoEnforceAny
        - pkg: "cryptoutil/internal/cmd/cicd/go_enforce_test_patterns"
          alias: cryptoutilCmdCicdGoEnforceTestPatterns
        - pkg: "cryptoutil/internal/cmd/cicd/go_fix_all"
          alias: cryptoutilCmdCicdGoFixAll
        - pkg: "cryptoutil/internal/cmd/cicd/go_fix_copyloopvar"
          alias: cryptoutilCmdCicdGoFixCopyLoopVar
        - pkg: "cryptoutil/internal/cmd/cicd/go_fix_thelper"
          alias: cryptoutilCmdCicdGoFixTHelper
        - pkg: "cryptoutil/internal/cmd/cicd/go_generate_postmortem"
          alias: cryptoutilGoGeneratePostmortem
        - pkg: "cryptoutil/internal/cmd/cicd/go_update_direct_dependencies"
          alias: cryptoutilCmdCicdGoUpdateDirectDependencies
        - pkg: "cryptoutil/internal/cmd/cicd/go_update_project_status"
          alias: cryptoutilCmdCicdGoUpdateProjectStatus
        - pkg: "cryptoutil/internal/cmd/cicd/go_update_project_status_v2"
          alias: cryptoutilGoUpdateProjectStatusV2
        - pkg: "cryptoutil/internal/cmd/cicd/github_workflow_lint"
          alias: cryptoutilCmdCicdGithubWorkflowLint
        # Cryptoutil test
        - pkg: "cryptoutil/internal/test/e2e"
          alias: cryptoutilE2E
        - pkg: "cryptoutil/internal/identity/test/testutils"
          alias: cryptoutilIdentityTestTestutils
        # Cryptoutil common
        - pkg: "cryptoutil/internal/common/apperr"
          alias: cryptoutilAppErr
        - pkg: "cryptoutil/internal/common/config"
          alias: cryptoutilConfig
        - pkg: "cryptoutil/internal/common/container"
          alias: cryptoutilContainer
        - pkg: "cryptoutil/internal/common/magic"
          alias: cryptoutilMagic
        - pkg: "cryptoutil/internal/common/pool"
          alias: cryptoutilPool
        - pkg: "cryptoutil/internal/common/telemetry"
          alias: cryptoutilTelemetry
        - pkg: "cryptoutil/internal/common/testutil"
          alias: cryptoutilTestutil
        - pkg: "cryptoutil/internal/common/util"
          alias: cryptoutilUtil
        - pkg: "cryptoutil/internal/common/util/combinations"
          alias: cryptoutilCombinations
        - pkg: "cryptoutil/internal/common/util/datetime"
          alias: cryptoutilDateTime
        - pkg: "cryptoutil/internal/common/util/files"
          alias: cryptoutilFiles
        - pkg: "cryptoutil/internal/common/util/network"
          alias: cryptoutilNetwork
        - pkg: "cryptoutil/internal/common/util/sysinfo"
          alias: cryptoutilSysinfo
        # Cryptoutil shared
        - pkg: "cryptoutil/internal/shared/apperr"
          alias: cryptoutilSharedApperr
        - pkg: "cryptoutil/internal/shared/testutil"
          alias: cryptoutilSharedTestutil
        - pkg: "cryptoutil/internal/shared/util"
          alias: cryptoutilSharedUtil
        - pkg: "cryptoutil/internal/shared/util/cache"
          alias: cryptoutilSharedUtilCache
        - pkg: "cryptoutil/internal/shared/util/files"
          alias: cryptoutilSharedUtilFiles
        - pkg: "cryptoutil/internal/shared/util/network"
          alias: cryptoutilSharedUtilNetwork
        - pkg: "cryptoutil/internal/shared/util/random"
          alias: cryptoutilSharedUtilRandom
        # Cryptoutil infra
        - pkg: "cryptoutil/internal/infra/tls"
          alias: cryptoutilTLS
        - pkg: "cryptoutil/internal/infra/demo"
          alias: cryptoutilDemo
        # Cryptoutil crypto
        - pkg: "cryptoutil/internal/common/crypto/asn1"
          alias: cryptoutilAsn1
        - pkg: "cryptoutil/internal/common/crypto/certificate"
          alias: cryptoutilCertificate
        - pkg: "cryptoutil/internal/common/crypto/digests"
          alias: cryptoutilDigests
        - pkg: "cryptoutil/internal/jose"
          alias: cryptoutilJose
        - pkg: "cryptoutil/internal/common/crypto/keygen"
          alias: cryptoutilKeyGen
        # Cryptoutil KMS
        - pkg: "cryptoutil/internal/kms/server/application"
          alias: cryptoutilServerApplication
        - pkg: "cryptoutil/internal/kms/businesslogic"
          alias: cryptoutilBusinessLogic
        - pkg: "cryptoutil/internal/kms/handler"
          alias: cryptoutilOpenapiHandler
        - pkg: "cryptoutil/internal/shared/barrier"
          alias: cryptoutilBarrierService
        - pkg: "cryptoutil/internal/shared/barrier/contentkeysservice"
          alias: cryptoutilContentKeysService
        - pkg: "cryptoutil/internal/shared/barrier/intermediatekeysservice"
          alias: cryptoutilIntermediateKeysService
        - pkg: "cryptoutil/internal/shared/barrier/rootkeysservice"
          alias: cryptoutilRootKeysService
        - pkg: "cryptoutil/internal/shared/barrier/unsealkeysservice"
          alias: cryptoutilUnsealKeysService
        - pkg: "cryptoutil/internal/kms/server/repository/orm"
          alias: cryptoutilOrmRepository
        - pkg: "cryptoutil/internal/kms/server/repository/sqlrepository"
          alias: cryptoutilSQLRepository
        # Cryptoutil template
        - pkg: "cryptoutil/internal/template/server"
          alias: cryptoutilTemplateServer
        # Cryptoutil cipher
        - pkg: "cryptoutil/internal/cipher/crypto"
          alias: cryptoutilCipherCrypto
        - pkg: "cryptoutil/internal/cipher/domain"
          alias: cryptoutilCipherDomain
        - pkg: "cryptoutil/internal/cipher/e2e"
          alias: cryptoutilCipherE2E
        - pkg: "cryptoutil/internal/cipher/integration"
          alias: cryptoutilCipherIntegration
        - pkg: "cryptoutil/internal/cipher/repository"
          alias: cryptoutilCipherRepository
        - pkg: "cryptoutil/internal/cipher/server"
          alias: cryptoutilCipherServer
        # Cryptoutil apps
        - pkg: "cryptoutil/internal/apps/ca/server/config"
          alias: cryptoutilAppsCaServerConfig
        - pkg: "cryptoutil/internal/apps/cipher"
          alias: cryptoutilAppsCipher
        - pkg: "cryptoutil/internal/apps/cipher/im"
          alias: cryptoutilAppsCipherIm
        - pkg: "cryptoutil/internal/apps/cipher/im/domain"
          alias: cryptoutilAppsCipherImDomain
        - pkg: "cryptoutil/internal/apps/cipher/im/repository"
          alias: cryptoutilAppsCipherImRepository
        - pkg: "cryptoutil/internal/apps/cipher/im/server"
          alias: cryptoutilAppsCipherImServer
        - pkg: "cryptoutil/internal/apps/cipher/im/server/apis"
          alias: cryptoutilAppsCipherImServerApis
        - pkg: "cryptoutil/internal/apps/cipher/im/server/config"
          alias: cryptoutilAppsCipherImServerConfig
        - pkg: "cryptoutil/internal/apps/identity/authz/server/config"
          alias: cryptoutilAppsIdentityAuthzServerConfig
        - pkg: "cryptoutil/internal/apps/identity/idp/server/config"
          alias: cryptoutilAppsIdentityIdpServerConfig
        - pkg: "cryptoutil/internal/apps/identity/rp/server"
          alias: cryptoutilAppsIdentityRpServer
        - pkg: "cryptoutil/internal/apps/identity/rp/server/config"
          alias: cryptoutilAppsIdentityRpServerConfig
        - pkg: "cryptoutil/internal/apps/identity/rs/server/config"
          alias: cryptoutilAppsIdentityRsServerConfig
        - pkg: "cryptoutil/internal/apps/jose/ja/repository"
          alias: cryptoutilAppsJoseJaRepository
        - pkg: "cryptoutil/internal/apps/jose/ja/server/apis"
          alias: cryptoutilAppsJoseJaServerApis
        - pkg: "cryptoutil/internal/apps/jose/ja/server/config"
          alias: cryptoutilAppsJoseJaServerConfig
        - pkg: "cryptoutil/internal/apps/template/service/server"
          alias: cryptoutilAppsTemplateServiceServer
        - pkg: "cryptoutil/internal/apps/template/service/server/repository"
          alias: cryptoutilAppsTemplateServiceServerRepository
        # Cryptoutil jose
        - pkg: "cryptoutil/internal/jose/domain"
          alias: cryptoutilJoseDomain
        - pkg: "cryptoutil/internal/jose/repository"
          alias: cryptoutilJoseRepository
        - pkg: "cryptoutil/internal/jose/server/middleware"
          alias: cryptoutilJoseServerMiddleware
        - pkg: "cryptoutil/internal/jose/service"
          alias: cryptoutilJoseService
        # Cryptoutil identity
        - pkg: "cryptoutil/internal/identity/apperr"
          alias: cryptoutilIdentityAppErr
        - pkg: "cryptoutil/internal/identity/authz"
          alias: cryptoutilIdentityAuthz
        - pkg: "cryptoutil/internal/identity/authz/clientauth"
          alias: cryptoutilIdentityClientAuth
        - pkg: "cryptoutil/internal/identity/bootstrap"
          alias: cryptoutilIdentityBootstrap
        - pkg: "cryptoutil/internal/identity/config"
          alias: cryptoutilIdentityConfig
        - pkg: "cryptoutil/internal/identity/domain"
          alias: cryptoutilIdentityDomain
        - pkg: "cryptoutil/internal/identity/healthcheck"
          alias: cryptoutilIdentityHealthcheck
        - pkg: "cryptoutil/internal/identity/idp"
          alias: cryptoutilIdentityIdp
        - pkg: "cryptoutil/internal/identity/idp/auth"
          alias: cryptoutilIdentityAuth
        - pkg: "cryptoutil/internal/identity/idp/userauth"
          alias: cryptoutilIdentityIdpUserauth
        - pkg: "cryptoutil/internal/identity/idp/userauth/mocks"
          alias: cryptoutilIdentityIdpUserauthMocks
        - pkg: "cryptoutil/internal/identity/issuer"
          alias: cryptoutilIdentityIssuer
        - pkg: "cryptoutil/internal/identity/jobs"
          alias: cryptoutilIdentityJobs
        - pkg: "cryptoutil/internal/identity/magic"
          alias: cryptoutilIdentityMagic
        - pkg: "cryptoutil/internal/identity/process"
          alias: cryptoutilIdentityProcess
        - pkg: "cryptoutil/internal/identity/repository"
          alias: cryptoutilIdentityRepository
        - pkg: "cryptoutil/internal/identity/repository/orm"
          alias: cryptoutilIdentityORM
        - pkg: "cryptoutil/internal/identity/rotation"
          alias: cryptoutilIdentityRotation
        - pkg: "cryptoutil/internal/identity/server"
          alias: cryptoutilIdentityServer
        - pkg: "cryptoutil/internal/identity/cmd/main"
          alias: cryptoutilIdentityCmd
        # Crypto packages
        - { pkg: "crypto/aes", alias: aes }
        - { pkg: "crypto/ecdsa", alias: ecdsa }
        - { pkg: "crypto/hmac", alias: hmac }
        - { pkg: "crypto/rsa", alias: rsa }
        - { pkg: "crypto/sha256", alias: sha256 }
        - { pkg: "crypto/sha512", alias: sha512 }
        - { pkg: "crypto/rand", alias: crand }

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
