# $schema: https://json.schemastore.org/golangci-lint.json
# schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json
# doc: https://golangci-lint.run/docs/configuration/file/
# reference: https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
# github repo: https://github.com/golangci/golangci-lint/tree/main
#
# golangci-lint configuration for cryptoutil project
# This project uses Go 1.25.4 with golangci-lint v2.6.2
#
# Usage: golangci-lint run --timeout=10m

version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 0  # Use all available CPUs

output:
  formats:
    tab:
      path: stdout
  sort-order:
    - linter
    - severity
    - file

linters:
  enable:
    # Essential linters (fast static analysis)
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs (Go's built-in vet)
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple, stylecheck in v2)
    - unused        # Find unused constants, variables, functions and types

    # Code quality linters (fast)
    - revive        # Golint replacement with more rules
    - godot         # Check for missing periods in documentation comments
    - copyloopvar   # Check for loop variables captured by reference
    - goconst       # Find repeated strings that could be constants
    - importas      # Enforce consistent import aliasing

    # Security and error handling
    - gosec         # Security-focused static analysis
    - noctx         # Check for missing context in HTTP requests
    - wrapcheck     # Check error wrapping consistency
    - errorlint     # Find code that will cause problems with Go 1.13 error wrapping

  settings:
    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G204  # Subprocess launched with variable
        - G301  # Directory permissions too permissive
        - G302  # File permissions too permissive
        - G304  # Potential file inclusion via variable
        - G402  # TLS InsecureSkipVerify set true
