# Markdownlint configuration for cryptoutil project

# Default state - only enable specific rules
default: false

# Enabled rules
MD001: true   # Heading levels should only increment by one level at a time
MD003: true   # Heading style (consistent)
MD004: true   # Unordered list style (consistent)
MD005: true   # Inconsistent indentation for list items at the same level
MD007: true   # Unordered list indentation
MD009: true   # Trailing spaces
MD010: true   # Hard tabs
MD011: true   # Reversed link syntax
MD012: true   # Multiple consecutive blank lines
MD013: false  # Line length - disabled (existing files exceed 80 chars significantly)
MD014: true   # Dollar signs used before commands without showing output
MD018: true   # No space after hash on atx style heading
MD019: true   # Multiple spaces after hash on atx style heading
MD020: true   # No space inside hashes on closed atx style heading
MD021: true   # Multiple spaces inside hashes on closed atx style heading
MD022: true   # Headings should be surrounded by blank lines
MD023: true   # Headings must start at the beginning of the line
MD024: false  # Multiple headings with the same content - disabled (acceptable in different sections)
MD025: false  # Multiple top-level headings in the same document - disabled (existing files have multiple H1s)
MD026: true   # Trailing punctuation in heading
MD027: true   # Multiple spaces after blockquote symbol
MD028: true   # Blank line inside blockquote
MD029: true   # Ordered list item prefix
MD030: true   # Spaces after list markers
MD031: true   # Fenced code blocks should be surrounded by blank lines
MD032: true   # Lists should be surrounded by blank lines
MD033: false  # Inline HTML - disabled (needed for GitHub-specific features)
MD034: false  # Bare URL used - disabled (existing documentation uses bare URLs)
MD036: false  # Emphasis used instead of heading - disabled (existing files use bold for section labels)
MD035: true   # Horizontal rule style
MD037: true   # Spaces inside emphasis markers
MD038: true   # Spaces inside code span elements
MD039: true   # Spaces inside link text
MD040: false  # Fenced code blocks should have a language specified - disabled (existing files use plain fences)
MD041: false  # First line in file should be a top level heading - disabled (not all docs start with h1)
MD042: true   # No empty links
MD043: false  # Required heading structure - disabled (too rigid)
MD044: false  # Proper names should have the correct capitalization - disabled (false positives)
MD045: true   # Images should have alternate text (alt text)
MD046: true   # Code block style
MD047: true   # Files should end with a single newline character
MD048: true   # Code fence style
MD049: true   # Emphasis style
MD050: true   # Strong style
MD051: true   # Link fragments should be valid
MD052: true   # Reference links and images should use a label that is defined
MD053: true   # Link and image reference definitions should be needed

# Rule-specific configuration
heading-style:
  style: "atx"  # Use atx style headings (# Heading)

ul-style:
  style: "dash"  # Use dash (-) for unordered lists

ul-indent:
  indent: 2  # Indent nested lists by 2 spaces

ol-prefix:
  style: "ordered"  # Use 1. 2. 3. for ordered lists

hr-style:
  style: "---"  # Use --- for horizontal rules

code-block-style:
  style: "fenced"  # Use fenced code blocks (```) instead of indented

code-fence-style:
  style: "backtick"  # Use backticks (```) for code fences

emphasis-style:
  style: "asterisk"  # Use * for emphasis

strong-style:
  style: "asterisk"  # Use ** for strong emphasis
