services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: USR
      POSTGRES_PASSWORD: PWD
      POSTGRES_DB: DB
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U USR -d DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cryptoutil-network

  cryptoutil:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cryptoutil-network

networks:
  cryptoutil-network:
    driver: bridge

#volumes:
#  postgres_data:
