services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    shm_size: 256mb
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d $$(cat /run/secrets/postgres_db)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cryptoutil-network

  cryptoutil:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cryptoutil-network

networks:
  cryptoutil-network:
    driver: bridge

#volumes:
#  postgres_data:

secrets:
  postgres_user:
    file: ./config/postgres_user.txt
  postgres_password:
    file: ./config/postgres_password.txt
  postgres_db:
    file: ./config/postgres_db.txt
