#!/usr/bin/env python3
# Script to write testserver_test.go without BOM
import os

content = (
    "// Copyright (c) 2025 Justin Cranford\n"
    "//\n"
    "\n"
    "package testserver_test\n"
    "\n"
    "import (\n"
    '\t"context"\n'
    '\t"errors"\n'
    '\t"fmt"\n'
    '\t"sync"\n'
    '\t"testing"\n'
    '\t"time"\n'
    "\n"
    '\t"github.com/stretchr/testify/assert"\n'
    '\t"github.com/stretchr/testify/require"\n'
    '\t"gorm.io/gorm"\n'
    "\n"
    '\tcryptoutilAppsTemplateServiceServer "cryptoutil/internal/apps/template/service/server"\n'
    '\tcryptoutilTestingTestserver "cryptoutil/internal/apps/template/service/testing/testserver"\n'
    ")\n"
    "\n"
    "// mockServer implements ServiceServer for testing without starting real HTTPS servers.\n"
    "type mockServer struct {\n"
    "\tmu          sync.Mutex\n"
    "\tpublicPort  int\n"
    "\tadminPort   int\n"
    "\tready       bool\n"
    "\tstartCalled bool\n"
    "\tstartDelay  time.Duration\n"
    "\tstartErr    error\n"
    "\tshutdownErr error\n"
    "}\n"
    "\n"
    "func newMockServer() *mockServer {\n"
    "\treturn &mockServer{}\n"
    "}\n"
    "\n"
    "// Start simulates a real server binding to ports: sets publicPort and adminPort under mutex.\n"
    "func (m *mockServer) Start(_ context.Context) error {\n"
    "\tif m.startDelay > 0 {\n"
    "\t\ttime.Sleep(m.startDelay)\n"
    "\t}\n"
    "\n"
    "\tif m.startErr != nil {\n"
    "\t\treturn m.startErr\n"
    "\t}\n"
    "\n"
    "\tm.mu.Lock()\n"
    "\tm.startCalled = true\n"
    "\tm.publicPort = 8080\n"
    "\tm.adminPort = 9090\n"
    "\tm.mu.Unlock()\n"
    "\n"
    "\treturn nil\n"
    "}\n"
    "\n"
    "func (m *mockServer) Shutdown(_ context.Context) error {\n"
    "\treturn m.shutdownErr\n"
    "}\n"
    "\n"
    "func (m *mockServer) DB() *gorm.DB {\n"
    "\treturn nil\n"
    "}\n"
    "\n"
    "func (m *mockServer) App() *cryptoutilAppsTemplateServiceServer.Application {\n"
    "\treturn nil\n"
    "}\n"
    "\n"
    "func (m *mockServer) PublicPort() int {\n"
    "\tm.mu.Lock()\n"
    "\tdefer m.mu.Unlock()\n"
    "\n"
    "\treturn m.publicPort\n"
    "}\n"
    "\n"
    "func (m *mockServer) AdminPort() int {\n"
    "\tm.mu.Lock()\n"
    "\tdefer m.mu.Unlock()\n"
    "\n"
    "\treturn m.adminPort\n"
    "}\n"
    "\n"
    "func (m *mockServer) SetReady(ready bool) {\n"
    "\tm.mu.Lock()\n"
    "\tm.ready = ready\n"
    "\tm.mu.Unlock()\n"
    "}\n"
    "\n"
    'func (m *mockServer) PublicBaseURL() string {\n'
    '\treturn "https://127.0.0.1:8080"\n'
    "}\n"
    "\n"
    "func (m *mockServer) AdminBaseURL() string {\n"
    '\treturn "https://127.0.0.1:9090"\n'
    "}\n"
    "\n"
    "func (m *mockServer) PublicServerActualPort() int {\n"
    "\tm.mu.Lock()\n"
    "\tdefer m.mu.Unlock()\n"
    "\n"
    "\treturn m.publicPort\n"
    "}\n"
    "\n"
    "func (m *mockServer) AdminServerActualPort() int {\n"
    "\tm.mu.Lock()\n"
    "\tdefer m.mu.Unlock()\n"
    "\n"
    "\treturn m.adminPort\n"
    "}\n"
    "\n"
    "func (m *mockServer) isStartCalled() bool {\n"
    "\tm.mu.Lock()\n"
    "\tdefer m.mu.Unlock()\n"
    "\n"
    "\treturn m.startCalled\n"
    "}\n"
    "\n"
    "func (m *mockServer) isReady() bool {\n"
    "\tm.mu.Lock()\n"
    "\tdefer m.mu.Unlock()\n"
    "\n"
    "\treturn m.ready\n"
    "}\n"
    "\n"
    "// captureTB wraps *testing.T to record Fatalf calls without exiting the test.\n"
    "// Used to exercise error code paths in StartAndWait that call t.Fatalf.\n"
    "type captureTB struct {\n"
    "\t*testing.T\n"
    "\tmu       sync.Mutex\n"
    "\tfatals   []string\n"
    "\tcleanups []func()\n"
    "}\n"
    "\n"
    "// Helper is a no-op override so captureTB call frames are not marked as test helpers.\n"
    "func (c *captureTB) Helper() {}\n"
    "\n"
    "// Fatalf records the fatal message without calling runtime.Goexit.\n"
    "func (c *captureTB) Fatalf(format string, args ...any) {\n"
    "\tc.mu.Lock()\n"
    "\tc.fatals = append(c.fatals, fmt.Sprintf(format, args...))\n"
    "\tc.mu.Unlock()\n"
    "}\n"
    "\n"
    "// Cleanup captures cleanup functions instead of registering them with *testing.T.\n"
    "func (c *captureTB) Cleanup(f func()) {\n"
    "\tc.mu.Lock()\n"
    "\tc.cleanups = append(c.cleanups, f)\n"
    "\tc.mu.Unlock()\n"
    "}\n"
    "\n"
    "func (c *captureTB) runCleanups() {\n"
    "\tc.mu.Lock()\n"
    "\tfns := make([]func(), len(c.cleanups))\n"
    "\tcopy(fns, c.cleanups)\n"
    "\tc.mu.Unlock()\n"
    "\n"
    "\tfor i := len(fns) - 1; i >= 0; i-- {\n"
    "\t\tfns[i]()\n"
    "\t}\n"
    "}\n"
    "\n"
    "func (c *captureTB) hasFatal() bool {\n"
    "\tc.mu.Lock()\n"
    "\tdefer c.mu.Unlock()\n"
    "\n"
    "\treturn len(c.fatals) > 0\n"
    "}\n"
    "\n"
    "func TestStartAndWait_Success(t *testing.T) {\n"
    "\tt.Parallel()\n"
    "\n"
    "\tctx := context.Background()\n"
    "\tsrv := newMockServer()\n"
    "\n"
    "\tresult := cryptoutilTestingTestserver.StartAndWait(ctx, t, srv)\n"
    "\n"
    "\trequire.NotNil(t, result)\n"
    '\tassert.True(t, srv.isStartCalled(), "Start should have been called")\n'
    '\tassert.True(t, srv.isReady(), "SetReady(true) should have been called")\n'
    "\n"
    "\tcastedResult, ok := result.(*mockServer)\n"
    '\trequire.True(t, ok, "returned server should be *mockServer")\n'
    '\tassert.Same(t, srv, castedResult, "returned server should be the same instance")\n'
    "}\n"
    "\n"
    "func TestStartAndWait_RegistersCleanup(t *testing.T) {\n"
    "\tt.Parallel()\n"
    "\n"
    "\tctx := context.Background()\n"
    "\tsrv := newMockServer()\n"
    "\n"
    '\tt.Run("inner", func(t *testing.T) {\n'
    "\t\tt.Parallel()\n"
    "\n"
    "\t\tresult := cryptoutilTestingTestserver.StartAndWait(ctx, t, srv)\n"
    "\t\trequire.NotNil(t, result)\n"
    "\t})\n"
    "}\n"
    "\n"
    "func TestStartAndWait_ReturnsOriginalServer(t *testing.T) {\n"
    "\tt.Parallel()\n"
    "\n"
    "\tctx := context.Background()\n"
    "\tsrv := newMockServer()\n"
    "\n"
    "\treturned := cryptoutilTestingTestserver.StartAndWait(ctx, t, srv)\n"
    '\tassert.Equal(t, "https://127.0.0.1:8080", returned.PublicBaseURL())\n'
    '\tassert.Equal(t, "https://127.0.0.1:9090", returned.AdminBaseURL())\n'
    "}\n"
    "\n"
    "func TestStartAndWait_PortsReady(t *testing.T) {\n"
    "\tt.Parallel()\n"
    "\n"
    "\tctx := context.Background()\n"
    "\tsrv := newMockServer()\n"
    "\n"
    "\tcryptoutilTestingTestserver.StartAndWait(ctx, t, srv)\n"
    "\n"
    "\tassert.Equal(t, 8080, srv.PublicPort())\n"
    "\tassert.Equal(t, 9090, srv.AdminPort())\n"
    "}\n"
    "\n"
    "func TestStartAndWait_StartError(t *testing.T) {\n"
    "\tt.Parallel()\n"
    "\n"
    "\tctx := context.Background()\n"
    "\tsrv := newMockServer()\n"
    '\tsrv.startErr = errors.New("simulated start failure")\n'
    "\n"
    "\tctb := &captureTB{T: t}\n"
    "\t_ = cryptoutilTestingTestserver.StartAndWait(ctx, ctb, srv)\n"
    "\tctb.runCleanups()\n"
    "\n"
    '\tassert.True(t, ctb.hasFatal(), "Fatalf should have been called for start error")\n'
    "}\n"
    "\n"
    "func TestStartAndWait_ShutdownError(t *testing.T) {\n"
    "\tt.Parallel()\n"
    "\n"
    "\tctx := context.Background()\n"
    "\n"
    '\tt.Run("shutdown error is logged without failing test", func(t *testing.T) {\n'
    "\t\tt.Parallel()\n"
    "\n"
    "\t\tsrv := newMockServer()\n"
    '\t\tsrv.shutdownErr = errors.New("simulated shutdown failure")\n'
    "\n"
    "\t\tresult := cryptoutilTestingTestserver.StartAndWait(ctx, t, srv)\n"
    "\t\trequire.NotNil(t, result)\n"
    "\t\t// cleanup runs when inner test ends, exercising the t.Logf path for shutdownErr\n"
    "\t})\n"
    "}\n"
)

path = os.path.join("internal", "apps", "template", "service", "testing", "testserver", "testserver_test.go")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print("Written successfully:", path)
