# __PS_ID__ Framework SQLite Instance 2 Configuration
# Settings UNIQUE to the '__PS_ID__-app-sqlite-2' compose service.

cors-origins:
  - "https://localhost:__SERVICE_APP_PORT_SQLITE_2__"
  - "https://127.0.0.1:__SERVICE_APP_PORT_SQLITE_2__"
  - "https://[::1]:__SERVICE_APP_PORT_SQLITE_2__"

otlp-service: __PS_ID__-sqlite-2
otlp-hostname: __PS_ID__-sqlite-2
