# __PS_ID__ Framework PostgreSQL Instance 2 Configuration
# Framework settings UNIQUE to the '__PS_ID__-app-postgresql-2' compose service.

cors-origins:
  - "https://localhost:__SERVICE_APP_PORT_PG_2__"
  - "https://127.0.0.1:__SERVICE_APP_PORT_PG_2__"
  - "https://[::1]:__SERVICE_APP_PORT_PG_2__"

otlp-service: __PS_ID__-postgresql-2
otlp-hostname: __PS_ID__-postgresql-2
