// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1-0.20250618140738-aae687ce8fe9 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for JWKGenerateRequestAlgorithm.
const (
	ECP256     JWKGenerateRequestAlgorithm = "ECP256"
	ECP384     JWKGenerateRequestAlgorithm = "ECP384"
	ECP521     JWKGenerateRequestAlgorithm = "ECP521"
	OKPEd25519 JWKGenerateRequestAlgorithm = "OKPEd25519"
	Oct128     JWKGenerateRequestAlgorithm = "Oct128"
	Oct192     JWKGenerateRequestAlgorithm = "Oct192"
	Oct256     JWKGenerateRequestAlgorithm = "Oct256"
	Oct384     JWKGenerateRequestAlgorithm = "Oct384"
	Oct512     JWKGenerateRequestAlgorithm = "Oct512"
	RSA2048    JWKGenerateRequestAlgorithm = "RSA2048"
	RSA3072    JWKGenerateRequestAlgorithm = "RSA3072"
	RSA4096    JWKGenerateRequestAlgorithm = "RSA4096"
)

// Defines values for JWKGenerateRequestUse.
const (
	Enc JWKGenerateRequestUse = "enc"
	Sig JWKGenerateRequestUse = "sig"
)

// Defines values for JWKResponseKty.
const (
	EC  JWKResponseKty = "EC"
	OKP JWKResponseKty = "OKP"
	Oct JWKResponseKty = "oct"
	RSA JWKResponseKty = "RSA"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message.
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
	Time   time.Time            `json:"time"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// JWEDecryptRequest defines model for JWEDecryptRequest.
type JWEDecryptRequest struct {
	// JWE Compact JWE to decrypt.
	JWE string `json:"jwe"`

	// Kid Key ID to use for decryption.
	Kid openapi_types.UUID `json:"kid"`
}

// JWEDecryptResponse defines model for JWEDecryptResponse.
type JWEDecryptResponse struct {
	// Error Error message (if decryption failed).
	Error *string `json:"error,omitempty"`

	// Kid Key ID used for decryption.
	Kid *openapi_types.UUID `json:"kid,omitempty"`

	// Plaintext Decrypted plaintext.
	Plaintext *string `json:"plaintext,omitempty"`
}

// JWEEncryptRequest defines model for JWEEncryptRequest.
type JWEEncryptRequest struct {
	// Kid Key ID to use for encryption.
	Kid openapi_types.UUID `json:"kid"`

	// Plaintext Plaintext to encrypt.
	Plaintext string `json:"plaintext"`
}

// JWEEncryptResponse defines model for JWEEncryptResponse.
type JWEEncryptResponse struct {
	// JWE Compact JWE serialization.
	JWE string `json:"jwe"`
}

// JWKGenerateRequest defines model for JWKGenerateRequest.
type JWKGenerateRequest struct {
	// Algorithm Algorithm for key generation.
	Algorithm JWKGenerateRequestAlgorithm `json:"algorithm"`

	// Use Intended use of the key (sig=signing, enc=encryption).
	Use *JWKGenerateRequestUse `json:"use,omitempty"`
}

// JWKGenerateRequestAlgorithm Algorithm for key generation.
type JWKGenerateRequestAlgorithm string

// JWKGenerateRequestUse Intended use of the key (sig=signing, enc=encryption).
type JWKGenerateRequestUse string

// JWKListResponse defines model for JWKListResponse.
type JWKListResponse struct {
	// Count Total number of keys.
	Count int           `json:"count"`
	Keys  []JWKResponse `json:"keys"`
}

// JWKResponse defines model for JWKResponse.
type JWKResponse struct {
	// Algorithm Algorithm used for the key.
	Algorithm string `json:"algorithm"`

	// CreatedAt Unix timestamp when the key was created.
	CreatedAt int64 `json:"created_at"`

	// Kid Key ID (UUIDv7).
	Kid openapi_types.UUID `json:"kid"`

	// Kty Key type.
	Kty JWKResponseKty `json:"kty"`

	// PublicJWK Public key in JWK format.
	PublicJWK *map[string]any `json:"public_jwk,omitempty"`

	// Use Intended use of the key.
	Use *string `json:"use,omitempty"`
}

// JWKResponseKty Key type.
type JWKResponseKty string

// JWKS JSON Web Key Set (RFC 7517).
type JWKS struct {
	Keys []map[string]any `json:"keys"`
}

// JWSSignRequest defines model for JWSSignRequest.
type JWSSignRequest struct {
	// Kid Key ID to use for signing.
	Kid openapi_types.UUID `json:"kid"`

	// Payload Payload to sign (string or base64url-encoded).
	Payload string `json:"payload"`
}

// JWSSignResponse defines model for JWSSignResponse.
type JWSSignResponse struct {
	// JWS Compact JWS serialization.
	JWS string `json:"jws"`
}

// JWSVerifyRequest defines model for JWSVerifyRequest.
type JWSVerifyRequest struct {
	// JWS Compact JWS to verify.
	JWS string `json:"jws"`

	// Kid Optional key ID to use for verification.
	Kid *openapi_types.UUID `json:"kid,omitempty"`
}

// JWSVerifyResponse defines model for JWSVerifyResponse.
type JWSVerifyResponse struct {
	// Error Error message (if invalid).
	Error *string `json:"error,omitempty"`

	// Kid Key ID used for verification.
	Kid *openapi_types.UUID `json:"kid,omitempty"`

	// Payload Decoded payload (if valid).
	Payload *string `json:"payload,omitempty"`

	// Valid Whether the signature is valid.
	Valid bool `json:"valid"`
}

// JWTCreateRequest defines model for JWTCreateRequest.
type JWTCreateRequest struct {
	// Claims JWT claims.
	Claims map[string]any `json:"claims"`

	// Kid Key ID to use for signing.
	Kid openapi_types.UUID `json:"kid"`
}

// JWTCreateResponse defines model for JWTCreateResponse.
type JWTCreateResponse struct {
	// JWT Compact JWT serialization.
	JWT string `json:"jwt"`
}

// JWTVerifyRequest defines model for JWTVerifyRequest.
type JWTVerifyRequest struct {
	// JWT Compact JWT to verify.
	JWT string `json:"jwt"`

	// Kid Optional key ID to use for verification.
	Kid *openapi_types.UUID `json:"kid,omitempty"`
}

// JWTVerifyResponse defines model for JWTVerifyResponse.
type JWTVerifyResponse struct {
	// Claims Decoded claims (if valid).
	Claims *map[string]any `json:"claims,omitempty"`

	// Error Error message (if invalid).
	Error *string `json:"error,omitempty"`

	// Kid Key ID used for verification.
	Kid *openapi_types.UUID `json:"kid,omitempty"`

	// Valid Whether the JWT signature is valid.
	Valid bool `json:"valid"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// DecryptJWEJSONRequestBody defines body for DecryptJWE for application/json ContentType.
type DecryptJWEJSONRequestBody = JWEDecryptRequest

// EncryptJWEJSONRequestBody defines body for EncryptJWE for application/json ContentType.
type EncryptJWEJSONRequestBody = JWEEncryptRequest

// GenerateJWKJSONRequestBody defines body for GenerateJWK for application/json ContentType.
type GenerateJWKJSONRequestBody = JWKGenerateRequest

// SignJWSJSONRequestBody defines body for SignJWS for application/json ContentType.
type SignJWSJSONRequestBody = JWSSignRequest

// VerifyJWSJSONRequestBody defines body for VerifyJWS for application/json ContentType.
type VerifyJWSJSONRequestBody = JWSVerifyRequest

// CreateJWTJSONRequestBody defines body for CreateJWT for application/json ContentType.
type CreateJWTJSONRequestBody = JWTCreateRequest

// VerifyJWTJSONRequestBody defines body for VerifyJWT for application/json ContentType.
type VerifyJWTJSONRequestBody = JWTVerifyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(c *fiber.Ctx) error
	// Decrypt a JWE
	// (POST /jwe/decrypt)
	DecryptJWE(c *fiber.Ctx) error
	// Encrypt a payload
	// (POST /jwe/encrypt)
	EncryptJWE(c *fiber.Ctx) error
	// List all JWKs
	// (GET /jwk)
	ListJWKS(c *fiber.Ctx) error
	// Generate a new JWK
	// (POST /jwk/generate)
	GenerateJWK(c *fiber.Ctx) error
	// Delete a JWK by Key ID
	// (DELETE /jwk/{kid})
	DeleteJWK(c *fiber.Ctx, kid openapi_types.UUID) error
	// Get a JWK by Key ID
	// (GET /jwk/{kid})
	GetJWK(c *fiber.Ctx, kid openapi_types.UUID) error
	// Get JWKS (public keys)
	// (GET /jwks)
	GetJWKS(c *fiber.Ctx) error
	// Sign a payload
	// (POST /jws/sign)
	SignJWS(c *fiber.Ctx) error
	// Verify a JWS
	// (POST /jws/verify)
	VerifyJWS(c *fiber.Ctx) error
	// Create a JWT
	// (POST /jwt/create)
	CreateJWT(c *fiber.Ctx) error
	// Verify a JWT
	// (POST /jwt/verify)
	VerifyJWT(c *fiber.Ctx) error
	// Liveness check
	// (GET /livez)
	GetLivez(c *fiber.Ctx) error
	// Readiness check
	// (GET /readyz)
	GetReadyz(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// DecryptJWE operation middleware
func (siw *ServerInterfaceWrapper) DecryptJWE(c *fiber.Ctx) error {

	return siw.Handler.DecryptJWE(c)
}

// EncryptJWE operation middleware
func (siw *ServerInterfaceWrapper) EncryptJWE(c *fiber.Ctx) error {

	return siw.Handler.EncryptJWE(c)
}

// ListJWKS operation middleware
func (siw *ServerInterfaceWrapper) ListJWKS(c *fiber.Ctx) error {

	return siw.Handler.ListJWKS(c)
}

// GenerateJWK operation middleware
func (siw *ServerInterfaceWrapper) GenerateJWK(c *fiber.Ctx) error {

	return siw.Handler.GenerateJWK(c)
}

// DeleteJWK operation middleware
func (siw *ServerInterfaceWrapper) DeleteJWK(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "kid" -------------
	var kid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "kid", c.Params("kid"), &kid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter kid: %w", err).Error())
	}

	return siw.Handler.DeleteJWK(c, kid)
}

// GetJWK operation middleware
func (siw *ServerInterfaceWrapper) GetJWK(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "kid" -------------
	var kid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "kid", c.Params("kid"), &kid, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter kid: %w", err).Error())
	}

	return siw.Handler.GetJWK(c, kid)
}

// GetJWKS operation middleware
func (siw *ServerInterfaceWrapper) GetJWKS(c *fiber.Ctx) error {

	return siw.Handler.GetJWKS(c)
}

// SignJWS operation middleware
func (siw *ServerInterfaceWrapper) SignJWS(c *fiber.Ctx) error {

	return siw.Handler.SignJWS(c)
}

// VerifyJWS operation middleware
func (siw *ServerInterfaceWrapper) VerifyJWS(c *fiber.Ctx) error {

	return siw.Handler.VerifyJWS(c)
}

// CreateJWT operation middleware
func (siw *ServerInterfaceWrapper) CreateJWT(c *fiber.Ctx) error {

	return siw.Handler.CreateJWT(c)
}

// VerifyJWT operation middleware
func (siw *ServerInterfaceWrapper) VerifyJWT(c *fiber.Ctx) error {

	return siw.Handler.VerifyJWT(c)
}

// GetLivez operation middleware
func (siw *ServerInterfaceWrapper) GetLivez(c *fiber.Ctx) error {

	return siw.Handler.GetLivez(c)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(c *fiber.Ctx) error {

	return siw.Handler.GetReadyz(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/health", wrapper.GetHealth)

	router.Post(options.BaseURL+"/jwe/decrypt", wrapper.DecryptJWE)

	router.Post(options.BaseURL+"/jwe/encrypt", wrapper.EncryptJWE)

	router.Get(options.BaseURL+"/jwk", wrapper.ListJWKS)

	router.Post(options.BaseURL+"/jwk/generate", wrapper.GenerateJWK)

	router.Delete(options.BaseURL+"/jwk/:kid", wrapper.DeleteJWK)

	router.Get(options.BaseURL+"/jwk/:kid", wrapper.GetJWK)

	router.Get(options.BaseURL+"/jwks", wrapper.GetJWKS)

	router.Post(options.BaseURL+"/jws/sign", wrapper.SignJWS)

	router.Post(options.BaseURL+"/jws/verify", wrapper.VerifyJWS)

	router.Post(options.BaseURL+"/jwt/create", wrapper.CreateJWT)

	router.Post(options.BaseURL+"/jwt/verify", wrapper.VerifyJWT)

	router.Get(options.BaseURL+"/livez", wrapper.GetLivez)

	router.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RbbW/jtrL+K7y890MCKLbsOG8G+iHNerd2Ni838jYHPQkKWhrbTCRKh6SSaBf57wck",
	"9WpLttNdZ9sCrWWLHA5nnnk4nEm/YTcMopABkwL3v2EOIgqZAP3lV+LdwH9iEFJ9c0MmgelHEkU+dYmk",
	"IWs/iJCp34Q7h4Cop//jMMV9/L/tQnTbvBXtAechv0kXwa+vrxb2QLicRkoY7qs1ETeLtvCrhYdMAmfE",
	"d4A/AdfT30+ZbHEk9OoI1ASt1mUoP4Yx895PlxsQYcxdQCyUaKrWbmE1KhWg5Fdl9L/hiIcRcEmNOyEz",
	"XlWwnoUCEILMoIUtDC8kiHzAfXwOSbEctrBMIvWzkJyymV5duYpy8HD/36n8+3xYOHkAVypr/QbEl/Nm",
	"zYQkMjY6sjhQsuZ6RoItHLPs+b6sWjFgQSkLSxroNYrBXbt7sNfp7tm9cafbt+2+bf+BLTwNeUAk7mOP",
	"SNjT09btMdU0XaRur6PbwQdweRLJUuxUt/vwDMtuOAuDiLgSjW4HSIbIMzKq/oBkNJ98cukVHf168fCl",
	"63Rc+vls5E+Ci/y3G/vycsjsVqvVqjPOI/WW11Z+Hn5Qy8YC0DTk2fI0ZFUN7M7J/tEROd7rTW1778i2",
	"7b1j9R+7+KdTtmwc0/XAUfYwmq0z6PdAG+3QaWlfaEqoD97um60UC/BqbLRmyxaOfEKZhBe5LDndH3go",
	"H1Q1uwMuB5ntpNagdXYbsNVA3BAMwLYJhpWWuc5eKX1SPd5smjLWHrUKxYr3ayzXhLi1MSyAU+LTr2TZ",
	"bt8dxjXxU7+P80/AgBMJjRAg/izkVM6D5d2cZq80CB4hQTMjLdtQytU3zmnPPjnElnrat4+65qlr946x",
	"hQdn1wfdjnnYP+6Zh+6BGn51fj3wugcHnRP1xZUHna55MOOuXJmOc2XnJH3V6R5XD4Jc2hKsYlHjInWk",
	"Mw88De5wiuQc9NZ2BJ39IuiMUTazFNJ+KVC/W96toDP9za2qYX5e7afC1g3e+kzFCsi5YcxqQmQcSuIj",
	"FgcT4GpHj5CICt4O8sUU5mfANcNBooVSCYFYl5yMbs+L1CSXRjgnyXKAKcFWqmzDPpv3uBEccwZOnVeN",
	"rmZAuByIBO9PUmPFL4y+IHWoC0mCCD3PgeXYeCYCpXMrS3WO9vf3O/uHtl0iOcrkYQ/XmnwF2+58+TL8",
	"8HS0ux2CfZRJ/cpq5EIo6wA1wYktHLpyMdxqGTye+NT98+H5sYbC9TttSMrQ6PYcGX1LvFaA4y0xW7XV",
	"JgFoyL/AmLFMBRgNiHWWtRo5V5foFiZIGdIBiXZuPp6ho4OO8eLCSbsYbguybs9RlNup1jLrg65edceh",
	"M/a9GUBKjFs6/knih6RGj2vzQimiFEA7Zg4KOZoQAYe9mPt7wNzQS/O4QrffwPdDC92G3Pf+Z9OkINVj",
	"pR2b8wGxKh9wNswHPn75Ouxc0qEYBjL642x4OHw4fbkaX+xfdge9z+Ob4OLDqbz8evp8cWb3Lj6cPn8e",
	"nz6rz/xfZ3TScj79LiafjsXwo/fkBi+Pw//fMI9oBNHvwOk0WXGjWbN7GaInLWLdzkcnb7q5XOkH4mt6",
	"qWJWr5dexlt/4U6y1hbffRmh7In49HuuIG/c44pY+wA6jFA6QOtXaLdxYFlYT1qWfzsHOQdzZKtgJjLm",
	"gKgwi1TWkDyGXPAkDH0gbMk/Zpl6D43PNJ83otX1CTUsTDyPGgBdl0YYBRYZeozMvIqu3zCJPdzHQbJH",
	"oki/iUxi0NMEaGGq/FHOFKgQuI8fQgF7JJZzdRSpM0jEE+U3AbzT3cd1F7qfz9W1tJlac40rmnlTrmKO",
	"8Zt5k90cuIo3H6N//X7WxCZLwd508I/XEt8a9Tcmvk1Vf38iXGubxgvLX4izjIfM3AUaWlLi70y1GxCh",
	"xvcWyVCNo2waZlVq4mq0MhKoUaNYSMrQGSdsGnIPL5ecB84YnV4P9f5HV84A7eik90qLR44hGkSYhwbF",
	"ZRkpB2szidYdu+bhE/VA9NGezv13ymnzLgoIIzMIgMl+Vl0ACwkZcrAQB8kpPIGFfCqkhTzwQerUXxhp",
	"TlWcysJ3ETAvCimTWusiqUYeVb6ZxLr4t6ezkmK2k3mhrH7fpJ1qfyaGs9PRLD8oza/ffz8rWWkZab2w",
	"KmRcEjIOH2FhvrmZlFWQapC4Y6e+j7S8cMZJNKduaZ4O/Y/Dawd1evbePiJRxMMn8FB+9VGuwRb2qQtp",
	"6KaguBiOsYVj7uM+nksZiX67HUbATPOhFfJZO50k2mqsrrdLzWkaIafZkYZMx0bhB1v4CbgwoOq07Jat",
	"pimpJKK4j/dbdmtfJ+Byrumibar76nEGNQR7AzLmTOgYMkORKcxnt8NaVVRc5TYaqlP7E0jTmsBWtfPV",
	"te0f1tlZaH7UtHZSS1GRbiZJOztxEBCe6KRL79Gdg/uoqIbMhAr7VPd7Nbj98AztFGGaiUPRXGhGZAV8",
	"Fda4NrA2ZVGR1oipGjCVN7odYMNIIOSvoZf8MOMtd1Neq+Sn+PF1i96r6T7UeFBZs9Ra4CBi3/Qve0aX",
	"uiVyndulRque0ls/JW9AVpFScXAJKupbgZOUlZpxcpbSzgqYTJK8L8BmBimG6ktNjDv2TOXc5PwRuHRK",
	"wdMFjhoopbK3CqWFfsj7Q2mxrVADpazokRoXPCRi1wUhprHvJ++EKQsfbLJGXXO+isdBdv5lp14DJh8b",
	"uf4zFRIR3zdJgYfKB75AGl8BSOIRSZYJXk3W1buturVat6+lh3OdwuQZzZJTK0bLtzy6PRcVg50XBmtn",
	"6VJzFGfNH0QQg+eK5VBNYObJQeuOOXEUhVxWUob+HdtDN85pH6UdHwulDR/90LV7x2rE4KyPTNPHQqbn",
	"oz+7B4fq7dX5dR8VjR/1k5MEgbKL20emCWQh0wPSn92DQ/3ZOTG/d7rHNeyRbVWZaFv0sdRM24g/Oj9S",
	"g3UgyzDxY0jjB3HAIgy1i+ox/e2Req8GyCrVr0tg9BWAVME8SRCVApkrW6smS1GTMmhUvNOrr8Wb5X8K",
	"9S4c59l2b8/VLs0Ol8xnNabJmm1Wmwtl2XRUbtSY661KZkLmJ7Wpc61B7feEeyOdvrujPoHcwEsR4SQA",
	"CVz9uroTmDbJdrG6weO+vhthK7ulmcpblXqskl3XlXju04ATa69YC9BxQCJdSaDm6u/7JdioS+V4TkVx",
	"BacCySSiLvH9pNS2VVfYSkFFWY2DnyiZEdHloVYty7/Hae40wM3Z8PhWWDDFiZJpdhs4T7QFnbGNMvGG",
	"esUkyUq+C1m4SbjekoMrqaNbZ2snaKUX+e7Zd7WDtyL1Vub8h+fdji5c1SbdTgl7pqbUjD5T4V2FPsI8",
	"BC+SE1ca+JkVW3dsOEUszMrRVBToszRt6CoeNTUGndojwgGp+PLqoGk02So4q6X+94fnQjm9loScKm3+",
	"vEJDGRkN8JJtU73ciNxq6qA5b+WUZpoC1h1LI3RzZjMrjW7HW4PPQtPx3eGz2Gmrhc84+zumfzS5lWFT",
	"wd64hL03UFsN9hZpLW39bovVtgjLn8xq401Ybfw3ZLV6ZPn0Cb6uTZqvzhE1jQiRl/aJmlp7j/qsZa71",
	"goQX2dal1ar9i6by1XlNqr+i25CqtFh8egIGQqzuNnAgXvLXDKGnIhki4roQyez/9hG1trkx6/wE42g1",
	"F42j1KFrrKMmaCl1l7zGHhl66uR9t/ZDKKD91MGv9/kCi4LKLaH8viWKG2Kqz6u18s8Wi/ZrqXtYCFEX",
	"lRUS8jSwYbKzanLRS2iYPVg1W9N0w8Qxfr1//W8AAAD//5VtRATZNgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
