# KMS Demo Compose Configuration
#
# Usage: docker compose -f deployments/sm-kms/compose.demo.yml up -d
#
# This configuration is for demonstration purposes only.
# It includes SQLite backend with demo data auto-seeding.
#
# Demo credentials (WARNING: Never use in production):
# - admin@demo.local / admin-demo-password
# - user@demo.local / user-demo-password
#
# Demo endpoints:
# - KMS API: https://localhost:8080/api/v1
# - Swagger UI: https://localhost:8080/ui/swagger
# - Admin API: https://localhost:9090
# - Grafana: http://localhost:3000 (admin/admin)

name: cryptoutil-kms-demo

include:
  - path: ../shared-telemetry/compose.yml

services:
  # KMS Demo Server (SQLite backend with demo seeding).
  cryptoutil-demo:
    build:
      context: ../..
      dockerfile: deployments/sm-kms/Dockerfile
      args:
        APP_VERSION: demo
        VCS_REF: demo
        BUILD_DATE: "2025-01-01T00:00:00Z"
    image: cryptoutil:demo
    container_name: cryptoutil-demo
    hostname: cryptoutil-demo
    secrets:
      - unseal_1of5.secret
      - unseal_2of5.secret
      - unseal_3of5.secret
      - unseal_4of5.secret
      - unseal_5of5.secret
    command:
      - server
      - start
      - --config=/etc/cryptoutil/common.yml
      - --config=/etc/cryptoutil/sqlite.yml
      - --demo
    ports:
      - "8080:8080"  # Public API (HTTPS)
      # Admin API (9090) NOT exposed - internal container use only (per 02-03.https-ports.instructions.md)
    volumes:
      - ./config/sm-kms-app-common.yml:/etc/cryptoutil/common.yml:ro
      - ./config/sm-kms-app-sqlite-1.yml:/etc/cryptoutil/sqlite.yml:ro
      - ./config/demo-seed.yml:/etc/cryptoutil/demo-seed.yml:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
      - OTEL_SERVICE_NAME=cryptoutil-demo
      - OTEL_RESOURCE_ATTRIBUTES=service.version=demo,deployment.environment=demo
    healthcheck:
      test:
        - CMD
        - wget
        - --no-check-certificate
        - -q
        - -O
        - /dev/null
        - https://127.0.0.1:9090/admin/api/v1/livez
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      opentelemetry-collector-contrib:
        condition: service_started
    networks:
      - cryptoutil-network
      - telemetry-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    profiles:
      - demo

secrets:
  unseal_1of5.secret:
    file: ./secrets/unseal_1of5.secret
  unseal_2of5.secret:
    file: ./secrets/unseal_2of5.secret
  unseal_3of5.secret:
    file: ./secrets/unseal_3of5.secret
  unseal_4of5.secret:
    file: ./secrets/unseal_4of5.secret
  unseal_5of5.secret:
    file: ./secrets/unseal_5of5.secret

networks:
  cryptoutil-network:
    driver: bridge
