# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# Doc: https://github.com/gitleaks/gitleaks

name: 'security-scan-gitleaks'
description: 'Scan files/directories for secrets using GitLeaks'

inputs:
  files:
    description: 'Comma-separated list of files or directories to scan (e.g., "coverage.out,coverage.html,./artifacts/")'
    required: true
  scan-name:
    description: 'Output security scan name in SARIF metadata (e.g. Security Scan of Coverage Artifacts)'
    required: true
  sarif-output-name:
    description: 'Output filename for GitLeaks SARIF results (e.g. gitleaks-files.sarif)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install GitLeaks
      shell: bash
      run: |
        echo "🔧 Installing GitLeaks..."
        START_TIME=$(date +%s)
        echo "📅 Start: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

        # Determine platform and architecture
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          PLATFORM="linux"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          PLATFORM="darwin"
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          PLATFORM="windows"
        else
          echo "❌ Unsupported platform: $RUNNER_OS"
          exit 1
        fi

        if [[ "$RUNNER_ARCH" == "X64" ]]; then
          ARCH="x64"
        elif [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          ARCH="arm64"
        else
          ARCH="x64"  # Default fallback
        fi

        # Get latest release info from GitHub API
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest)
        DOWNLOAD_URL=$(echo "$LATEST_RELEASE" | jq -r ".assets[] | select(.name | contains(\"$PLATFORM\") and contains(\"$ARCH\")) | .browser_download_url" | head -1)

        if [[ -z "$DOWNLOAD_URL" ]]; then
          echo "❌ Could not find GitLeaks download URL for $PLATFORM-$ARCH"
          exit 1
        fi

        echo "📦 Downloading GitLeaks from: $DOWNLOAD_URL"
        curl -L -o gitleaks.tar.gz "$DOWNLOAD_URL"

        # Extract and install
        tar -xzf gitleaks.tar.gz
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/ || mv gitleaks /usr/local/bin/

        # Verify installation
        gitleaks version

        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "📅 End: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        echo "⏱️ GitLeaks installed in: ${DURATION}s"

    - name: Parse file list
      shell: bash
      run: |
        echo "🔍 Parsing file list for security scanning..."
        # Convert comma-separated string to array
        IFS=',' read -ra FILE_ARRAY <<< "${{ inputs.files }}"

        # Validate files exist and create scan list
        SCAN_LIST=""
        for file in "${FILE_ARRAY[@]}"; do
          file=$(echo "$file" | xargs)  # Trim whitespace
          if [ -e "$file" ]; then
            echo "✅ Found: $file"
            SCAN_LIST="$SCAN_LIST $file"
          else
            echo "⚠️ Not found: $file"
          fi
        done

        if [ -z "$SCAN_LIST" ]; then
          echo "❌ No valid files found to scan"
          exit 1
        fi

        # Export for use in subsequent steps
        echo "SCAN_FILES=$SCAN_LIST" >> $GITHUB_ENV
        echo "📋 Files to scan: $SCAN_LIST"

    - name: Run GitLeaks secrets detection
      shell: bash
      run: |
        echo "🔐 Running GitLeaks secrets detection..."
        START_TIME=$(date +%s)
        echo "📅 Start: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

        # Run GitLeaks on specified files/directories
        # Use dir command to scan directories/files for secrets
        gitleaks dir --verbose --redact --report-format sarif --report-path ${{ inputs.sarif-output-name }} $SCAN_FILES

        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "📅 End: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        echo "⏱️ GitLeaks scan completed in: ${DURATION}s"

    - name: Upload GitLeaks results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.sarif-output-name }}
        category: "${{ inputs.scan-name }}-gitleaks"
      if: always() && hashFiles('${{ inputs.sarif-output-name }}') != ''

    - name: Security scan summary
      shell: bash
      run: |
        echo "## 🔒 ${{ inputs.scan-name }} Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Files Scanned" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "$SCAN_FILES" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ -f "${{ inputs.sarif-output-name }}" ]; then
          RESULT_COUNT=$(jq '.runs[0].results | length' ${{ inputs.sarif-output-name }} 2>/dev/null || echo "0")
          echo "### GitLeaks Results" >> $GITHUB_STEP_SUMMARY
          echo "- SARIF file: \`${{ inputs.sarif-output-name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Secrets found: $RESULT_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ✅ Uploaded to Security tab" >> $GITHUB_STEP_SUMMARY
        else
          echo "### GitLeaks Results" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ❌ No SARIF file generated" >> $GITHUB_STEP_SUMMARY
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Note**: Results are available in the [Security tab](https://github.com/${{ github.repository }}/security/code-scanning) for detailed analysis." >> $GITHUB_STEP_SUMMARY
