# $schema: https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#
# CA Server Docker Compose Configuration
#
# This compose file provides the CA (Certificate Authority) REST API server.
# It provides certificate issuance, revocation, CRL, and OCSP services.
#
# Usage:
#   docker compose -f compose.simple.yml up -d                # Start CA server
#   docker compose -f compose.simple.yml logs -f ca-server    # Follow logs
#   docker compose -f compose.simple.yml down -v              # Stop and clean up
#
# API Endpoints (HTTPS on port 8093):
#   /api/v1/ca/ca                          - List CAs
#   /api/v1/ca/ca/{caId}                   - Get CA details
#   /api/v1/ca/ca/{caId}/crl               - Download CRL
#   /api/v1/ca/enrollments                 - Submit enrollment request
#   /api/v1/ca/certificates/{serialNumber} - Get/revoke certificate
#   /api/v1/ca/profiles                    - List certificate profiles
#   /api/v1/ca/ocsp                        - OCSP responder
#   /api/v1/ca/est/*                       - EST protocol endpoints
#   /api/v1/ca/tsa/timestamp               - TSA timestamp endpoint
#
include:
  - path: ../telemetry/compose.yml

services:
  # Build CA server image from source.
  builder-ca:
    image: ca-server:dev
    build:
      context: ../..
      dockerfile: deployments/ca/Dockerfile.ca-server
      args:
        APP_VERSION: "dev"
        VCS_REF: "local"
        BUILD_DATE: "2025-12-01T00:00:00Z"
    entrypoint: ["sh", "-c"]
    command: ["echo 'Build completed successfully'"]

  # CA Server.
  ca-server:
    image: ca-server:dev
    container_name: ca-server
    hostname: ca-server
    command:
      - start
      - --config=/etc/ca/ca.yml
    ports:
      - "8093:8093"  # Public API (HTTPS)
      - "9093:9093"  # Admin API (HTTPS)
    volumes:
      - ./config/ca.yml:/etc/ca/ca.yml:ro
      - ca-data:/app/data
    depends_on:
      builder-ca:
        condition: service_completed_successfully
      opentelemetry-collector-contrib:
        condition: service_started
      healthcheck-opentelemetry-collector-contrib:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "/dev/null", "https://127.0.0.1:9093/livez"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ca-network
      - telemetry-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  ca-data:

networks:
  ca-network:
    driver: bridge
