# OpenTelemetry Collector Configuration
# This collector receives application telemetry from cryptoutil services and forwards it to Grafana-OTEL-LGTM.
# It also exposes its own internal metrics for monitoring and provides health check endpoints.
#
# Ports:
# - 4317: OTLP gRPC receiver (application telemetry ingress)
# - 4318: OTLP HTTP receiver (application telemetry ingress)
# - 8888: Internal metrics exposure (Prometheus scraping - configured by default, not in this file)
# - 8889: Health check extension (container health monitoring)
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 16384
    send_batch_max_size: 32768

exporters:
  otlphttp:
    endpoint: "http://grafana-otel-lgtm:4318"
  # debug:
  #   verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:8889  # Health check endpoint for container monitoring

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
