# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

# NOTE: This action works in tandem with workflow-end-summary.
# Changes to environment variables or naming conventions here must be reflected in workflow-end-summary.
# Both actions should be updated together to maintain consistency.

name: 'workflow-begin-summary'
description: 'Add a standardized beginning summary to GitHub Actions workflow runs'

inputs:
  job-name:
    description: 'Name of the job (e.g., "e2e", "coverage", "gitleaks")'
    required: true

runs:
  using: 'composite'
  steps:
    # Use GitHub Actions' environment variable persistence mechanism ($GITHUB_ENV) to pass variables to workflow-end-summary action
    - name: Set workflow begin environment variables
      shell: bash
      run: |
        echo "WORKFLOW_START_TIME=$(date +%s)" >> $GITHUB_ENV

        # Derive workflow file name from job name pattern
        WORKFLOW_FILE_NAME=".github/workflows/ci-${{ inputs.job-name }}.yml"

        echo "WORKFLOW_FILE_NAME=$WORKFLOW_FILE_NAME" >> $GITHUB_ENV

    - name: Print workflow begin summary
      shell: bash
      run: |
        echo "=========================================="
        echo "${{ github.workflow }} ($WORKFLOW_FILE_NAME)"
        echo "Job: ${{ inputs.job-name }}"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Start Time: $(date -u +'%Y-%m-%d %H:%M:%S UTC' -d "@$WORKFLOW_START_TIME")"
        echo "=========================================="
