# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: 'workflow-begin-summary'
description: 'Add a standardized beginning summary to GitHub Actions workflow runs'

inputs:
  job-name:
    description: 'Name of the job (e.g., "e2e", "coverage", "gitleaks")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set workflow start time
      shell: bash
      run: |
        # Use GitHub Actions' environment variable persistence mechanism ($GITHUB_ENV) to pass the start time from the begin-summary action to the end-summary action
        echo "WORKFLOW_START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Workflow begin summary
      shell: bash
      run: |
        # Derive workflow file from job name pattern
        WORKFLOW_FILE=".github/workflows/ci-${{ inputs.job-name }}.yml"

        echo "=========================================="
        echo "${{ github.workflow }} ($WORKFLOW_FILE)"
        echo "Job: ${{ inputs.job-name }}"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Start Time: $(date -u +'%Y-%m-%d %H:%M:%S UTC' -d "@$WORKFLOW_START_TIME")"
        echo "=========================================="
