# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: 'workflow-begin-summary'
description: 'Add a standardized beginning summary to GitHub Actions workflow runs'

inputs:
  job-name:
    description: 'Name of the job (e.g., "e2e", "coverage", "gitleaks")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Workflow begin summary
      shell: bash
      run: |
        # Derive workflow file from job name
        case "${{ inputs.job-name }}" in
          "e2e")
            WORKFLOW_FILE=".github/workflows/ci-e2e.yml"
            OPERATION_NAME="End-to-End Testing"
            EMOJI="🧪"
            ;;
          "coverage")
            WORKFLOW_FILE=".github/workflows/ci-coverage.yml"
            OPERATION_NAME="Coverage Collection"
            EMOJI="📊"
            ;;
          "gitleaks")
            WORKFLOW_FILE=".github/workflows/ci-gitleaks.yml"
            OPERATION_NAME="GitLeaks Secrets Scan"
            EMOJI="🔍"
            ;;
          *)
            echo "ERROR: Unknown job name '${{ inputs.job-name }}'. Supported job names: e2e, coverage, gitleaks"
            exit 1
            ;;
        esac

        echo "=========================================="
        echo "$EMOJI ${{ github.workflow }} ($WORKFLOW_FILE)"
        echo "Job: ${{ inputs.job-name }}"
        echo "Operation: $OPERATION_NAME"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Start Time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        echo "=========================================="
