# https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.1/schema.yaml
openapi: 3.0.3
info:
  title: API
  version: "0.0.1"
  description: >
    Crypto REST API
servers:
  - url: http://localhost:8080/

paths:
  /keypool:
    post:
      summary: Create a new Key Pool.
      description: Create a new Key Pool. Depending on the provider, a Key Pool may be contained to one Key or many Keys.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolCreate'
      responses:
        '200':
          description: Key Pool created successfully.
          content:
            application/json:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/KeyPool'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
    get:
      summary: List all Key Pools. Supports optional filtering, sorting, and paging.
      description: List all Key Pools. Supports optional filtering, sorting, and paging.
      parameters:
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterIds'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterNames'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterProviders'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterAlgorithms'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterVersioningAllowed'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterImportAllowed'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterExportAllowed'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterStatuses'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterSorts'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterPageNumber'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolFilterPageSize'
      responses:
        '200':
          description: A JSON array of 0, 1, or many Key Pools.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './openapi_spec_components.yaml#/components/schemas/KeyPool'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'

  /keypool/{keyPoolID}/key:
    parameters:
      - name: keyPoolID
        in: path
        required: true
        schema:
          $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
    post:
      summary: Generate a new Key in a Key Pool.
      description: Generate a new Key in a Key Pool.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi_spec_components.yaml#/components/schemas/KeyGenerate'
      responses:
        '200':
          description: Key generated successfully.
          content:
            application/json:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/Key'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
    get:
      summary: List all Keys in Key Pool. Supports optional filtering, sorting, and paging.
      description: List all Keys in Key Pool. Supports optional filtering, sorting, and paging.
      parameters:
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterKeyPoolId'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterId'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterMinimumGenerateDate'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterMaximumGenerateDate'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterSorts'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterPageNumber'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyFilterPageSize'
      responses:
        '200':
          description: A JSON array of 0, 1, or many Keys in a Key Pool.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './openapi_spec_components.yaml#/components/schemas/Key'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'

components:
