# https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.1/schema.yaml
openapi: 3.0.3
info:
  title: API
  version: "0.0.1"
  description: >
    Crypto REST API
servers:
  - url: http://localhost:8080/

paths:
  /keypool:
    post:
      summary: Create a new Key Pool.
      description: Create a new Key Pool. Depending on the provider, a Key Pool may be contained to one Key or many Keys.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolCreate'
      responses:
        '200':
          description: Key Pool created successfully.
          content:
            application/json:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/KeyPool'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
  /keypool/{keyPoolID}:
    parameters:
      - name: keyPoolID
        in: path
        required: true
        schema:
          $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
    get:
      summary: Get a Key Pool.
      description: Get a Key Pool.
      responses:
        '200':
          description: Key Pool retrieved successfully.
          content:
            application/json:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/KeyPool'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
  /keypools:
    get:
      summary: Find Key Pools. Supports optional filtering, sorting, and paging.
      description: Find Key Pools. Supports optional filtering, sorting, and paging.
      parameters:
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamIds'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamNames'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamProviders'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamAlgorithms'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamVersioningAllowed'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamImportAllowed'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamExportAllowed'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamStatuses'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamSorts'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamPageNumber'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyPoolQueryParamPageSize'
      responses:
        '200':
          description: A JSON array of 0, 1, or many Key Pools.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './openapi_spec_components.yaml#/components/schemas/KeyPool'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'

  /keypool/{keyPoolID}/key:
    parameters:
      - name: keyPoolID
        in: path
        required: true
        schema:
          $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
    post:
      summary: Generate a new Key in a Key Pool.
      description: Generate a new Key in a Key Pool.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi_spec_components.yaml#/components/schemas/KeyGenerate'
      responses:
        '200':
          description: Key generated successfully.
          content:
            application/json:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/Key'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
  /keypool/{keyPoolID}/key/{keyID}:
    parameters:
      - name: keyPoolID
        in: path
        required: true
        schema:
          $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
      - name: keyID
        in: path
        required: true
        schema:
          $ref: './openapi_spec_components.yaml#/components/schemas/KeyId'
    get:
      summary: Get Key in Key Pool.
      description: Get Key in Key Pool.
      responses:
        '200':
          description: A JSON array of 0, 1, or many Keys in a Key Pool.
          content:
            application/json:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/Key'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
  /keypool/{keyPoolID}/keys:
    parameters:
      - name: keyPoolID
        in: path
        required: true
        schema:
          $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
    get:
      summary: Find Keys in Key Pool. Supports optional filtering, sorting, and paging.
      description: Find Keys in Key Pool. Supports optional filtering, sorting, and paging.
      parameters:
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamIds'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamMinimumGenerateDate'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamMaximumGenerateDate'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamSorts'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamPageNumber'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamPageSize'
      responses:
        '200':
          description: A JSON array of 0, 1, or many Keys in a Key Pool.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './openapi_spec_components.yaml#/components/schemas/Key'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
  /keys:
    get:
      summary: Find Keys. Supports optional filtering, sorting, and paging.
      description: Find Keys. Supports optional filtering, sorting, and paging.
      parameters:
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamKeyPoolIds'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamIds'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamMinimumGenerateDate'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamMaximumGenerateDate'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamSorts'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamPageNumber'
        - $ref: './openapi_spec_components.yaml#/components/parameters/KeyQueryParamPageSize'
      responses:
        '200':
          description: A JSON array of 0, 1, or many Keys in a Key Pool.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './openapi_spec_components.yaml#/components/schemas/Key'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'
  /keypool/{keyPoolID}/encrypt:
    post:
      summary: Encrypt binary data using a specific key.
      description: Encrypts raw binary data using the selected algorithm.
      parameters:
        - name: keyPoolID
          in: path
          required: true
          schema:
            $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
        - name: iv
          in: query
          required: false
          schema:
            $ref: './openapi_spec_components.yaml#/components/schemas/SymmetricCipherInitializationVector'
        - name: aad
          in: query
          required: false
          schema:
            $ref: './openapi_spec_components.yaml#/components/schemas/SymmetricCipherAdditionalAuthenticatedData'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              $ref: './openapi_spec_components.yaml#/components/schemas/SymmetricEncryptRequest'
      responses:
        '200':
          description: Raw JWE ciphertext.
          content:
            text/plain:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/SymmetricEncryptResponse'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'

  /keypool/{keyPoolID}/decrypt:
    post:
      summary: Decrypt raw JWE ciphertext using a specific key.
      description: Accepts a raw JWE (binary) ciphertext and returns raw decrypted plaintext.
      parameters:
        - name: keyPoolID
          in: path
          required: true
          schema:
            $ref: './openapi_spec_components.yaml#/components/schemas/KeyPoolId'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              $ref: './openapi_spec_components.yaml#/components/schemas/SymmetricDecryptRequest'
      responses:
        '200':
          description: Raw decrypted plaintext.
          content:
            text/plain:
              schema:
                $ref: './openapi_spec_components.yaml#/components/schemas/SymmetricDecryptResponse'
        '400':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP400BadRequest'
        '401':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP401Unauthorized'
        '403':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP403Forbidden'
        '404':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP404NotFound'
        '429':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP429TooManyRequests'
        '500':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP500InternalServerError'
        '502':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP502BadGateway'
        '503':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP503ServiceUnavailable'
        '504':
          $ref: './openapi_spec_components.yaml#/components/responses/HTTP504GatewayTimeout'

components:
