# identity-rp-app-postgresql-1.yml
# Instance-specific settings for identity-rp-app-postgresql-1 in compose.yml

cors-origins:
  - "https://localhost:8702"
  - "https://127.0.0.1:8702"
  - "https://[::1]:8702"

otlp-service: identity-rp-postgresql-1
otlp-hostname: identity-rp-postgresql-1
