# identity-rp-app-postgresql-2.yml
# Instance-specific settings for identity-rp-app-postgresql-2 in compose.yml

cors-origins:
  - "https://localhost:8703"
  - "https://127.0.0.1:8703"
  - "https://[::1]:8703"

otlp-service: identity-rp-postgresql-2
otlp-hostname: identity-rp-postgresql-2
