# identity-rp Framework PostgreSQL Instance 2 Configuration
# Framework settings UNIQUE to the 'identity-rp-app-postgresql-2' compose service.

cors-origins:
  - "https://localhost:8703"
  - "https://127.0.0.1:8703"
  - "https://[::1]:8703"

otlp-service: identity-rp-postgresql-2
otlp-hostname: identity-rp-postgresql-2
