# identity-rp-app-common.yml
# Common settings shared by ALL identity-rp instances in compose.yml

bind-public-address: "0.0.0.0"

tls-cert-file: /run/secrets/tls-cert.pem
tls-key-file: /run/secrets/tls-key.pem

unseal-mode: "3-of-5"

unseal-files:
  - /run/secrets/unseal-1of5.secret
  - /run/secrets/unseal-2of5.secret
  - /run/secrets/unseal-3of5.secret
  - /run/secrets/unseal-4of5.secret
  - /run/secrets/unseal-5of5.secret

browser-username-file: /run/secrets/browser-username.secret
browser-password-file: /run/secrets/browser-password.secret
service-username-file: /run/secrets/service-username.secret
service-password-file: /run/secrets/service-password.secret

allowed-ips:
  - "127.0.0.1"
  - "::1"
  - "::ffff:127.0.0.1"
allowed-cidrs:
  - "0.0.0.0/0"
  - "::/0"

csrf-token-single-use-token: false
