# Configuration for running cryptoutil on the host machine, connecting to PostgreSQL in Docker
#
# This configuration is specifically for local development and debugging from the host machine.
# It connects to the PostgreSQL container using localhost:5432 and explicitly disables container mode.
#
# Usage:
#   go run main.go --config=./config/postgresql-local-debug.yaml
#   or
#   Use the "cryptoutil postgres-local" launch configuration in VS Code

# Logging level (ALL, TRACE, DEBUG, CONFIG, INFO, NOTICE, WARN, ERROR, FATAL, OFF)
log-level: "ALL"

# Database connection to the PostgreSQL container from host machine
database-url: "host=localhost port=5432 user=USR password=PWD dbname=DB sslmode=disable"

# Explicitly disable container mode
database-container: "disabled"

# Run database auto-migrations
migrations: true

# Binding address - 0.0.0.0 allows connections from any IP
bind-address: "0.0.0.0"
