# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

# NOTE: This action works in tandem with workflow-job-end.
# Changes to environment variables or naming conventions here must be reflected in workflow-job-end.
# Both actions should be updated together to maintain consistency.

name: 'workflow-job-begin'
description: 'Add a standardized beginning summary to GitHub Actions workflow runs'

inputs:
  workflow-name:
    description: 'Name of the workflow (e.g., "CI - Quality Testing")'
    required: true
  job-name:
    description: 'Name of the job (e.g., "code-quality", "build")'
    required: true

runs:
  using: 'composite'
  steps:
    # Use GitHub Actions' environment variable persistence mechanism ($GITHUB_ENV) to pass variables to workflow-job-end action
    - name: Set workflow job begin environment variables
      shell: bash
      run: |
        echo "WORKFLOW_JOB_START_TIME=$(date +%s)" >> $GITHUB_ENV

        # Derive workflow file name from workflow name
        # Input: "CI - Quality Testing" -> Output: "ci-quality.yml"
        WORKFLOW_JOB_FILE_NAME=".github/workflows/ci-$(echo "$INPUT_WORKFLOW_NAME" | sed 's/^CI - //' | cut -d' ' -f1 | tr '[:upper:]' '[:lower:]').yml"

        echo "WORKFLOW_JOB_FILE_NAME=$WORKFLOW_JOB_FILE_NAME" >> $GITHUB_ENV

    - name: Print workflow job begin summary
      shell: bash
      run: |
        echo "=========================================="
        echo "${{ inputs.workflow-name }} ($WORKFLOW_JOB_FILE_NAME)"
        echo "Job: ${{ inputs.job-name }}"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Start Time: $(date -u +'%Y-%m-%d %H:%M:%S UTC' -d "@$WORKFLOW_JOB_START_TIME")"
        echo "=========================================="
