# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# Doc: https://docs.github.com/en/actions/reference/workflows-and-actions/variables

# NOTE: This action works in tandem with workflow-job-end.

name: 'workflow-job-begin'
description: 'Add a standardized beginning summary to GitHub Actions workflow runs'

# No inputs required - uses built-in GITHUB_WORKFLOW and GITHUB_JOB environment variables

runs:
  using: 'composite'
  steps:
    - name: Print all ENV names (no values)
      shell: bash
      run: |
        printenv | cut -d '=' -f1 | sort

    # Use GitHub Actions' environment variable persistence mechanism ($GITHUB_ENV) to pass variables to workflow-job-end action
    - name: Set workflow job begin environment variables
      shell: bash
      run: |
        echo "WORKFLOW_JOB_START_TIME=$(date +%s)" >> $GITHUB_ENV

        # Derive workflow file name from workflow name
        # Input: "CI - Quality Testing" -> Output: "ci-quality.yml"
        WORKFLOW_JOB_FILE_NAME=".github/workflows/ci-$(echo "$GITHUB_WORKFLOW" | sed 's/^CI - //' | cut -d' ' -f1 | tr '[:upper:]' '[:lower:]').yml"

        echo "WORKFLOW_JOB_FILE_NAME=$WORKFLOW_JOB_FILE_NAME" >> $GITHUB_ENV

    - name: Print workflow job begin summary
      shell: bash
      run: |
        echo "=========================================="
        echo "$GITHUB_WORKFLOW ($WORKFLOW_JOB_FILE_NAME)"
        echo "Job: $GITHUB_JOB"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Start Time: $(date -u +'%Y-%m-%d %H:%M:%S UTC' -d "@$WORKFLOW_JOB_START_TIME")"
        echo "=========================================="
