# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
# Doc: https://docs.github.com/en/actions/reference/workflows-and-actions/variables

# NOTE: This action works in tandem with workflow-job-end.

name: 'workflow-job-begin'
description: 'Add a standardized beginning summary to GitHub Actions workflow runs'

# No inputs required - uses built-in GITHUB_WORKFLOW and GITHUB_JOB environment variables

outputs:
  go-version:
    description: "Go version to use"
    value: ${{ steps.set-outputs.outputs.go-version }}
  java-version:
    description: "Java version to use"
    value: ${{ steps.set-outputs.outputs.java-version }}

runs:
  using: 'composite'
  steps:
    - name: Set workflow job begin environment variables
      shell: bash
      run: |
        echo "WORKFLOW_JOB_START_TIME=$(date +%s)" >> $GITHUB_ENV

    - name: Set global outputs
      id: set-outputs
      shell: bash
      run: |
        echo "go-version=1.25.7" >> $GITHUB_OUTPUT
        echo "java-version=21" >> $GITHUB_OUTPUT

    - name: Print workflow job begin summary
      shell: bash
      run: |
        echo "=========================================="
        echo "Workflow: $GITHUB_WORKFLOW"
        echo "Workflow Ref: $GITHUB_WORKFLOW_REF"
        echo "Job: $GITHUB_JOB"
        echo "Run URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo "Actor: $GITHUB_ACTOR"
        echo "Branch/Tag: $GITHUB_REF"
        echo "Commit: $GITHUB_SHA"
        echo "Run ID: $GITHUB_RUN_ID"
        echo "Runner: $RUNNER_OS ($RUNNER_ENVIRONMENT)"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Start Time: $(date -u +'%Y-%m-%d %H:%M:%S UTC' -d "@$WORKFLOW_JOB_START_TIME")"
        echo "=========================================="

    - name: Print all ENV names (no values)
      shell: bash
      run: |
        printenv | cut -d '=' -f1 | sort
