# pki-ca PostgreSQL Instance 1 Configuration
# Settings UNIQUE to the 'pki-ca-app-postgresql-1' compose service.

cors-origins:
  - "https://localhost:8302"
  - "https://127.0.0.1:8302"
  - "https://[::1]:8302"

otlp-service: pki-ca-postgresql-1
otlp-hostname: pki-ca-postgresql-1
