// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1-0.20250618140738-aae687ce8fe9 DO NOT EDIT.
package model

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ElasticKeyAlgorithm.
const (
	A128CBCHS256A128GCMKW    ElasticKeyAlgorithm = "A128CBC-HS256/A128GCMKW"
	A128CBCHS256A128KW       ElasticKeyAlgorithm = "A128CBC-HS256/A128KW"
	A128CBCHS256A192GCMKW    ElasticKeyAlgorithm = "A128CBC-HS256/A192GCMKW"
	A128CBCHS256A192KW       ElasticKeyAlgorithm = "A128CBC-HS256/A192KW"
	A128CBCHS256A256GCMKW    ElasticKeyAlgorithm = "A128CBC-HS256/A256GCMKW"
	A128CBCHS256A256KW       ElasticKeyAlgorithm = "A128CBC-HS256/A256KW"
	A128CBCHS256Dir          ElasticKeyAlgorithm = "A128CBC-HS256/dir"
	A128CBCHS256ECDHES       ElasticKeyAlgorithm = "A128CBC-HS256/ECDH-ES"
	A128CBCHS256ECDHESA128KW ElasticKeyAlgorithm = "A128CBC-HS256/ECDH-ES+A128KW"
	A128CBCHS256ECDHESA192KW ElasticKeyAlgorithm = "A128CBC-HS256/ECDH-ES+A192KW"
	A128CBCHS256ECDHESA256KW ElasticKeyAlgorithm = "A128CBC-HS256/ECDH-ES+A256KW"
	A128CBCHS256RSA15        ElasticKeyAlgorithm = "A128CBC-HS256/RSA1_5"
	A128CBCHS256RSAOAEP      ElasticKeyAlgorithm = "A128CBC-HS256/RSA-OAEP"
	A128CBCHS256RSAOAEP256   ElasticKeyAlgorithm = "A128CBC-HS256/RSA-OAEP-256"
	A128CBCHS256RSAOAEP384   ElasticKeyAlgorithm = "A128CBC-HS256/RSA-OAEP-384"
	A128CBCHS256RSAOAEP512   ElasticKeyAlgorithm = "A128CBC-HS256/RSA-OAEP-512"
	A128GCMA128GCMKW         ElasticKeyAlgorithm = "A128GCM/A128GCMKW"
	A128GCMA128KW            ElasticKeyAlgorithm = "A128GCM/A128KW"
	A128GCMA192GCMKW         ElasticKeyAlgorithm = "A128GCM/A192GCMKW"
	A128GCMA192KW            ElasticKeyAlgorithm = "A128GCM/A192KW"
	A128GCMA256GCMKW         ElasticKeyAlgorithm = "A128GCM/A256GCMKW"
	A128GCMA256KW            ElasticKeyAlgorithm = "A128GCM/A256KW"
	A128GCMDir               ElasticKeyAlgorithm = "A128GCM/dir"
	A128GCMECDHES            ElasticKeyAlgorithm = "A128GCM/ECDH-ES"
	A128GCMECDHESA128KW      ElasticKeyAlgorithm = "A128GCM/ECDH-ES+A128KW"
	A128GCMECDHESA192KW      ElasticKeyAlgorithm = "A128GCM/ECDH-ES+A192KW"
	A128GCMECDHESA256KW      ElasticKeyAlgorithm = "A128GCM/ECDH-ES+A256KW"
	A128GCMRSA15             ElasticKeyAlgorithm = "A128GCM/RSA1_5"
	A128GCMRSAOAEP           ElasticKeyAlgorithm = "A128GCM/RSA-OAEP"
	A128GCMRSAOAEP256        ElasticKeyAlgorithm = "A128GCM/RSA-OAEP-256"
	A128GCMRSAOAEP384        ElasticKeyAlgorithm = "A128GCM/RSA-OAEP-384"
	A128GCMRSAOAEP512        ElasticKeyAlgorithm = "A128GCM/RSA-OAEP-512"
	A192CBCHS384A128GCMKW    ElasticKeyAlgorithm = "A192CBC-HS384/A128GCMKW"
	A192CBCHS384A128KW       ElasticKeyAlgorithm = "A192CBC-HS384/A128KW"
	A192CBCHS384A192GCMKW    ElasticKeyAlgorithm = "A192CBC-HS384/A192GCMKW"
	A192CBCHS384A192KW       ElasticKeyAlgorithm = "A192CBC-HS384/A192KW"
	A192CBCHS384A256GCMKW    ElasticKeyAlgorithm = "A192CBC-HS384/A256GCMKW"
	A192CBCHS384A256KW       ElasticKeyAlgorithm = "A192CBC-HS384/A256KW"
	A192CBCHS384Dir          ElasticKeyAlgorithm = "A192CBC-HS384/dir"
	A192CBCHS384ECDHES       ElasticKeyAlgorithm = "A192CBC-HS384/ECDH-ES"
	A192CBCHS384ECDHESA128KW ElasticKeyAlgorithm = "A192CBC-HS384/ECDH-ES+A128KW"
	A192CBCHS384ECDHESA192KW ElasticKeyAlgorithm = "A192CBC-HS384/ECDH-ES+A192KW"
	A192CBCHS384ECDHESA256KW ElasticKeyAlgorithm = "A192CBC-HS384/ECDH-ES+A256KW"
	A192CBCHS384RSA15        ElasticKeyAlgorithm = "A192CBC-HS384/RSA1_5"
	A192CBCHS384RSAOAEP      ElasticKeyAlgorithm = "A192CBC-HS384/RSA-OAEP"
	A192CBCHS384RSAOAEP256   ElasticKeyAlgorithm = "A192CBC-HS384/RSA-OAEP-256"
	A192CBCHS384RSAOAEP384   ElasticKeyAlgorithm = "A192CBC-HS384/RSA-OAEP-384"
	A192CBCHS384RSAOAEP512   ElasticKeyAlgorithm = "A192CBC-HS384/RSA-OAEP-512"
	A192GCMA128GCMKW         ElasticKeyAlgorithm = "A192GCM/A128GCMKW"
	A192GCMA128KW            ElasticKeyAlgorithm = "A192GCM/A128KW"
	A192GCMA192GCMKW         ElasticKeyAlgorithm = "A192GCM/A192GCMKW"
	A192GCMA192KW            ElasticKeyAlgorithm = "A192GCM/A192KW"
	A192GCMA256GCMKW         ElasticKeyAlgorithm = "A192GCM/A256GCMKW"
	A192GCMA256KW            ElasticKeyAlgorithm = "A192GCM/A256KW"
	A192GCMDir               ElasticKeyAlgorithm = "A192GCM/dir"
	A192GCMECDHES            ElasticKeyAlgorithm = "A192GCM/ECDH-ES"
	A192GCMECDHESA128KW      ElasticKeyAlgorithm = "A192GCM/ECDH-ES+A128KW"
	A192GCMECDHESA192KW      ElasticKeyAlgorithm = "A192GCM/ECDH-ES+A192KW"
	A192GCMECDHESA256KW      ElasticKeyAlgorithm = "A192GCM/ECDH-ES+A256KW"
	A192GCMRSA15             ElasticKeyAlgorithm = "A192GCM/RSA1_5"
	A192GCMRSAOAEP           ElasticKeyAlgorithm = "A192GCM/RSA-OAEP"
	A192GCMRSAOAEP256        ElasticKeyAlgorithm = "A192GCM/RSA-OAEP-256"
	A192GCMRSAOAEP384        ElasticKeyAlgorithm = "A192GCM/RSA-OAEP-384"
	A192GCMRSAOAEP512        ElasticKeyAlgorithm = "A192GCM/RSA-OAEP-512"
	A256CBCHS512A128GCMKW    ElasticKeyAlgorithm = "A256CBC-HS512/A128GCMKW"
	A256CBCHS512A128KW       ElasticKeyAlgorithm = "A256CBC-HS512/A128KW"
	A256CBCHS512A192GCMKW    ElasticKeyAlgorithm = "A256CBC-HS512/A192GCMKW"
	A256CBCHS512A192KW       ElasticKeyAlgorithm = "A256CBC-HS512/A192KW"
	A256CBCHS512A256GCMKW    ElasticKeyAlgorithm = "A256CBC-HS512/A256GCMKW"
	A256CBCHS512A256KW       ElasticKeyAlgorithm = "A256CBC-HS512/A256KW"
	A256CBCHS512Dir          ElasticKeyAlgorithm = "A256CBC-HS512/dir"
	A256CBCHS512ECDHES       ElasticKeyAlgorithm = "A256CBC-HS512/ECDH-ES"
	A256CBCHS512ECDHESA128KW ElasticKeyAlgorithm = "A256CBC-HS512/ECDH-ES+A128KW"
	A256CBCHS512ECDHESA192KW ElasticKeyAlgorithm = "A256CBC-HS512/ECDH-ES+A192KW"
	A256CBCHS512ECDHESA256KW ElasticKeyAlgorithm = "A256CBC-HS512/ECDH-ES+A256KW"
	A256CBCHS512RSA15        ElasticKeyAlgorithm = "A256CBC-HS512/RSA1_5"
	A256CBCHS512RSAOAEP      ElasticKeyAlgorithm = "A256CBC-HS512/RSA-OAEP"
	A256CBCHS512RSAOAEP256   ElasticKeyAlgorithm = "A256CBC-HS512/RSA-OAEP-256"
	A256CBCHS512RSAOAEP384   ElasticKeyAlgorithm = "A256CBC-HS512/RSA-OAEP-384"
	A256CBCHS512RSAOAEP512   ElasticKeyAlgorithm = "A256CBC-HS512/RSA-OAEP-512"
	A256GCMA128GCMKW         ElasticKeyAlgorithm = "A256GCM/A128GCMKW"
	A256GCMA128KW            ElasticKeyAlgorithm = "A256GCM/A128KW"
	A256GCMA192GCMKW         ElasticKeyAlgorithm = "A256GCM/A192GCMKW"
	A256GCMA192KW            ElasticKeyAlgorithm = "A256GCM/A192KW"
	A256GCMA256GCMKW         ElasticKeyAlgorithm = "A256GCM/A256GCMKW"
	A256GCMA256KW            ElasticKeyAlgorithm = "A256GCM/A256KW"
	A256GCMDir               ElasticKeyAlgorithm = "A256GCM/dir"
	A256GCMECDHES            ElasticKeyAlgorithm = "A256GCM/ECDH-ES"
	A256GCMECDHESA128KW      ElasticKeyAlgorithm = "A256GCM/ECDH-ES+A128KW"
	A256GCMECDHESA192KW      ElasticKeyAlgorithm = "A256GCM/ECDH-ES+A192KW"
	A256GCMECDHESA256KW      ElasticKeyAlgorithm = "A256GCM/ECDH-ES+A256KW"
	A256GCMRSA15             ElasticKeyAlgorithm = "A256GCM/RSA1_5"
	A256GCMRSAOAEP           ElasticKeyAlgorithm = "A256GCM/RSA-OAEP"
	A256GCMRSAOAEP256        ElasticKeyAlgorithm = "A256GCM/RSA-OAEP-256"
	A256GCMRSAOAEP384        ElasticKeyAlgorithm = "A256GCM/RSA-OAEP-384"
	A256GCMRSAOAEP512        ElasticKeyAlgorithm = "A256GCM/RSA-OAEP-512"
	ES256                    ElasticKeyAlgorithm = "ES256"
	ES384                    ElasticKeyAlgorithm = "ES384"
	ES512                    ElasticKeyAlgorithm = "ES512"
	EdDSA                    ElasticKeyAlgorithm = "EdDSA"
	HS256                    ElasticKeyAlgorithm = "HS256"
	HS384                    ElasticKeyAlgorithm = "HS384"
	HS512                    ElasticKeyAlgorithm = "HS512"
	PS256                    ElasticKeyAlgorithm = "PS256"
	PS384                    ElasticKeyAlgorithm = "PS384"
	PS512                    ElasticKeyAlgorithm = "PS512"
	RS256                    ElasticKeyAlgorithm = "RS256"
	RS384                    ElasticKeyAlgorithm = "RS384"
	RS512                    ElasticKeyAlgorithm = "RS512"
)

// Defines values for ElasticKeyProvider.
const (
	Internal ElasticKeyProvider = "Internal"
)

// Defines values for ElasticKeySort.
const (
	ElasticKeySortAlgorithmASC          ElasticKeySort = "algorithm:ASC"
	ElasticKeySortAlgorithmDESC         ElasticKeySort = "algorithm:DESC"
	ElasticKeySortElasticKeyIDASC       ElasticKeySort = "elastic_key_id:ASC"
	ElasticKeySortElasticKeyIDDESC      ElasticKeySort = "elastic_key_id:DESC"
	ElasticKeySortExportAllowedASC      ElasticKeySort = "export_allowed:ASC"
	ElasticKeySortExportAllowedDESC     ElasticKeySort = "export_allowed:DESC"
	ElasticKeySortImportAllowedASC      ElasticKeySort = "import_allowed:ASC"
	ElasticKeySortImportAllowedDESC     ElasticKeySort = "import_allowed:DESC"
	ElasticKeySortNameASC               ElasticKeySort = "name:ASC"
	ElasticKeySortNameDESC              ElasticKeySort = "name:DESC"
	ElasticKeySortProviderASC           ElasticKeySort = "provider:ASC"
	ElasticKeySortProviderDESC          ElasticKeySort = "provider:DESC"
	ElasticKeySortStatusASC             ElasticKeySort = "status:ASC"
	ElasticKeySortStatusDESC            ElasticKeySort = "status:DESC"
	ElasticKeySortVersioningAllowedASC  ElasticKeySort = "versioning_allowed:ASC"
	ElasticKeySortVersioningAllowedDESC ElasticKeySort = "versioning_allowed:DESC"
)

// Defines values for ElasticKeyStatus.
const (
	Active                         ElasticKeyStatus = "active"
	Creating                       ElasticKeyStatus = "creating"
	Disabled                       ElasticKeyStatus = "disabled"
	FinishedDelete                 ElasticKeyStatus = "finished_delete"
	GenerateFailed                 ElasticKeyStatus = "generate_failed"
	ImportFailed                   ElasticKeyStatus = "import_failed"
	PendingDeleteWasActive         ElasticKeyStatus = "pending_delete_was_active"
	PendingDeleteWasDisabled       ElasticKeyStatus = "pending_delete_was_disabled"
	PendingDeleteWasGenerateFailed ElasticKeyStatus = "pending_delete_was_generate_failed"
	PendingDeleteWasImportFailed   ElasticKeyStatus = "pending_delete_was_import_failed"
	PendingDeleteWasPendingImport  ElasticKeyStatus = "pending_delete_was_pending_import"
	PendingGenerate                ElasticKeyStatus = "pending_generate"
	PendingImport                  ElasticKeyStatus = "pending_import"
	StartedDelete                  ElasticKeyStatus = "started_delete"
)

// Defines values for GenerateAlgorithm.
const (
	ECP256     GenerateAlgorithm = "EC/P256"
	ECP384     GenerateAlgorithm = "EC/P384"
	ECP521     GenerateAlgorithm = "EC/P521"
	OKPEd25519 GenerateAlgorithm = "OKP/Ed25519"
	Oct128     GenerateAlgorithm = "oct/128"
	Oct192     GenerateAlgorithm = "oct/192"
	Oct256     GenerateAlgorithm = "oct/256"
	Oct384     GenerateAlgorithm = "oct/384"
	Oct512     GenerateAlgorithm = "oct/512"
	RSA2048    GenerateAlgorithm = "RSA/2048"
	RSA3072    GenerateAlgorithm = "RSA/3072"
	RSA4096    GenerateAlgorithm = "RSA/4096"
)

// Defines values for MaterialKeySort.
const (
	MaterialKeySortElasticKeyID       MaterialKeySort = "elastic_key_id"
	MaterialKeySortElasticKeyIDASC    MaterialKeySort = "elastic_key_id:ASC"
	MaterialKeySortElasticKeyIDDESC   MaterialKeySort = "elastic_key_id:DESC"
	MaterialKeySortExpirationDate     MaterialKeySort = "expiration_date"
	MaterialKeySortExpirationDateASC  MaterialKeySort = "expiration_date:ASC"
	MaterialKeySortExpirationDateDESC MaterialKeySort = "expiration_date:DESC"
	MaterialKeySortGenerateDate       MaterialKeySort = "generate_date"
	MaterialKeySortGenerateDateASC    MaterialKeySort = "generate_date:ASC"
	MaterialKeySortGenerateDateDESC   MaterialKeySort = "generate_date:DESC"
	MaterialKeySortImportDate         MaterialKeySort = "import_date"
	MaterialKeySortImportDateASC      MaterialKeySort = "import_date:ASC"
	MaterialKeySortImportDateDESC     MaterialKeySort = "import_date:DESC"
	MaterialKeySortMaterialKeyID      MaterialKeySort = "material_key_id"
	MaterialKeySortMaterialKeyIDASC   MaterialKeySort = "material_key_id:ASC"
	MaterialKeySortMaterialKeyIDDESC  MaterialKeySort = "material_key_id:DESC"
	MaterialKeySortRevocationDate     MaterialKeySort = "revocation_date"
	MaterialKeySortRevocationDateASC  MaterialKeySort = "revocation_date:ASC"
	MaterialKeySortRevocationDateDESC MaterialKeySort = "revocation_date:DESC"
)

// DecryptRequest JSON Web Encryption (JWE) message in compact serialized format. See RFC 7516 JSON Web Encryption (JWE) for more details. Compact serialized format is 'Header.EncryptedKey.IV.Ciphertext.AuthenticationTag'. Each section is Base64Url-encoded; Some parts can be empty depending on 'alg' and 'enc' headers. - Header: Required base64Url-encoded JSON key/values for the JWE message. - EncryptedKey: Optional base64Url-encoded of an encrypted symmetric key used to encrypt the payload. Mon-empty for envelope encryption (e.g. alg=a256gcmkw), or empty for direct encryption (e.g. alg=dir). - IV: Required base64Url-encoded Initialization Vector (IV) used to encrypt the payload. For AES-GCM or AES-GCM-SIV it contains a 12-bytes nonce. For AES-CBC it contains a 16-bytes IV. - Ciphertext: Required base64Url-encoded encrypted bytes. - AuthenticationTag: Required base64Url-encoded authentication tag. For AES-GCM or AES-GCM-SIV it's a 16-bytes authentication tag. For AES-CBC-HMAC it contains an AEAD HMAC hash.
type DecryptRequest = string

// DecryptResponse Decrypted string. For bytes, decode from text (e.g. Hexadecimal, Base64, Base64-URL, Base64-MIME, etc) back to bytes.
type DecryptResponse = string

// ElasticKey defines model for ElasticKey.
type ElasticKey struct {
	// Algorithm Cryptographic algorithm(s) used for Material Keys in the Elastic Key. The first is the content encryption algorithm, and the second is the optional key encryption algorithm. If key encryption algorithm is 'dir', the Elastic Key Key is directly used on values. direct encryption is useful for small values. If key encryption algorithm is 'K*W', a random Content Encryption Key (CEK) is used directly on values, and the Elastic Key Key is used to encrypt the CEK. Key wrap is useful for large values (e.g. files, blobs, etc). If in doubt, it is safe to use 'A256GCM/A256KW' for all values; it is the default.
	Algorithm *ElasticKeyAlgorithm `json:"algorithm,omitempty"`

	// Description Description for an Elastic Key.
	Description *ElasticKeyDescription `json:"description,omitempty"`

	// ElasticKeyID Unique UUID for an Elastic Key.
	ElasticKeyID *ElasticKeyID `json:"elastic_key_id,omitempty"`

	// ImportAllowed Indicates if the Elastic Key supports import (BYOK).
	ImportAllowed *ElasticKeyImportAllowed `json:"import_allowed,omitempty"`

	// Name Friendly name for an Elastic Key.
	Name *ElasticKeyName `json:"name,omitempty"`

	// Provider Provider of the Elastic Key management service.
	Provider *ElasticKeyProvider `json:"provider,omitempty"`

	// Status Status of the Elastic Key.
	Status *ElasticKeyStatus `json:"status,omitempty"`

	// VersioningAllowed Indicates if the Elastic Key supports versioning.
	VersioningAllowed *ElasticKeyVersioningAllowed `json:"versioning_allowed,omitempty"`
}

// ElasticKeyAlgorithm Cryptographic algorithm(s) used for Material Keys in the Elastic Key. The first is the content encryption algorithm, and the second is the optional key encryption algorithm. If key encryption algorithm is 'dir', the Elastic Key Key is directly used on values. direct encryption is useful for small values. If key encryption algorithm is 'K*W', a random Content Encryption Key (CEK) is used directly on values, and the Elastic Key Key is used to encrypt the CEK. Key wrap is useful for large values (e.g. files, blobs, etc). If in doubt, it is safe to use 'A256GCM/A256KW' for all values; it is the default.
type ElasticKeyAlgorithm string

// ElasticKeyCreate defines model for ElasticKeyCreate.
type ElasticKeyCreate struct {
	// Algorithm Cryptographic algorithm(s) used for Material Keys in the Elastic Key. The first is the content encryption algorithm, and the second is the optional key encryption algorithm. If key encryption algorithm is 'dir', the Elastic Key Key is directly used on values. direct encryption is useful for small values. If key encryption algorithm is 'K*W', a random Content Encryption Key (CEK) is used directly on values, and the Elastic Key Key is used to encrypt the CEK. Key wrap is useful for large values (e.g. files, blobs, etc). If in doubt, it is safe to use 'A256GCM/A256KW' for all values; it is the default.
	Algorithm *ElasticKeyAlgorithm `json:"algorithm,omitempty"`

	// Description Description for an Elastic Key.
	Description ElasticKeyDescription `json:"description"`

	// ImportAllowed Indicates if the Elastic Key supports import (BYOK).
	ImportAllowed *ElasticKeyImportAllowed `json:"import_allowed,omitempty"`

	// Name Friendly name for an Elastic Key.
	Name ElasticKeyName `json:"name"`

	// Provider Provider of the Elastic Key management service.
	Provider *ElasticKeyProvider `json:"provider,omitempty"`

	// VersioningAllowed Indicates if the Elastic Key supports versioning.
	VersioningAllowed *ElasticKeyVersioningAllowed `json:"versioning_allowed,omitempty"`
}

// ElasticKeyDescription Description for an Elastic Key.
type ElasticKeyDescription = string

// ElasticKeyID Unique UUID for an Elastic Key.
type ElasticKeyID = openapi_types.UUID

// ElasticKeyImportAllowed Indicates if the Elastic Key supports import (BYOK).
type ElasticKeyImportAllowed = bool

// ElasticKeyMaterialKeysQueryParams defines model for ElasticKeyMaterialKeysQueryParams.
type ElasticKeyMaterialKeysQueryParams struct {
	MaterialKeyID *[]MaterialKeyID `json:"material_key_id,omitempty"`

	// MaxExpirationDate ISO 8601 UTC timestamp of Material Key generation.
	MaxExpirationDate *MaterialKeyExpirationDate `json:"max_expiration_date,omitempty"`

	// MaxGenerateDate ISO 8601 UTC timestamp of Material Key generation.
	MaxGenerateDate *MaterialKeyGenerateDate `json:"max_generate_date,omitempty"`

	// MaxImportDate ISO 8601 UTC timestamp of Material Key generation.
	MaxImportDate *MaterialKeyImportDate `json:"max_import_date,omitempty"`

	// MaxRevocationDate ISO 8601 UTC timestamp of Material Key generation.
	MaxRevocationDate *MaterialKeyRevocationDate `json:"max_revocation_date,omitempty"`

	// MinExpirationDate ISO 8601 UTC timestamp of Material Key generation.
	MinExpirationDate *MaterialKeyExpirationDate `json:"min_expiration_date,omitempty"`

	// MinGenerateDate ISO 8601 UTC timestamp of Material Key generation.
	MinGenerateDate *MaterialKeyGenerateDate `json:"min_generate_date,omitempty"`

	// MinImportDate ISO 8601 UTC timestamp of Material Key generation.
	MinImportDate *MaterialKeyImportDate `json:"min_import_date,omitempty"`

	// MinRevocationDate ISO 8601 UTC timestamp of Material Key generation.
	MinRevocationDate *MaterialKeyRevocationDate `json:"min_revocation_date,omitempty"`

	// Page Page number starting at 0.
	Page *PageNumber `json:"page,omitempty"`

	// Size Page number.
	Size *PageSize          `json:"size,omitempty"`
	Sort *[]MaterialKeySort `json:"sort,omitempty"`
}

// ElasticKeyName Friendly name for an Elastic Key.
type ElasticKeyName = string

// ElasticKeyProvider Provider of the Elastic Key management service.
type ElasticKeyProvider string

// ElasticKeySort defines model for ElasticKeySort.
type ElasticKeySort string

// ElasticKeyStatus Status of the Elastic Key.
type ElasticKeyStatus string

// ElasticKeyUpdate defines model for ElasticKeyUpdate.
type ElasticKeyUpdate struct {
	// Description Description for an Elastic Key.
	Description ElasticKeyDescription `json:"description"`

	// Name Friendly name for an Elastic Key.
	Name ElasticKeyName `json:"name"`
}

// ElasticKeyVersioningAllowed Indicates if the Elastic Key supports versioning.
type ElasticKeyVersioningAllowed = bool

// ElasticKeysQueryParams defines model for ElasticKeysQueryParams.
type ElasticKeysQueryParams struct {
	Algorithm    *[]ElasticKeyAlgorithm `json:"algorithm,omitempty"`
	ElasticKeyID *[]ElasticKeyID        `json:"elastic_key_id,omitempty"`

	// ImportAllowed Indicates if the Elastic Key supports import (BYOK).
	ImportAllowed *ElasticKeyImportAllowed `json:"import_allowed,omitempty"`
	Name          *[]ElasticKeyName        `json:"name,omitempty"`

	// Page Page number starting at 0.
	Page     *PageNumber           `json:"page,omitempty"`
	Provider *[]ElasticKeyProvider `json:"provider,omitempty"`

	// Size Page number.
	Size   *PageSize           `json:"size,omitempty"`
	Sort   *[]ElasticKeySort   `json:"sort,omitempty"`
	Status *[]ElasticKeyStatus `json:"status,omitempty"`

	// VersioningAllowed Indicates if the Elastic Key supports versioning.
	VersioningAllowed *ElasticKeyVersioningAllowed `json:"versioning_allowed,omitempty"`
}

// EncryptContext Base64URL-encoded context. This is clear data used for authentication and integrity checking during decryption (e.g. namespace, context).
type EncryptContext = string

// EncryptParams defines model for EncryptParams.
type EncryptParams struct {
	// Context Base64URL-encoded context. This is clear data used for authentication and integrity checking during decryption (e.g. namespace, context).
	Context *EncryptContext `json:"context,omitempty"`
}

// EncryptRequest Clear string to be encrypted. For bytes, pre-encode as text (e.g. Hexadecimal, Base64, Base64-URL, Base64-MIME, etc).
type EncryptRequest = string

// EncryptResponse JSON Web Encryption (JWE) message in compact serialized format. See RFC 7516 JSON Web Encryption (JWE) for more details. Compact serialized format is 'Header.EncryptedKey.IV.Ciphertext.AuthenticationTag'. Each section is Base64Url-encoded; Some parts can be empty depending on 'alg' and 'enc' headers. - Header: Required base64Url-encoded JSON key/values for the JWE. - EncryptedKey: Optional base64Url-encoded of an encrypted symmetric key used to encrypt the payload. Mon-empty for envelope encryption (e.g. alg=a256gcmkw), or empty for direct encryption (e.g. alg=dir). - IV: Required base64Url-encoded Initialization Vector (IV) used to encrypt the payload. For AES-GCM or AES-GCM-SIV it contains a 12-bytes nonce. For AES-CBC it contains a 16-bytes IV. - Ciphertext: Required base64Url-encoded encrypted bytes. - AuthenticationTag: Required base64Url-encoded authentication tag. For AES-GCM or AES-GCM-SIV it's a 16-bytes authentication tag. For AES-CBC-HMAC it contains an AEAD HMAC hash.
type EncryptResponse = string

// GenerateAlgorithm Key or Key Pair algorithm.
type GenerateAlgorithm string

// GenerateParams defines model for GenerateParams.
type GenerateParams struct {
	// Alg Key or Key Pair algorithm.
	Alg *GenerateAlgorithm `json:"alg,omitempty"`

	// Context Base64URL-encoded context. This is clear data used for authentication and integrity checking during decryption (e.g. namespace, context).
	Context *EncryptContext `json:"context,omitempty"`
}

// GenerateResponse JSON Web Encryption (JWE) message in compact serialized format. See RFC 7516 JSON Web Encryption (JWE) for more details. Compact serialized format is 'Header.EncryptedKey.IV.Ciphertext.AuthenticationTag'. Each section is Base64Url-encoded; Some parts can be empty depending on 'alg' and 'enc' headers. - Header: Required base64Url-encoded JSON key/values for the JWE. - EncryptedKey: Optional base64Url-encoded of an encrypted symmetric key used to encrypt the payload. Mon-empty for envelope encryption (e.g. alg=a256gcmkw), or empty for direct encryption (e.g. alg=dir). - IV: Required base64Url-encoded Initialization Vector (IV) used to encrypt the payload. For AES-GCM or AES-GCM-SIV it contains a 12-bytes nonce. For AES-CBC it contains a 16-bytes IV. - Ciphertext: Required base64Url-encoded encrypted bytes. - AuthenticationTag: Required base64Url-encoded authentication tag. For AES-GCM or AES-GCM-SIV it's a 16-bytes authentication tag. For AES-CBC-HMAC it contains an AEAD HMAC hash.
type GenerateResponse = string

// HTTPError defines model for HTTPError.
type HTTPError struct {
	// Error HTTP status message
	Error string `json:"error"`

	// Message Detailed error message
	Message string `json:"message"`

	// Status HTTP status code
	Status int `json:"status"`
}

// MaterialKey defines model for MaterialKey.
type MaterialKey struct {
	// ClearPublic Clear public key Material Key (if applicable)
	ClearPublic *MaterialKeyClearPublic `json:"clear_public,omitempty"`

	// ElasticKeyID Unique UUID for an Elastic Key.
	ElasticKeyID ElasticKeyID `json:"elastic_key_id"`

	// ExpirationDate ISO 8601 UTC timestamp of Material Key generation.
	ExpirationDate *MaterialKeyExpirationDate `json:"expiration_date,omitempty"`

	// GenerateDate ISO 8601 UTC timestamp of Material Key generation.
	GenerateDate *MaterialKeyGenerateDate `json:"generate_date,omitempty"`

	// ImportDate ISO 8601 UTC timestamp of Material Key generation.
	ImportDate *MaterialKeyImportDate `json:"import_date,omitempty"`

	// MaterialKeyID Unique UUID for a Material Key.
	MaterialKeyID MaterialKeyID `json:"material_key_id"`

	// RevocationDate ISO 8601 UTC timestamp of Material Key generation.
	RevocationDate *MaterialKeyRevocationDate `json:"revocation_date,omitempty"`
}

// MaterialKeyClearPublic Clear public key Material Key (if applicable)
type MaterialKeyClearPublic = string

// MaterialKeyExpirationDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyExpirationDate = time.Time

// MaterialKeyGenerate defines model for MaterialKeyGenerate.
type MaterialKeyGenerate = map[string]interface{}

// MaterialKeyGenerateDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyGenerateDate = time.Time

// MaterialKeyID Unique UUID for a Material Key.
type MaterialKeyID = openapi_types.UUID

// MaterialKeyImportDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyImportDate = time.Time

// MaterialKeyRevocationDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyRevocationDate = time.Time

// MaterialKeySort defines model for MaterialKeySort.
type MaterialKeySort string

// MaterialKeyUpdate defines model for MaterialKeyUpdate.
type MaterialKeyUpdate struct {
	// ElasticKeyID Unique UUID for an Elastic Key.
	ElasticKeyID ElasticKeyID `json:"elastic_key_id"`

	// MaterialKeyID Unique UUID for a Material Key.
	MaterialKeyID MaterialKeyID `json:"material_key_id"`
}

// MaterialKeysQueryParams defines model for MaterialKeysQueryParams.
type MaterialKeysQueryParams struct {
	ElasticKeyID  *[]ElasticKeyID  `json:"elastic_key_id,omitempty"`
	MaterialKeyID *[]MaterialKeyID `json:"material_key_id,omitempty"`

	// MaxExpirationDate ISO 8601 UTC timestamp of Material Key generation.
	MaxExpirationDate *MaterialKeyExpirationDate `json:"max_expiration_date,omitempty"`

	// MaxGenerateDate ISO 8601 UTC timestamp of Material Key generation.
	MaxGenerateDate *MaterialKeyGenerateDate `json:"max_generate_date,omitempty"`

	// MaxImportDate ISO 8601 UTC timestamp of Material Key generation.
	MaxImportDate *MaterialKeyImportDate `json:"max_import_date,omitempty"`

	// MaxRevocationDate ISO 8601 UTC timestamp of Material Key generation.
	MaxRevocationDate *MaterialKeyRevocationDate `json:"max_revocation_date,omitempty"`

	// MinExpirationDate ISO 8601 UTC timestamp of Material Key generation.
	MinExpirationDate *MaterialKeyExpirationDate `json:"min_expiration_date,omitempty"`

	// MinGenerateDate ISO 8601 UTC timestamp of Material Key generation.
	MinGenerateDate *MaterialKeyGenerateDate `json:"min_generate_date,omitempty"`

	// MinImportDate ISO 8601 UTC timestamp of Material Key generation.
	MinImportDate *MaterialKeyImportDate `json:"min_import_date,omitempty"`

	// MinRevocationDate ISO 8601 UTC timestamp of Material Key generation.
	MinRevocationDate *MaterialKeyRevocationDate `json:"min_revocation_date,omitempty"`

	// Page Page number starting at 0.
	Page *PageNumber `json:"page,omitempty"`

	// Size Page number.
	Size *PageSize          `json:"size,omitempty"`
	Sort *[]MaterialKeySort `json:"sort,omitempty"`
}

// PageNumber Page number starting at 0.
type PageNumber = int

// PageSize Page number.
type PageSize = int

// SignContext Base64URL-encoded context. This is clear data used for integrity checking during verify (e.g. namespace, context).
type SignContext = string

// SignParams defines model for SignParams.
type SignParams struct {
	// Context Base64URL-encoded context. This is clear data used for integrity checking during verify (e.g. namespace, context).
	Context *SignContext `json:"context,omitempty"`
}

// SignRequest Clear text to be signed. Can be JSON-encoded to create a JWT, or freeform to create a JWS. If you need freeform, encode as text (e.g. Base64-URL, Base64-MIME, Base64, Hexadecimal, etc).
type SignRequest = string

// SignResponse JSON Web Signature (JWS) message in compact serialized format. See RFC 7515 JSON Web Signature (JWS) for more details. Compact serialized format is 'Header.Payload.Signature'. Each section is Base64Url-encoded. All parts are non-empty. - Header: Required base64Url-encoded JSON key/values for the JWS message. - Plaintext: Required base64Url-encoded clear text. Payload can be freeform (JWS), or in a special case it can be JSON (JWT). - Signature: Required base64Url-encoded signature.
type SignResponse = string

// VerifyRequest JSON Web Signature (JWS) message in compact serialized format. See RFC 7515 JSON Web Signature (JWS) for more details. Compact serialized format is 'Header.Payload.Signature'. Each section is Base64Url-encoded. All parts are non-empty. - Header: Required base64Url-encoded JSON key/values for the JWS message. - Plaintext: Required base64Url-encoded clear text. Payload can be freeform (JWS), or in a special case it can be JSON (JWT). - Signature: Required base64Url-encoded signature.
type VerifyRequest = string

// VerifyResponse Optional message about verification result
type VerifyResponse = string

// ElasticKeyQueryParamAlgorithms defines model for ElasticKeyQueryParamAlgorithms.
type ElasticKeyQueryParamAlgorithms = []ElasticKeyAlgorithm

// ElasticKeyQueryParamElasticKeyIDS defines model for ElasticKeyQueryParamElasticKeyIDS.
type ElasticKeyQueryParamElasticKeyIDS = []ElasticKeyID

// ElasticKeyQueryParamImportAllowed Indicates if the Elastic Key supports import (BYOK).
type ElasticKeyQueryParamImportAllowed = ElasticKeyImportAllowed

// ElasticKeyQueryParamNames defines model for ElasticKeyQueryParamNames.
type ElasticKeyQueryParamNames = []ElasticKeyName

// ElasticKeyQueryParamPageNumber Page number starting at 0.
type ElasticKeyQueryParamPageNumber = PageNumber

// ElasticKeyQueryParamPageSize Page number.
type ElasticKeyQueryParamPageSize = PageSize

// ElasticKeyQueryParamProviders defines model for ElasticKeyQueryParamProviders.
type ElasticKeyQueryParamProviders = []ElasticKeyProvider

// ElasticKeyQueryParamSorts defines model for ElasticKeyQueryParamSorts.
type ElasticKeyQueryParamSorts = []ElasticKeySort

// ElasticKeyQueryParamStatuses defines model for ElasticKeyQueryParamStatuses.
type ElasticKeyQueryParamStatuses = []ElasticKeyStatus

// ElasticKeyQueryParamVersioningAllowed Indicates if the Elastic Key supports versioning.
type ElasticKeyQueryParamVersioningAllowed = ElasticKeyVersioningAllowed

// MaterialKeyQueryParamElasticKeyIDS defines model for MaterialKeyQueryParamElasticKeyIDS.
type MaterialKeyQueryParamElasticKeyIDS = []ElasticKeyID

// MaterialKeyQueryParamMaterialKeyIDS defines model for MaterialKeyQueryParamMaterialKeyIDS.
type MaterialKeyQueryParamMaterialKeyIDS = []MaterialKeyID

// MaterialKeyQueryParamMaximumExpirationDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMaximumExpirationDate = MaterialKeyExpirationDate

// MaterialKeyQueryParamMaximumGenerateDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMaximumGenerateDate = MaterialKeyGenerateDate

// MaterialKeyQueryParamMaximumImportDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMaximumImportDate = MaterialKeyImportDate

// MaterialKeyQueryParamMaximumRevocationDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMaximumRevocationDate = MaterialKeyRevocationDate

// MaterialKeyQueryParamMinimumExpirationDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMinimumExpirationDate = MaterialKeyExpirationDate

// MaterialKeyQueryParamMinimumGenerateDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMinimumGenerateDate = MaterialKeyGenerateDate

// MaterialKeyQueryParamMinimumImportDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMinimumImportDate = MaterialKeyImportDate

// MaterialKeyQueryParamMinimumRevocationDate ISO 8601 UTC timestamp of Material Key generation.
type MaterialKeyQueryParamMinimumRevocationDate = MaterialKeyRevocationDate

// MaterialKeyQueryParamPageNumber Page number starting at 0.
type MaterialKeyQueryParamPageNumber = PageNumber

// MaterialKeyQueryParamPageSize Page number.
type MaterialKeyQueryParamPageSize = PageSize

// MaterialKeyQueryParamSorts defines model for MaterialKeyQueryParamSorts.
type MaterialKeyQueryParamSorts = []MaterialKeySort

// HTTP400BadRequest defines model for HTTP400BadRequest.
type HTTP400BadRequest struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP401Unauthorized defines model for HTTP401Unauthorized.
type HTTP401Unauthorized struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP403Forbidden defines model for HTTP403Forbidden.
type HTTP403Forbidden struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP404NotFound defines model for HTTP404NotFound.
type HTTP404NotFound struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP409Conflict defines model for HTTP409Conflict.
type HTTP409Conflict struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP429TooManyRequests defines model for HTTP429TooManyRequests.
type HTTP429TooManyRequests struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP500InternalServerError defines model for HTTP500InternalServerError.
type HTTP500InternalServerError struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP502BadGateway defines model for HTTP502BadGateway.
type HTTP502BadGateway struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP503ServiceUnavailable defines model for HTTP503ServiceUnavailable.
type HTTP503ServiceUnavailable struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP504GatewayTimeout defines model for HTTP504GatewayTimeout.
type HTTP504GatewayTimeout struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8bXPbOJLwX0Hx2SrbO7IsyVY21tbzQZE1E8fjxGfZSe3O5DwQ2ZKwIQEOADrWTPm/",
	"X+GFL6AoWaI0ia/OH1wWm+hGvwDdALrBPz2fRTGjQKXwen96MeY4AglcPw1DLCTxL2D+Xwnw+ZV62Q+n",
	"jBM5i3SLAITPSSwJo17P+5GEEjgaz5HFRBcwRzjFaHoNDx7ikAXg9SRPoOERhfa7Iu41PIoj8Hpe1t5r",
	"eMKfQYRVT0SC6fJvHCZez/t/RznnR6aZOMoZztj0HhuenMeaMOd4rp6FnIcKMGFcv6+SM4edn41WiSpn",
	"4Ih7fob2b2/Pzw7WFBcM7t0XmN+RYBuZz8/qCnsexYzLfhiyrxCsEvbrDOQMOCIaARGBsEFSwlZJZxre",
	"2VaOdGsK5bD2uESA9zgCsYmVFHtrGkj/28Isire6hrnCU3ifRGPguuMK7mI8hbXVWiD3uKLHEfkDlvUn",
	"1LtN+tPElvbG2T0JrLtZx5nEFmFN26XNt7FfymNdG44YlxXyjWLwyWSOBOOS0CnCAv02IRAGarz0AsLB",
	"Vy1/Q/vQnDYb6DclUg8L/7eDJrqGGLBEmbtGE8ZRlISSxCFokkjTEmvqSWFsoyMlY239SCwTsdn0FRpn",
	"XeF0463EMxRqCvgRuCCMEjrdwMPeZ0hreNm88RaedpFNNWsvsQROcLi74JgkJHiuwbFS2gJwDXHT1lbe",
	"NQWNLFZtSR0mtxD1gURJNHyICcdKvDMsYSOJI0MBQUYCBVgC2ifUDxNB7uFg2SiO8MNdjnan0NYexgVp",
	"Ssw/PiHrT0CBYwm1JZ1aAhvJmSLVltJh+ykZzSKqtoR2tbeJfHbdV1e6AsNPyXYN98zfbqzyjMRGMuZo",
	"teUsMb9cVkK3nZeGQq15Seg3nZeG0/rz0kq6+bwk9JvNS8Nj3XlpJdx0XhL6Teal4W6beWnlqzMvCf2W",
	"8/Kv3Z8t7fKv2aBVdrer3UtpgfO8NjIFydfbyTw2PA4iZtTuW97e3FydtFpvcHANvycgpAL6jEqg+ieO",
	"45CYAXX0H6E0+GeBRxyGHyZe75fVTKo+hpwztRH9U+1sY+CSmP5Bw9WPBxzFmtE3OEApM5k4QnJCp0qe",
	"CIRQQ9PBuZkB4gYH+SwJA0SZRGNACVWbdMlYgBhHX7FAERFCGV41JxyC3ITaVAv92U1YsbuTVqvh2Ric",
	"PpmZb58sEUIlTO2UsCA2/g/40nv8/KiA7tAsCv7YsKZp31KcyBnj5A+z//q+xnG4Wdc6/UTOgErLKppg",
	"EoK2RyKAo4CB0Oaa4XtAMXBtIUaFnlLKxwYgtKWwnprrW6ntWKntWKld10qOBjIzHf/I+JgEAdDvb6Oc",
	"lZoGEonvAwQQoHEitQVw3gCCKrNh3wchkGS6OQfBEu7D+qY6dkx17JjquK6pckVkdjp5z+SPLKHPYCq9",
	"ZxIZVmp4OQgyJbsOb6Iorq/3E0fvJ47eT+rqPZcs0/vpgNFJSPxnEF8yTrYOLoqXEJQtggTU2MfIt8TR",
	"VyJnei74CedApT75A8QmNSfIqWOoU8dQp3UNlakitVPn9IaxS0znNg6J72+uG8aQ4ghlLK1rt3+xxDgn",
	"ofQvGUORomNNKRChCKMpuQeKcMQSKrV1SLS+VTqOVTqOVTq1rbIosTVPt9U6pxI4xeEI+D3wYaqu72ui",
	"lClkuEIGde3gQ1FC4SEGX80kTR4xX0+bADGq54vQhNe1S9dZn3Wd9Vm3/vqsWszMNp03OPgJS/iK589j",
	"EZ0ys4mfM4pGHHwg92rJRRGh9zgkOt7ofQOacBZpqySxkBxwtLF5Oo55Oo55Otssn1ORM6McK1sRH24p",
	"vsckxOMQvr9xLE+oyFQNIxGRBpdwjhKqyKggNMM0UL8KUcuGJwlRzDjmc8TugYcM60V4hJWiKabrh6Ou",
	"s17rOuu1bv31WpVeMkueWNvekAhY8gzWEZYflDJUw4IBMWsJO90Q1uEnnO9yrp04ljpxLFV7hVeWXbWw",
	"alTdn4HP57EsHCm46O9GH96jTzBGQ6obqk3H/rtPwwNkNaZis7IQ9qUSmOBQbbfUhjDCsolGAOj6xwH6",
	"R7f9Ci0npo9kGFcbSIlJKJposIymmkx7bwEHwJuWDgQXMG+ef2wOSDwDLuFBNt2N0g2e7jXREPszJMyx",
	"kSLzBgt4dXLLw0OgPgsg+CcasQhQjLkUyMdULR0hiuUcBRADDQidqji3h8PpHsI0QHtA/T0009yIJjpE",
	"hrGeXhDonfC43IfRwheYH93jMIF87/zu0zBVqqJUlK2HPmht4bCCHpso3w9pcyTmUQSSE191onaAgfIo",
	"9r3uKcZz5VKa6JLRQyOfYgLoPYQshrStNg80p02Ew+n/x53uq6kfffl60FC+KEczJ3HVSAHhB0qY848r",
	"VXJOidRWNrvaj+BLxtH++ceD1fz/yDjqD0eHPw0uUf7zcHT+ERG1A6ASEyoQRu3O4Xgu9TZYOc8McfBm",
	"UG75yrY8/6gYz0fUSgFy7WtkhbkwAFcSwO6+XuLpE9LtOcyuQh+8GRy+veyXBKWoP+yfIf1ihsWs+Sv1",
	"Gl6MpVo5eT3vv3/pH/4bH/7ROjy9O/z8w6+/Nh3A38uANVr8rcoTZg7IuNFFD2QbqIGtkYxgWuwGCkCp",
	"z/peeJB26L2FBxyATyIcNuwsT/8f3l7/nP2+PL8cNhBI/wCNsf9FjTNjvypO80S/LmN0gk5eUFivfNAR",
	"eV0KZwWkx0a5kGHDsoVSFV3d4rn0lHzTyrWsiqpWzVQeTjcttqkoa9mymqUUk4vjpl8cJaX9vRrjbMpx",
	"PCN+Xs+6L6wHVI62mMDSe+JS6UsTqQXLhHChg6Q+0jDrrqJzzmg3dAQzezaf0SDFYWmoUeGjCrGJzidL",
	"X+rwHBC+11iozFF/RNh4EdrQxCgycbBZEUiIUI0mSajlFxEOw6z1Uzxc/P3TXgNhxDENWIQGVhOFpYfi",
	"Z38wvDiw/QQ5axlXuZIqJKmKTYPhRVO//8pxXBIgxHwKlrD1VBMSqk7GIRsL44m0ZISigCVj2VBOmwgk",
	"8ETvCxIBaK/f6b76aXB5pP5ffNrTpHPN/NOimOP4CU5CqRNbVC0kf/FcZK/h9dunnRKg89oFpCjt046L",
	"kgMsSgbIUDqvSygZIEVJAQXGfhpcLvCWw3L2MliBwwVcB5bzuYir3y1wu4hbgFncgPACVvpk2tsn2/J6",
	"1D/80B9eHXbbnQLKAtjglsFlIsevT6qIpOASEQsuE+l0X1URScElIhZcIlJBoALZRWzfdV20FJAhWYBF",
	"GQ7O3h4ORz8sjNyKF4bE4osyqfKIrnhRIlUe4fmL0kiveFEmVRr59sUijUVki6WXdqNuu+NOZwM+fn3i",
	"TmoD7nRfuVO7QKSojgKRojIKRIqqKBIpKKJIpKCGIpGCElxxipPRlag4JV2hihPTlWsJtZJzcKVbRs11",
	"FK6My6i5TiOnlruOnE7uQHIKuRvJcSucSU6kwqXk1CocSwXZ3L1UkM2dTAXZ3NVUkM0dTgXZ3O1UkM2d",
	"zyLZpSSXkqsilTslh1DumhwyuYPKiVS6qZxYpbPKiVa6rAri1TO10n1VEK+euZWurIp45UyudGsLxJdR",
	"XUbOa3jXI2P265EZVdcjM2ivLPzKwq8sfGjhQwsfWvhbC39r4W/T9sHZqO99bhQTHeVF0orN4ICDLT57",
	"flvC/9Wbut1vzdJCIrUOtleuilr+vHLzdubao3xIkT2Z5Th1NmZewzlVJsLZTSzZSVzhOWdhiM6wxGMs",
	"FLcRfvgZ6FTOvF6n29UHxOlze+UgPT9b5PmWkt8TQLe352dLeDYHrl7PSxISrJ4FT1zvO6eBrkgRiEwW",
	"b9oksUIWabHp/pt/fbg4cJQ2waGAjIExYyFg6nJQKLATeW2hWJyY5XsQO7v+UHW5oH7tcqOiiL9ujXBj",
	"oWC+Xj1uo7IovX7Na6Oy8HsrnS0UWG+hs1Ixc22dVRQMb6Oz2Caq1i3zbZiC3bXrdBumxHVnla2rD8Xe",
	"29BSKgjjBGgQmlu0T7rU1a7y1fEGnvKqELNcltI3aWVQ0YVFmOIpRLp6yKRGi2cuaTmCu8jIoCv5GVlT",
	"pLTcU95efzTwyke/vbOhhurbnP38pwWnUdm+yh7t62zdYt/nz7bBYly2LSteWBR3HWKbl4C2KTxUNC0B",
	"bVNz6mub2Af96vNqjWaHxaWctoZXWLdoSl+t9hTJjH9TI6sUaRKE1mUUAKk/8hpe5poyLOxLcq9XIkTg",
	"sUspgBAk3H3F4m5ZZ4UmS/svtMl6q3i3moFFzoXEXEJgG6nlAqFEzHKIM9oLilthm9s4qFxM72IxXGcN",
	"u+2icY17uestjfK55Xg+c0th1bJo9VrI2aTs8vsXi8monVym3fmGZkcfWtg8JBf3Rrv8WsBfGenXuYyf",
	"+tadXX//Fhk6s+vSKaKHiiIYWydy/XOWrvdN0ybSmzkikB8C5ijAEuf5ulJSHtMA6eIdTuQc+TPwvxA6",
	"RUHC9T8olU+oESpi7EMj7U1viZZm6Cuz61ayZdPfzyVeqVBXP6t0uLSQaKAVZDjTeXbIiyaclH7MwaoZ",
	"YbFdUr+5QiXLCw5eSp6+ZcnTS6nTS6nT/5FSp/R8YUUZiFrzMa6XfleY8NKHzewe5HrUPzppnZoz8f7R",
	"cesfHfuz0zp57TW84eDoqttp21/2FHxwdGXOvz9cXB0Ng0632z71Gh7z5ZE5B1e/TFv1y7RVv9qn6dt2",
	"57W7qM8bLhV2xcrzqbCzqK/Hxi5DVkr/JRS8hIKXUPASCr5hKMgvMPSW3l9wXZHCsN8kS52P9+SxZuFW",
	"QzlfJc3VbnOJa22CYsnZWZE7ZVqveJXh9HSNW/fFY5bsa2pgr6el/FUdthSOnys2OGrXcRcn45D4G5xj",
	"683KlcHaurJ2l+mNXaU2dpMKWsijbZQ+211KpDR8Fr7oVub0iWFUtP6SfawZUTrUOJ+V2ScTZC84jUM4",
	"qJr6y+27eDQ4+oBev2q10e3NQN83EhJHsQp9Tqd2UNgPLuSrs06r0z1sHR+2T27anV6r1Wu1/l3M6iqt",
	"HyqyT7CZDh69bAsCYmLyVWGiuenZSqWu/tbSM5F0rTS5w9JaafLqKfRclfDUV5WeCZurE2OLSbFVmbLF",
	"TyOWvyXUr2qXope/6OU8W1QX5ubFLFrhyU2RFVEWv5JWguQpMwdq0Rc/XFWCWPQydGlerWCRZcmb7cLn",
	"dmFmx6FhdTblL0p6vBSsvBSsvBSsfOeCFfczfKXKEDwFRPVLpLPi+nN1ErWcyFf8tkXFHsh0kX52b2kH",
	"DslO17kyXuigU9XBiEzprpNcyzNa98DJZL7LbJbif8tUVlEFlXZWDZ5IYumclElhCTKlEDTRwJyWvRt9",
	"eJ+pTzKkix4AYfTu040+P5pwALXSKb0c6Utfc5YgCkqvtlUDVSbClua80qSYkylbmggzkj559KmaYZlw",
	"QPvvPo1qnHx20VJaNQ8+r+xJWEZundPNJuqHoT3cxBwQTU8Btz64HBWv7V+F+iMdT5yc+dlAaiIrTXri",
	"mg0RrSI9avTnj0QMvlpb+1iAPtTKh5xqeqNPHDONrOxdpK02PP76Yb3DrY964j/9SYmXkfUysuqNrGVO",
	"K8sXpEMJj1kiTSRKT4k5iCSs+AaMigaETtgi1evh6Ab1r86zMtRoDIGS9uJyhC6Jzxmy38PRQksizSWS",
	"q/O8KNLrea1mq9lWUrAYKI6J1/OOm63msdHTTHg9moTh4/8EAAD//9pPuZcwaQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
