// Package authz provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1-0.20250618140738-aae687ce8fe9 DO NOT EDIT.
package authz

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClientBasicAuthScopes  = "clientBasicAuth.Scopes"
	ClientSecretPostScopes = "clientSecretPost.Scopes"
)

// Defines values for AuthZTokenResponseTokenType.
const (
	AuthZTokenResponseTokenTypeBearer AuthZTokenResponseTokenType = "Bearer"
)

// Defines values for HealthResponseDatabase.
const (
	Error HealthResponseDatabase = "error"
	Ok    HealthResponseDatabase = "ok"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for IntrospectionResponseTokenType.
const (
	IntrospectionResponseTokenTypeBearer IntrospectionResponseTokenType = "Bearer"
)

// Defines values for OAuth2ErrorError.
const (
	InvalidClient          OAuth2ErrorError = "invalid_client"
	InvalidGrant           OAuth2ErrorError = "invalid_grant"
	InvalidRequest         OAuth2ErrorError = "invalid_request"
	InvalidScope           OAuth2ErrorError = "invalid_scope"
	ServerError            OAuth2ErrorError = "server_error"
	TemporarilyUnavailable OAuth2ErrorError = "temporarily_unavailable"
	UnauthorizedClient     OAuth2ErrorError = "unauthorized_client"
	UnsupportedGrantType   OAuth2ErrorError = "unsupported_grant_type"
)

// Defines values for AuthorizeGETParamsResponseType.
const (
	AuthorizeGETParamsResponseTypeCode AuthorizeGETParamsResponseType = "code"
)

// Defines values for AuthorizeGETParamsCodeChallengeMethod.
const (
	AuthorizeGETParamsCodeChallengeMethodS256 AuthorizeGETParamsCodeChallengeMethod = "S256"
)

// Defines values for AuthorizeFormdataBodyCodeChallengeMethod.
const (
	AuthorizeFormdataBodyCodeChallengeMethodS256 AuthorizeFormdataBodyCodeChallengeMethod = "S256"
)

// Defines values for AuthorizeFormdataBodyResponseType.
const (
	AuthorizeFormdataBodyResponseTypeCode AuthorizeFormdataBodyResponseType = "code"
)

// Defines values for IntrospectFormdataBodyTokenTypeHint.
const (
	IntrospectFormdataBodyTokenTypeHintAccessToken  IntrospectFormdataBodyTokenTypeHint = "access_token"
	IntrospectFormdataBodyTokenTypeHintRefreshToken IntrospectFormdataBodyTokenTypeHint = "refresh_token"
)

// Defines values for RevokeFormdataBodyTokenTypeHint.
const (
	RevokeFormdataBodyTokenTypeHintAccessToken  RevokeFormdataBodyTokenTypeHint = "access_token"
	RevokeFormdataBodyTokenTypeHintRefreshToken RevokeFormdataBodyTokenTypeHint = "refresh_token"
)

// Defines values for TokenFormdataBodyGrantType.
const (
	AuthorizationCode TokenFormdataBodyGrantType = "authorization_code"
	ClientCredentials TokenFormdataBodyGrantType = "client_credentials"
	RefreshToken      TokenFormdataBodyGrantType = "refresh_token"
)

// AuthZTokenResponse defines model for AuthZTokenResponse.
type AuthZTokenResponse struct {
	// AccessToken OAuth 2.0 access token (opaque or JWT)
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds
	ExpiresIn int `json:"expires_in"`

	// IDToken OpenID Connect ID Token (if openid scope requested)
	IDToken *string `json:"id_token,omitempty"`

	// RefreshToken Refresh token (optional, for authorization_code and refresh_token grants)
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope Space-delimited granted scopes
	Scope *string `json:"scope,omitempty"`

	// TokenType Token type (always "Bearer")
	TokenType AuthZTokenResponseTokenType `json:"token_type"`
}

// AuthZTokenResponseTokenType Token type (always "Bearer")
type AuthZTokenResponseTokenType string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Database Database connectivity status
	Database *HealthResponseDatabase `json:"database,omitempty"`

	// Status Overall service health status
	Status HealthResponseStatus `json:"status"`

	// Uptime Service uptime in seconds
	Uptime *int `json:"uptime,omitempty"`
}

// HealthResponseDatabase Database connectivity status
type HealthResponseDatabase string

// HealthResponseStatus Overall service health status
type HealthResponseStatus string

// IntrospectionResponse defines model for IntrospectionResponse.
type IntrospectionResponse struct {
	// Active Whether the token is currently active
	Active bool `json:"active"`

	// Aud Audience (intended recipient)
	Aud *string `json:"aud,omitempty"`

	// ClientID Client ID that token was issued to
	ClientID *string `json:"client_id,omitempty"`

	// Exp Expiration timestamp (Unix epoch)
	Exp *int `json:"exp,omitempty"`

	// Iat Issued-at timestamp (Unix epoch)
	Iat *int `json:"iat,omitempty"`

	// Iss Issuer (authorization server)
	Iss *string `json:"iss,omitempty"`

	// Scope Space-separated list of scopes
	Scope *string `json:"scope,omitempty"`

	// Sub Subject identifier
	Sub *string `json:"sub,omitempty"`

	// TokenType Token type
	TokenType *IntrospectionResponseTokenType `json:"token_type,omitempty"`

	// Username Username of resource owner
	Username *string `json:"username,omitempty"`
}

// IntrospectionResponseTokenType Token type
type IntrospectionResponseTokenType string

// OAuth2Error defines model for OAuth2Error.
type OAuth2Error struct {
	// Error OAuth 2.0 error code
	Error OAuth2ErrorError `json:"error"`

	// ErrorDescription Human-readable error description
	ErrorDescription *string `json:"error_description,omitempty"`

	// ErrorURI URI for error documentation
	ErrorURI *string `json:"error_uri,omitempty"`
}

// OAuth2ErrorError OAuth 2.0 error code
type OAuth2ErrorError string

// AuthorizeGETParams defines parameters for AuthorizeGET.
type AuthorizeGETParams struct {
	// ResponseType Must be "code" for authorization code flow
	ResponseType AuthorizeGETParamsResponseType `form:"response_type" json:"response_type"`

	// ClientID Registered OAuth 2.0 client identifier
	ClientID openapi_types.UUID `form:"client_id" json:"client_id"`

	// RedirectURI Client redirect URI (must match registered value)
	RedirectURI string `form:"redirect_uri" json:"redirect_uri"`

	// Scope Space-delimited scope values (e.g., "openid profile email")
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`

	// State Opaque value for CSRF protection
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// CodeChallenge PKCE code challenge (base64url-encoded SHA256 hash of code_verifier)
	CodeChallenge string `form:"code_challenge" json:"code_challenge"`

	// CodeChallengeMethod Must be "S256" (SHA256 hash)
	CodeChallengeMethod AuthorizeGETParamsCodeChallengeMethod `form:"code_challenge_method" json:"code_challenge_method"`
}

// AuthorizeGETParamsResponseType defines parameters for AuthorizeGET.
type AuthorizeGETParamsResponseType string

// AuthorizeGETParamsCodeChallengeMethod defines parameters for AuthorizeGET.
type AuthorizeGETParamsCodeChallengeMethod string

// AuthorizeFormdataBody defines parameters for Authorize.
type AuthorizeFormdataBody struct {
	// ClientID Registered OAuth 2.0 client identifier
	ClientID openapi_types.UUID `form:"client_id" json:"client_id"`

	// CodeChallenge PKCE code challenge (base64url-encoded SHA256 hash of code_verifier)
	CodeChallenge string `form:"code_challenge" json:"code_challenge"`

	// CodeChallengeMethod Must be "S256" (SHA256 hash)
	CodeChallengeMethod AuthorizeFormdataBodyCodeChallengeMethod `form:"code_challenge_method" json:"code_challenge_method"`

	// RedirectURI Client redirect URI (must match registered value)
	RedirectURI string `form:"redirect_uri" json:"redirect_uri"`

	// ResponseType Must be "code" for authorization code flow
	ResponseType AuthorizeFormdataBodyResponseType `form:"response_type" json:"response_type"`

	// Scope Space-delimited scope values (e.g., "openid profile email")
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`

	// State Opaque value for CSRF protection
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// AuthorizeFormdataBodyCodeChallengeMethod defines parameters for Authorize.
type AuthorizeFormdataBodyCodeChallengeMethod string

// AuthorizeFormdataBodyResponseType defines parameters for Authorize.
type AuthorizeFormdataBodyResponseType string

// IntrospectFormdataBody defines parameters for Introspect.
type IntrospectFormdataBody struct {
	// Token Access or refresh token to introspect
	Token string `form:"token" json:"token"`

	// TokenTypeHint Hint about token type to optimize lookup
	TokenTypeHint *IntrospectFormdataBodyTokenTypeHint `form:"token_type_hint,omitempty" json:"token_type_hint,omitempty"`
}

// IntrospectFormdataBodyTokenTypeHint defines parameters for Introspect.
type IntrospectFormdataBodyTokenTypeHint string

// RevokeFormdataBody defines parameters for Revoke.
type RevokeFormdataBody struct {
	// Token Access or refresh token to revoke
	Token string `form:"token" json:"token"`

	// TokenTypeHint Hint about token type to optimize lookup
	TokenTypeHint *RevokeFormdataBodyTokenTypeHint `form:"token_type_hint,omitempty" json:"token_type_hint,omitempty"`
}

// RevokeFormdataBodyTokenTypeHint defines parameters for Revoke.
type RevokeFormdataBodyTokenTypeHint string

// TokenFormdataBody defines parameters for Token.
type TokenFormdataBody struct {
	// Code Authorization code (required for authorization_code grant)
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// CodeVerifier PKCE code verifier (required for authorization_code grant)
	CodeVerifier *string `form:"code_verifier,omitempty" json:"code_verifier,omitempty"`

	// GrantType OAuth 2.0 grant type
	GrantType TokenFormdataBodyGrantType `form:"grant_type" json:"grant_type"`

	// RedirectURI Client redirect URI (must match authorize request)
	RedirectURI *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`

	// RefreshToken Refresh token (required for refresh_token grant)
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`

	// Scope Space-delimited scope values (optional, for narrowing access)
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// TokenFormdataBodyGrantType defines parameters for Token.
type TokenFormdataBodyGrantType string

// AuthorizeFormdataRequestBody defines body for Authorize for application/x-www-form-urlencoded ContentType.
type AuthorizeFormdataRequestBody AuthorizeFormdataBody

// IntrospectFormdataRequestBody defines body for Introspect for application/x-www-form-urlencoded ContentType.
type IntrospectFormdataRequestBody IntrospectFormdataBody

// RevokeFormdataRequestBody defines body for Revoke for application/x-www-form-urlencoded ContentType.
type RevokeFormdataRequestBody RevokeFormdataBody

// TokenFormdataRequestBody defines body for Token for application/x-www-form-urlencoded ContentType.
type TokenFormdataRequestBody TokenFormdataBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AuthorizeGET request
	AuthorizeGET(ctx context.Context, params *AuthorizeGETParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AuthorizeWithBody request with any body
	AuthorizeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AuthorizeWithFormdataBody(ctx context.Context, body AuthorizeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IntrospectWithBody request with any body
	IntrospectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	IntrospectWithFormdataBody(ctx context.Context, body IntrospectFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeWithBody request with any body
	RevokeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RevokeWithFormdataBody(ctx context.Context, body RevokeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TokenWithBody request with any body
	TokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TokenWithFormdataBody(ctx context.Context, body TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthorizeGET(ctx context.Context, params *AuthorizeGETParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeGETRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthorizeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthorizeWithFormdataBody(ctx context.Context, body AuthorizeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthorizeRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IntrospectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIntrospectRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IntrospectWithFormdataBody(ctx context.Context, body IntrospectFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIntrospectRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeWithFormdataBody(ctx context.Context, body RevokeFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TokenWithFormdataBody(ctx context.Context, body TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTokenRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAuthorizeGETRequest generates requests for AuthorizeGET
func NewAuthorizeGETRequest(server string, params *AuthorizeGETParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth2/v1/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "response_type", runtime.ParamLocationQuery, params.ResponseType); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "client_id", runtime.ParamLocationQuery, params.ClientID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "redirect_uri", runtime.ParamLocationQuery, params.RedirectURI); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Scope != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "scope", runtime.ParamLocationQuery, *params.Scope); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, *params.State); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "code_challenge", runtime.ParamLocationQuery, params.CodeChallenge); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "code_challenge_method", runtime.ParamLocationQuery, params.CodeChallengeMethod); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAuthorizeRequestWithFormdataBody calls the generic Authorize builder with application/x-www-form-urlencoded body
func NewAuthorizeRequestWithFormdataBody(server string, body AuthorizeFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewAuthorizeRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewAuthorizeRequestWithBody generates requests for Authorize with any type of body
func NewAuthorizeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth2/v1/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewIntrospectRequestWithFormdataBody calls the generic Introspect builder with application/x-www-form-urlencoded body
func NewIntrospectRequestWithFormdataBody(server string, body IntrospectFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewIntrospectRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewIntrospectRequestWithBody generates requests for Introspect with any type of body
func NewIntrospectRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth2/v1/introspect")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeRequestWithFormdataBody calls the generic Revoke builder with application/x-www-form-urlencoded body
func NewRevokeRequestWithFormdataBody(server string, body RevokeFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewRevokeRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewRevokeRequestWithBody generates requests for Revoke with any type of body
func NewRevokeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth2/v1/revoke")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTokenRequestWithFormdataBody calls the generic Token builder with application/x-www-form-urlencoded body
func NewTokenRequestWithFormdataBody(server string, body TokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewTokenRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewTokenRequestWithBody generates requests for Token with any type of body
func NewTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth2/v1/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error)

	// AuthorizeGETWithResponse request
	AuthorizeGETWithResponse(ctx context.Context, params *AuthorizeGETParams, reqEditors ...RequestEditorFn) (*AuthorizeGETResponse, error)

	// AuthorizeWithBodyWithResponse request with any body
	AuthorizeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error)

	AuthorizeWithFormdataBodyWithResponse(ctx context.Context, body AuthorizeFormdataRequestBody, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error)

	// IntrospectWithBodyWithResponse request with any body
	IntrospectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IntrospectResponse, error)

	IntrospectWithFormdataBodyWithResponse(ctx context.Context, body IntrospectFormdataRequestBody, reqEditors ...RequestEditorFn) (*IntrospectResponse, error)

	// RevokeWithBodyWithResponse request with any body
	RevokeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RevokeResponse, error)

	RevokeWithFormdataBodyWithResponse(ctx context.Context, body RevokeFormdataRequestBody, reqEditors ...RequestEditorFn) (*RevokeResponse, error)

	// TokenWithBodyWithResponse request with any body
	TokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TokenResponse, error)

	TokenWithFormdataBodyWithResponse(ctx context.Context, body TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*TokenResponse, error)
}

type HealthCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AuthorizeGETResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *OAuth2Error
	JSON401      *OAuth2Error
}

// Status returns HTTPResponse.Status
func (r AuthorizeGETResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthorizeGETResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AuthorizeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *OAuth2Error
	JSON401      *OAuth2Error
}

// Status returns HTTPResponse.Status
func (r AuthorizeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthorizeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type IntrospectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *IntrospectionResponse
	JSON401      *OAuth2Error
}

// Status returns HTTPResponse.Status
func (r IntrospectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IntrospectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Message *string `json:"message,omitempty"`
	}
	JSON401 *OAuth2Error
}

// Status returns HTTPResponse.Status
func (r RevokeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AuthZTokenResponse
	JSON400      *OAuth2Error
	JSON401      *OAuth2Error
}

// Status returns HTTPResponse.Status
func (r TokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// HealthCheckWithResponse request returning *HealthCheckResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckResponse(rsp)
}

// AuthorizeGETWithResponse request returning *AuthorizeGETResponse
func (c *ClientWithResponses) AuthorizeGETWithResponse(ctx context.Context, params *AuthorizeGETParams, reqEditors ...RequestEditorFn) (*AuthorizeGETResponse, error) {
	rsp, err := c.AuthorizeGET(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeGETResponse(rsp)
}

// AuthorizeWithBodyWithResponse request with arbitrary body returning *AuthorizeResponse
func (c *ClientWithResponses) AuthorizeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error) {
	rsp, err := c.AuthorizeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeResponse(rsp)
}

func (c *ClientWithResponses) AuthorizeWithFormdataBodyWithResponse(ctx context.Context, body AuthorizeFormdataRequestBody, reqEditors ...RequestEditorFn) (*AuthorizeResponse, error) {
	rsp, err := c.AuthorizeWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthorizeResponse(rsp)
}

// IntrospectWithBodyWithResponse request with arbitrary body returning *IntrospectResponse
func (c *ClientWithResponses) IntrospectWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IntrospectResponse, error) {
	rsp, err := c.IntrospectWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIntrospectResponse(rsp)
}

func (c *ClientWithResponses) IntrospectWithFormdataBodyWithResponse(ctx context.Context, body IntrospectFormdataRequestBody, reqEditors ...RequestEditorFn) (*IntrospectResponse, error) {
	rsp, err := c.IntrospectWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIntrospectResponse(rsp)
}

// RevokeWithBodyWithResponse request with arbitrary body returning *RevokeResponse
func (c *ClientWithResponses) RevokeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RevokeResponse, error) {
	rsp, err := c.RevokeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeResponse(rsp)
}

func (c *ClientWithResponses) RevokeWithFormdataBodyWithResponse(ctx context.Context, body RevokeFormdataRequestBody, reqEditors ...RequestEditorFn) (*RevokeResponse, error) {
	rsp, err := c.RevokeWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeResponse(rsp)
}

// TokenWithBodyWithResponse request with arbitrary body returning *TokenResponse
func (c *ClientWithResponses) TokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TokenResponse, error) {
	rsp, err := c.TokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTokenResponse(rsp)
}

func (c *ClientWithResponses) TokenWithFormdataBodyWithResponse(ctx context.Context, body TokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*TokenResponse, error) {
	rsp, err := c.TokenWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTokenResponse(rsp)
}

// ParseHealthCheckResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckResponse(rsp *http.Response) (*HealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseAuthorizeGETResponse parses an HTTP response from a AuthorizeGETWithResponse call
func ParseAuthorizeGETResponse(rsp *http.Response) (*AuthorizeGETResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthorizeGETResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseAuthorizeResponse parses an HTTP response from a AuthorizeWithResponse call
func ParseAuthorizeResponse(rsp *http.Response) (*AuthorizeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthorizeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseIntrospectResponse parses an HTTP response from a IntrospectWithResponse call
func ParseIntrospectResponse(rsp *http.Response) (*IntrospectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IntrospectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IntrospectionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseRevokeResponse parses an HTTP response from a RevokeWithResponse call
func ParseRevokeResponse(rsp *http.Response) (*RevokeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseTokenResponse parses an HTTP response from a TokenWithResponse call
func ParseTokenResponse(rsp *http.Response) (*TokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuthZTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest OAuth2Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbW/buJP/KoTuXriA7diOkyYGDndtmm6dbbfZJN0utg4MWhpbbCRSJSmn7iLf/TCk",
	"Hi3KSfqwu1j83zkSNRwOZ37zmyHzp+eLOBEcuFbe5E9PgkoEV2D+ePss1eHoVEoh8U9fcA1c40+aJBHz",
	"qWaC731UguMz5YcQU/z13xKW3sT7r71S9p59q/aqMu/u7rpeAMqXLEFR3sROSUb9AQEcQnJ9PByaycAp",
	"cNgfV+IG+EU+YvKnl0iRgNTMqk99H5SaaxyFf7fNZMcRM450REI/pUCEJGfvr554XQ8+0ziJwJvUBM6z",
	"x/PhaH98cPj06HjgdT29SXCg0pLxlXeHHydMgpozhwZGfRKxJWgWA2GcKPAFD1R10v3DwaCQy7iGFUgU",
	"zILWhSXApy/IieAcfE2mL4idqMOWRCTAWUCULxIgEj6loDQE9VXC5ixc/OSzt+zs8t2X6fAXNlVTfnHg",
	"n0wPpzfJ77+dnB33+33XaiUsJaiwTbML+7q0ND6nUZcshSQ01aGQ7ItxqrkvAiCUB6Qmkqwk5VrV9a2N",
	"KLZlcHz09PBgvD8auhQ1BmgqeJlQH3oBRCxmGgI7HWT2qm2Ll1kykWLJIiAQUxa5ZrJa2cduB8B3pEOj",
	"W7pRZOY9BypBzjyzSJ7G3uRD9sy7riqQPWtMabbhU8okBPhpLQhq6tSc87qQIxYfwdeo+iugkQ7b4yug",
	"mi6ocizsRfaG+NYJ2ZrpDVGa6lRVliVu8A8DBbWlmefNPbOfN/19DZJGEVEg18wHEhq1m7PZ5xuv66U8",
	"/12bthzQmDtNMEQdDpPNad+3hPDR4dgVw1sblenr2ogp11KoBA0pduKdZmuHku9D0CFIokPIQo8p4qdS",
	"AtfRhmSfVRTWMoVCjYUQEVCOetA0aEp/lgYMuA+kgyvjAWDM+ixhwHU9UEOtEzXZ26MJ62dP+76IXfb2",
	"I/x8zhzznZhXCGs6pDpb0C1VhCmVQkC0qE1qJQ1H+y3o3JzgFKPCoBDBTVWaxgnpvOPsM4FE+GFtUcOn",
	"+weHR8dtIE11U/7U6NlD3R8mfrA/ahGvVIt4STo1PDXBAbJlP1IdfrlvR3YipoKESopIGTGliVh+C2Kq",
	"dOGYJzXRQFgAXLMlM8hXyh4Mj/dHMA56mI17mI57x3Th9wJYDvIE/fXo/JVI3PVSBZJTF3C8y96grSQo",
	"kUofiLjlW+v6KEIeCHgAypsYdoHHFomrQwbkj3ezMMzGFSMwvqYRC+YZgfC6xRMbbZUHJoMayM39ESqj",
	"Uq7SJBFSQzYyz0z559brup5137lVt+tpiBMhqWTRZp5yuqYsoosI6tvS1LIZ/yhvXlv7tilepTHlPQk0",
	"wBkye1SHVKe8CgtWhRgbM6UYXxFK8r0iGCcxaLe7WHVSyRz+cjE1LCmbX/hpDFzThgZ5TAfCV9WQ3hNo",
	"/9Ge+V7tNW2zFDJGtPJw+vvcrcjZW96G0Qt+KpneXCJXt05mt/s5VcxHv9oF6cj4FPgSNFkzSl5dXZ0T",
	"8yHBLzH0bdHRn/FXQAOQxOo9Me8LuJtkHyEHORx3imwyyX7ZKZ7M0HamqDCJDj8pl46WLFPRpfniXCjd",
	"qj6taUhSs/W1CZEf5O6xEMGmP+O/CA0TgpT92fmU7PcHJFWgyMJACrG6mY3HdfZwPcHWRP0Zf+brlEaE",
	"4WYXbmEF1eenysgpvZAkIEke7cP+lkG2cM1aBDeZ8aXIK0LqG5NYOJ94FqD15v98uUm0SDWL+pHwKUK9",
	"hUJvmg0hV0Bjr7UEHBpv2KpmattMLg0sYEpZs4Dx1WTGe1tDTCGxjMQtuWU6JDHlAdVCbsj5zyenONzC",
	"PPAgEYxrY2v8Zi8rK/YyC/oSjNo0UlkVgh9bikz8EPybuoxYcKYFRo8xqmbaxGe5OOdKnp1Pva63Bqms",
	"LYb9QX+AJsLkSRPmTbz9/qCPZCahOjThtWd5K/5cgW7nqDVeTBj3oxRtRgIXWffMlJYGTQPEQfP1CS7U",
	"69bbBKPB4Lu1B7ZqDkeHIF8OUyQn7Hdd72Cw//foUNYSBv3SOKZyU9iL5AbTdKUQOe1j7xoH55i8Hu4V",
	"ybF1F6ecaUY1kEp4PNzRDUj4kGi19VWBBArB4VMKclN51p/x3zBPUF1ASZdICJgEX2Oi6poYxannfkij",
	"CPgK+jN+kQ1RRAsyDc5JJFaME7ZEUJKEixpaQtAlQuJQHw1uAyjG0bVB/Rm/ChnyfFPJKI0rlEGrQYpw",
	"TBE0F5tsAUYnpanURgxazOJe3d/z8ISfTq9MtOU28SYftvfmTYqADmTmoSVmXrOfUe5OvTixvIqhEGP7",
	"EiTzCMsZUZl+bXVWunLOyoywa0fqbrZhVkxpQDpSEj1rnDZ+fXAwgKPxYNCD0fGiNx4G4x59OjzsjceH",
	"hwcH4/FgMBi0LKQs5XYtoqQfqRl57yKypJs7I0GC1IlxI2Kq/ZDIcpFrGqXgLn2scjWi5NMoWlATtO59",
	"Kb3/gStyE6r7ek+2R2d0V6QD/VW/S2bOIirrFd1XaLlWU/DrQu179Xxr+6NGMePoJ5cXL3EybfsTNVU+",
	"b760zaypfuTMCGQ2kAqsIR1L8VIZ9YDju4Bcvno2OjgkIVUhVlcGnNYgjVPXDXV6/AaiUNDR29v1S3n6",
	"5upslZ68ogJ+HuqjdxfvF+lPZ5dK3/b8N23OXUO+nf4Q08+vga8wUQ9HR10vZjz/e7z/AP8oQeZydHA4",
	"80instD6unDAgxSex6BDETwIXoxQB7xcb7GB/cHI1fnNwrSWDzqtCeEJMTSskg062+ngSX/GX4uMbIe2",
	"GDB8lHFFNJUrQFB4bbOhBJ1KPk9lVOG+lupxzXiaM2mv61lRZim5eEc2LtaAU2zrunNaJw6xIKlXayzw",
	"kReYOf63FPM/rT2bCpnI1lSPrnvgCPnI2PI4FzUqdrh+foPfDB/5TY0ltdHhi6xK6ljaEz2pUKjiG+/6",
	"ruslzpLsm9nSX0p7qqKtPg5lHXSonbRkEQ1KPxfBZgcz/ty7vb3tmeIylVEGoXWqXO8Y7ejM/jhecQ87",
	"6G7j8OQfljoeh/3dFpSePD4lbGF3I0U4TvAq9Gbyd5Cu3UDV3SLGk2/l4lvkucHNv/bo8LvTN+d5GLiO",
	"fx/Nz3Y3+7YrkTqhr7HhBh1yO7KjcXi3TUHufhiteBDaNunGN5CD5ozF8bbZxErF/SB28AhW8O/hAi0M",
	"oN5HYcVJqclcTm6Qp/bseoGWDNZAYtA0oJpavDCH5nkL0J4xKpPgjYvmpGC7E0suzJao7Eg1b7XhPPaY",
	"0o8oi5Urc5dHvD8udbfcynhmr78YP63ez9CCsKpW3+WGSHngNg8Zd+zOK4Z2XYg0P9o11yO0ICLRLGZf",
	"gERC3KRJBbu3rjjUL6Fct13guRf3iu8fjVXfsyHqPvt39CRtH5tVhxMJKo006WT+KCRh3P5+UgnYv+Je",
	"l/uMZElZBEHt3Mi01xonRh+usSBuHsV8uMb6s8QQa4Sazchp3gfsXLw8IU8PD0dPHoQlEtbiBtpx5MK8",
	"z2+PbYdPn9wDFogma3GTnw9WI49GCosCFK8IjSJClRI+Mwfs1ctqTiSxav2TUETmGv0HQX4UgtS3KAal",
	"qC2DKmfTxhZ2LwKiUrOQZRpFG+c6HCq78AblZcFcirRlrfVkCTTYkOy8+d8MOhelJbYQZzA4fhjiFKHl",
	"BpzTz35IsXJt8tVuPepMYyGDnerBZcltMpCa8Ut7ASM71DSxoiaOy5jd+k3MLmmei9baJkXFXRTQbbc8",
	"7WmqC8quinj8Ma0MrPAc99maxUBxfWPXErbuCqc6NC8feFG4ZqpdDYzCnF+jVfD841KfwR/jk9/Oe/Hz",
	"49HPo6dpuHh39m6YDOX89v1w9fL9y7enH3+/+Yq2ReUKz44rRaWjVRG4oX4Dh4vKs+JyW+DsEvKdWxzF",
	"SW1+k+PH9Dgec4+65geO+9IPuS692zm/qudRv97NqZTi1rAdA0C7eh73JtaKo/3d/NzxjwiuCwNlbtRZ",
	"3swH/5W19ndJd2WdbhNfnu3aUtxdfn3PdXT+Wvg0Ii9gDZFIYoy8zuWvr5k2rcNURpWQMreIQqH05Ghw",
	"NPCaJ2QOWbiClYTLX1+TKVeach/I8B7Rw68XPbpH9Mgh+lyKIM07c/VvbTuncZHq7vru/wMAAP//Nfaf",
	"17czAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
