# Identity Services Docker Compose - Advanced Configuration

# CRITICAL: This file demonstrates advanced orchestration patterns (Nx/Mx/Xx scaling, profiles, secrets)
# for Identity Services (AuthZ, IdP, Resource Server, SPA Relying Party).
#
# KEY FEATURES:
# - Templated service definitions with scaling support (1x1x1x1, 2x2x2x2, etc.)
# - Docker Compose profiles (demo, development, CI, production-like)
# - Docker secrets integration (PostgreSQL credentials, service secrets)
# - Health checks with IPv4 loopback (127.0.0.1)
# - Relative paths for cross-platform compatibility
# - Resource limits for predictable scaling

# USAGE:
# Demo profile (1 instance of each service):
#   docker compose -f compose.advanced.yml --profile demo up -d
#
# Development profile (2 instances for high availability testing):
#   docker compose -f compose.advanced.yml --profile development up -d
#
# CI profile (minimal resources, single instance):
#   docker compose -f compose.advanced.yml --profile ci up -d
#
# Production-like profile (3 instances with load balancing):
#   docker compose -f compose.advanced.yml --profile production up -d
#
# Custom scaling (e.g., 2x AuthZ, 1x IdP, 1x RS, 1x SPA):
#   docker compose -f compose.advanced.yml --profile demo up -d --scale identity-authz=2

services:

  # PostgreSQL database for identity services (SHARED by all services)
  identity-postgres:
    image: postgres:18
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    environment:
      # Use Docker secrets for credentials (not environment variables)
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    shm_size: 256mb
    ports:
      - "5433:5432"  # Different port to avoid conflict with cryptoutil kms postgres
    volumes:
      - identity_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user) -d $(cat /run/secrets/postgres_db)"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - identity-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    profiles:
      - demo
      - development
      - ci
      - production

  # OAuth 2.1 Authorization Server (Scalable)
  identity-authz:
    build:
      context: ../..
      dockerfile: deployments/kms/Dockerfile.kms
      args:
        APP_VERSION: "dev"
        VCS_REF: "local"
        BUILD_DATE: "2025-01-10T00:00:00Z"
    image: cryptoutil-identity:dev
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    command:
      - identity
      - start
      - --service=authz
      - --port=8100
      - --bind=0.0.0.0
      - --db-url=postgres://$(cat /run/secrets/postgres_user):$(cat /run/secrets/postgres_password)@identity-postgres:5432/$(cat /run/secrets/postgres_db)?sslmode=disable
    ports:
      - "8100-8109:8100"  # Port range allows scaling (8100, 8101, 8102, etc.)
      # Admin API (9090) NOT exposed - internal container use only (per 02-03.https-ports.instructions.md)
    environment:
      - LOG_LEVEL=INFO
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    depends_on:
      identity-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "/dev/null", "https://127.0.0.1:9090/admin/api/v1/livez"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      replicas: 1  # Override with --scale identity-authz=N
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo
      - development
      - ci
      - production

  # OIDC Identity Provider (Scalable)
  identity-idp:
    image: cryptoutil-identity:dev
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    command:
      - identity
      - start
      - --service=idp
      - --port=8100
      - --bind=0.0.0.0
      - --db-url=postgres://$(cat /run/secrets/postgres_user):$(cat /run/secrets/postgres_password)@identity-postgres:5432/$(cat /run/secrets/postgres_db)?sslmode=disable
      - --authz-url=https://identity-authz:8100
    ports:
      - "8101-8109:8100"  # Port range for scaling (8101 to avoid conflict with authz)
      # Admin API (9090) NOT exposed - internal container use only (per 02-03.https-ports.instructions.md)
    environment:
      - LOG_LEVEL=INFO
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    depends_on:
      identity-postgres:
        condition: service_healthy
      identity-authz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "/dev/null", "https://127.0.0.1:9090/admin/api/v1/livez"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo
      - development
      - ci
      - production

  # Resource Server (Scalable)
  identity-rs:
    image: cryptoutil-identity:dev
    command:
      - identity
      - start
      - --service=rs
      - --port=8110
      - --bind=0.0.0.0
      - --authz-url=https://identity-authz:8100
    ports:
      - "8110-8119:8110"  # Port range for scaling
      # Admin API (9090) NOT exposed - internal container use only (per 02-03.https-ports.instructions.md)
    environment:
      - LOG_LEVEL=INFO
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    depends_on:
      identity-authz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "/dev/null", "https://127.0.0.1:9090/admin/api/v1/livez"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo
      - development
      - ci
      - production

  # SPA Relying Party Application (Scalable)
  identity-spa-rp:
    image: cryptoutil-identity:dev
    command:
      - identity
      - start
      - --service=spa-rp
      - --port=8120
      - --bind=0.0.0.0
      - --authz-url=https://identity-authz:8100
      - --idp-url=https://identity-idp:8100
    ports:
      - "8120-8129:8120"  # Port range for scaling
      # Admin API (9090) NOT exposed - internal container use only (per 02-03.https-ports.instructions.md)
    environment:
      - LOG_LEVEL=INFO
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    depends_on:
      identity-authz:
        condition: service_healthy
      identity-idp:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "/dev/null", "https://127.0.0.1:9090/admin/api/v1/livez"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo
      - development
      - ci
      - production

# Docker secrets for PostgreSQL credentials
secrets:
  postgres_user:
    file: ./postgres/postgres_username.secret
  postgres_password:
    file: ./postgres/postgres_password.secret
  postgres_db:
    file: ./postgres/postgres_database.secret

networks:
  identity-network:
    driver: bridge

volumes:
  identity_postgres_data:
    name: identity-postgres-volume
