# Identity Demo Compose Configuration
#
# Usage: docker compose -f deployments/identity/compose.demo.yml up -d
#
# This configuration is for demonstration purposes only.
# It includes SQLite backend with demo data auto-seeding.
#
# Demo credentials (WARNING: Never use in production):
# - demo-client / demo-secret (OAuth client)
# - demo-user / demo-password (User login)
#
# Demo endpoints:
# - AuthZ Server: https://localhost:8082
# - Token Endpoint: https://localhost:8082/oauth2/token
# - JWKS Endpoint: https://localhost:8082/.well-known/jwks.json
# - Grafana: http://localhost:3000 (admin/admin)

name: cryptoutil-identity-demo

include:
  - path: ../telemetry/compose.yml

services:
  # Identity AuthZ Demo Server (SQLite backend with demo seeding).
  identity-authz-demo:
    build:
      context: ../..
      dockerfile: deployments/identity/Dockerfile.authz
    image: cryptoutil-identity-authz:demo
    container_name: identity-authz-demo
    hostname: identity-authz-demo
    command:
      - --config=/etc/identity/authz.yml
      - --demo
    ports:
      - "8082:8082"  # AuthZ API (HTTPS)
    volumes:
      - ./config/authz.yml:/etc/identity/authz.yml:ro
      - ./config/demo-seed.yml:/etc/identity/demo-seed.yml:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
      - OTEL_SERVICE_NAME=identity-authz-demo
      - OTEL_RESOURCE_ATTRIBUTES=service.version=demo,deployment.environment=demo
    healthcheck:
      test:
        - CMD
        - wget
        - --no-check-certificate
        - -q
        - -O
        - /dev/null
        - https://127.0.0.1:8082/healthz
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      opentelemetry-collector-contrib:
        condition: service_started
    networks:
      - cryptoutil-network
      - telemetry-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo

  # Identity IdP Demo Server (SQLite backend with demo seeding).
  identity-idp-demo:
    build:
      context: ../..
      dockerfile: deployments/identity/Dockerfile.idp
    image: cryptoutil-identity-idp:demo
    container_name: identity-idp-demo
    hostname: identity-idp-demo
    command:
      - --config=/etc/identity/idp.yml
      - --demo
    ports:
      - "8083:8083"  # IdP API (HTTPS)
    volumes:
      - ./config/idp.yml:/etc/identity/idp.yml:ro
      - ./config/demo-seed.yml:/etc/identity/demo-seed.yml:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
      - OTEL_SERVICE_NAME=identity-idp-demo
      - OTEL_RESOURCE_ATTRIBUTES=service.version=demo,deployment.environment=demo
    healthcheck:
      test:
        - CMD
        - wget
        - --no-check-certificate
        - -q
        - -O
        - /dev/null
        - https://127.0.0.1:8083/healthz
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      opentelemetry-collector-contrib:
        condition: service_started
    networks:
      - cryptoutil-network
      - telemetry-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo

  # Identity RS Demo Server (SQLite backend with demo seeding).
  identity-rs-demo:
    build:
      context: ../..
      dockerfile: deployments/identity/Dockerfile.rs
    image: cryptoutil-identity-rs:demo
    container_name: identity-rs-demo
    hostname: identity-rs-demo
    command:
      - --config=/etc/identity/rs.yml
      - --demo
    ports:
      - "8084:8084"  # RS API (HTTPS)
    volumes:
      - ./config/rs.yml:/etc/identity/rs.yml:ro
      - ./config/demo-seed.yml:/etc/identity/demo-seed.yml:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
      - OTEL_SERVICE_NAME=identity-rs-demo
      - OTEL_RESOURCE_ATTRIBUTES=service.version=demo,deployment.environment=demo
    healthcheck:
      test:
        - CMD
        - wget
        - --no-check-certificate
        - -q
        - -O
        - /dev/null
        - https://127.0.0.1:8084/healthz
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      opentelemetry-collector-contrib:
        condition: service_started
    networks:
      - cryptoutil-network
      - telemetry-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    profiles:
      - demo

networks:
  cryptoutil-network:
    driver: bridge
