services:

  cryptoutil_sqlite:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    # Using shell form of command
    entrypoint: ["/sbin/tini", "--"]
    command: /app/cryptoutil --config=/app/sqlite.yaml
    ports:
      - "8090:8080"
    volumes:
      - ./cryptoutil/sqlite.yaml:/app/sqlite.yaml:ro

  cryptoutil_postgres:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    # Using shell form of command to allow for command substitution
    entrypoint: ["/sbin/tini", "--"]
    command: sh -c '/app/cryptoutil --config=/app/postgresql.yaml --database-url="$$(cat /run/secrets/cryptoutil_database-url)"'
    ports:
      - "8080-8089:8080"
    volumes:
      - ./cryptoutil/postgresql.yaml:/app/postgresql.yaml:ro
    secrets:
      - cryptoutil_database-url
      - cryptoutil_unseal_1of5
      - cryptoutil_unseal_2of5
      - cryptoutil_unseal_3of5
      - cryptoutil_unseal_4of5
      - cryptoutil_unseal_5of5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cryptoutil-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_database
    secrets:
      - postgres_username
      - postgres_password
      - postgres_database
    shm_size: 256mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_username) -d $$(cat /run/secrets/postgres_database)"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - cryptoutil-network

networks:
  cryptoutil-network:
    driver: bridge

volumes:
 postgres_data:
   name: cryptoutil_postgres_volume

secrets:

  postgres_username:
    file: ./postgres/postgres_username
  postgres_password:
    file: ./postgres/postgres_password
  postgres_database:
    file: ./postgres/postgres_database

  cryptoutil_database-url:
    file: ./cryptoutil/cryptoutil_database-url

  cryptoutil_unseal_1of5:
    file: ./cryptoutil/cryptoutil_unseal_1of5
  cryptoutil_unseal_2of5:
    file: ./cryptoutil/cryptoutil_unseal_2of5
  cryptoutil_unseal_3of5:
    file: ./cryptoutil/cryptoutil_unseal_3of5
  cryptoutil_unseal_4of5:
    file: ./cryptoutil/cryptoutil_unseal_4of5
  cryptoutil_unseal_5of5:
    file: ./cryptoutil/cryptoutil_unseal_5of5