# sm-kms PostgreSQL Instance 2 Configuration
# Settings UNIQUE to the 'sm-kms-app-postgresql-2' compose service.

cors-origins:
  - "https://localhost:8003"
  - "https://127.0.0.1:8003"
  - "https://[::1]:8003"

otlp-service: sm-kms-postgresql-2
otlp-hostname: sm-kms-postgresql-2
