# $schema: https://json.schemastore.org/github-action.json
# Doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: 'workflow-end-summary'
description: 'Add a standardized summary to GitHub Actions workflow runs'

inputs:
  job-name:
    description: 'Name of the job (e.g., "e2e", "coverage", "gitleaks")'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Workflow end summary
      shell: bash
      run: |
        # Derive operation name from job name (capitalize first letter)
        OPERATION_NAME="$(echo ${{ inputs.job-name }} | sed 's/.*/\u&/')"

        echo "## $OPERATION_NAME Results" >> $GITHUB_STEP_SUMMARY
        START_TIME=$(date +%s)
        echo "📅 Start: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ ${{ inputs.job-name }} completed successfully." >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ ${{ inputs.job-name }} failed." >> $GITHUB_STEP_SUMMARY
        fi
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "📅 End: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        echo "⏱️ $OPERATION_NAME summary completed in: ${DURATION}s"
