# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: model
output: model/openapi_gen_model.go
generate:
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
  name-normalizer: ToCamelCaseWithInitialisms
  additional-initialisms:
    - IDS
    - JWT
    - JWK
    - JWE
    - JWS
    - OIDC
    - SAML
    - AES
    - GCM
    - CBC
    - RSA
    - EC
    - HMAC
    - SHA
    - TLS
    - IP
    - AI
    - ML
    - KEM
    - PEM
    - DER
    - DSA
    - IKM
