# $schema: https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:

  # PostgreSQL database for identity services
  identity-postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass # pragma: allowlist secret
      POSTGRES_DB: identity_db
    shm_size: 256mb
    ports:
      - "5433:5432"  # Different port to avoid conflict with cryptoutil postgres
    volumes:
      - identity_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user -d identity_db"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - identity-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # OAuth 2.1 Authorization Server
  identity-authz:
    build:
      context: ../..
      dockerfile: deployments/Dockerfile
      args:
        APP_VERSION: "dev"
        VCS_REF: "local"
        BUILD_DATE: "2025-11-07T00:00:00Z"
    image: cryptoutil-identity:dev
    command: ["identity", "authz"]
    ports:
      - "8090:8080"  # OAuth 2.1 authorization endpoints
      - "9080:9090"  # Admin API (health, metrics)
    environment:
      - IDENTITY_DB_DSN=postgres://identity_user:identity_pass@identity-postgres:5432/identity_db?sslmode=disable
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    volumes:
      - ../../configs/identity/authz-docker.yml:/app/run/authz-docker.yml:ro
    depends_on:
      identity-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # OIDC Identity Provider
  identity-idp:
    image: cryptoutil-identity:dev
    command: ["identity", "idp", "--config=/app/config/idp-docker.yml"]
    ports:
      - "8091:8081"  # OIDC identity provider endpoints (using 8091 to avoid conflict with KMS)
      - "9091:9090"  # Admin API (health, metrics)
    environment:
      - IDENTITY_DB_DSN=postgres://identity_user:identity_pass@identity-postgres:5432/identity_db?sslmode=disable
      - AUTHZ_URL=http://identity-authz:8080
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    volumes:
      - ../../configs/identity/idp-docker.yml:/app/config/idp-docker.yml:ro
    depends_on:
      identity-postgres:
        condition: service_healthy
      identity-authz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8081/health"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Resource Server
  identity-rs:
    image: cryptoutil-identity:dev
    command: ["identity", "rs", "--config=/app/config/rs-docker.yml"]
    ports:
      - "8082:8082"  # Resource server API endpoints
      - "9082:9090"  # Admin API (health, metrics)
    environment:
      - AUTHZ_URL=http://identity-authz:8080
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    volumes:
      - ../../configs/identity/rs-docker.yml:/app/config/rs-docker.yml:ro
    depends_on:
      identity-authz:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8082/health"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # SPA Relying Party Application
  identity-spa-rp:
    image: cryptoutil-identity:dev
    command: ["identity", "spa-rp", "start", "--port=8083", "--bind=0.0.0.0", "--authz-url=https://identity-authz:8080", "--idp-url=https://identity-idp:8081"]
    ports:
      - "8083:8083"  # SPA application
      - "9083:9090"  # Admin API (health, metrics)
    environment:
      - LOG_LEVEL=INFO
      - OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
    depends_on:
      identity-authz:
        condition: service_healthy
      identity-idp:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8083/health"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - identity-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  identity-network:
    driver: bridge

volumes:
  identity_postgres_data:
    name: identity-postgres-volume
