// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package model

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for KeyPoolAlgorithm.
const (
	A128CBCHS256A128GCMKW KeyPoolAlgorithm = "A128CBC-HS256/A128GCMKW"
	A128CBCHS256A128KW    KeyPoolAlgorithm = "A128CBC-HS256/A128KW"
	A128CBCHS256A192GCMKW KeyPoolAlgorithm = "A128CBC-HS256/A192GCMKW"
	A128CBCHS256A192KW    KeyPoolAlgorithm = "A128CBC-HS256/A192KW"
	A128CBCHS256A256GCMKW KeyPoolAlgorithm = "A128CBC-HS256/A256GCMKW"
	A128CBCHS256A256KW    KeyPoolAlgorithm = "A128CBC-HS256/A256KW"
	A128CBCHS256dir       KeyPoolAlgorithm = "A128CBC-HS256/dir"
	A128GCMA128GCMKW      KeyPoolAlgorithm = "A128GCM/A128GCMKW"
	A128GCMA128KW         KeyPoolAlgorithm = "A128GCM/A128KW"
	A128GCMA192GCMKW      KeyPoolAlgorithm = "A128GCM/A192GCMKW"
	A128GCMA192KW         KeyPoolAlgorithm = "A128GCM/A192KW"
	A128GCMA256GCMKW      KeyPoolAlgorithm = "A128GCM/A256GCMKW"
	A128GCMA256KW         KeyPoolAlgorithm = "A128GCM/A256KW"
	A128GCMdir            KeyPoolAlgorithm = "A128GCM/dir"
	A192CBCHS384A192GCMKW KeyPoolAlgorithm = "A192CBC-HS384/A192GCMKW"
	A192CBCHS384A192KW    KeyPoolAlgorithm = "A192CBC-HS384/A192KW"
	A192CBCHS384A256GCMKW KeyPoolAlgorithm = "A192CBC-HS384/A256GCMKW"
	A192CBCHS384A256KW    KeyPoolAlgorithm = "A192CBC-HS384/A256KW"
	A192CBCHS384dir       KeyPoolAlgorithm = "A192CBC-HS384/dir"
	A192GCMA192GCMKW      KeyPoolAlgorithm = "A192GCM/A192GCMKW"
	A192GCMA192KW         KeyPoolAlgorithm = "A192GCM/A192KW"
	A192GCMA256GCMKW      KeyPoolAlgorithm = "A192GCM/A256GCMKW"
	A192GCMA256KW         KeyPoolAlgorithm = "A192GCM/A256KW"
	A192GCMdir            KeyPoolAlgorithm = "A192GCM/dir"
	A256CBCHS512A256GCMKW KeyPoolAlgorithm = "A256CBC-HS512/A256GCMKW"
	A256CBCHS512A256KW    KeyPoolAlgorithm = "A256CBC-HS512/A256KW"
	A256CBCHS512dir       KeyPoolAlgorithm = "A256CBC-HS512/dir"
	A256GCMA256GCMKW      KeyPoolAlgorithm = "A256GCM/A256GCMKW"
	A256GCMA256KW         KeyPoolAlgorithm = "A256GCM/A256KW"
	A256GCMdir            KeyPoolAlgorithm = "A256GCM/dir"
)

// Defines values for KeyPoolProvider.
const (
	Internal KeyPoolProvider = "Internal"
)

// Defines values for KeyPoolSort.
const (
	KeyPoolSortAlgorithmASC          KeyPoolSort = "algorithm:ASC"
	KeyPoolSortAlgorithmDESC         KeyPoolSort = "algorithm:DESC"
	KeyPoolSortExportAllowedASC      KeyPoolSort = "export_allowed:ASC"
	KeyPoolSortExportAllowedDESC     KeyPoolSort = "export_allowed:DESC"
	KeyPoolSortIdASC                 KeyPoolSort = "id:ASC"
	KeyPoolSortIdDESC                KeyPoolSort = "id:DESC"
	KeyPoolSortImportAllowedASC      KeyPoolSort = "import_allowed:ASC"
	KeyPoolSortImportAllowedDESC     KeyPoolSort = "import_allowed:DESC"
	KeyPoolSortNameASC               KeyPoolSort = "name:ASC"
	KeyPoolSortNameDESC              KeyPoolSort = "name:DESC"
	KeyPoolSortProviderASC           KeyPoolSort = "provider:ASC"
	KeyPoolSortProviderDESC          KeyPoolSort = "provider:DESC"
	KeyPoolSortStatusASC             KeyPoolSort = "status:ASC"
	KeyPoolSortStatusDESC            KeyPoolSort = "status:DESC"
	KeyPoolSortVersioningAllowedASC  KeyPoolSort = "versioning_allowed:ASC"
	KeyPoolSortVersioningAllowedDESC KeyPoolSort = "versioning_allowed:DESC"
)

// Defines values for KeyPoolStatus.
const (
	Active                         KeyPoolStatus = "active"
	Creating                       KeyPoolStatus = "creating"
	Disabled                       KeyPoolStatus = "disabled"
	FinishedDelete                 KeyPoolStatus = "finished_delete"
	GenerateFailed                 KeyPoolStatus = "generate_failed"
	ImportFailed                   KeyPoolStatus = "import_failed"
	PendingDeleteWasActive         KeyPoolStatus = "pending_delete_was_active"
	PendingDeleteWasDisabled       KeyPoolStatus = "pending_delete_was_disabled"
	PendingDeleteWasGenerateFailed KeyPoolStatus = "pending_delete_was_generate_failed"
	PendingDeleteWasImportFailed   KeyPoolStatus = "pending_delete_was_import_failed"
	PendingDeleteWasPendingImport  KeyPoolStatus = "pending_delete_was_pending_import"
	PendingGenerate                KeyPoolStatus = "pending_generate"
	PendingImport                  KeyPoolStatus = "pending_import"
	StartedDelete                  KeyPoolStatus = "started_delete"
)

// Defines values for KeySort.
const (
	KeySortGenerateDate     KeySort = "generate_date"
	KeySortGenerateDateASC  KeySort = "generate_date:ASC"
	KeySortGenerateDateDESC KeySort = "generate_date:DESC"
	KeySortId               KeySort = "id"
	KeySortIdASC            KeySort = "id:ASC"
	KeySortIdDESC           KeySort = "id:DESC"
	KeySortPool             KeySort = "pool"
	KeySortPoolASC          KeySort = "pool:ASC"
	KeySortPoolDESC         KeySort = "pool:DESC"
)

// DecryptRequest Base64Url-encoded JSON Web Encryption (JWE) of the encrypted bytes (and non-secret cipher parameters) in compact serialized format. See RFC 7516 JSON Web Encryption (JWE) for more details. Compact serialized format is 'Header.EncryptedKey.IV.Ciphertext.AuthenticationTag'. There are five Base64Url-encoded parts and separated by '.'. Some parts can be empty depending on the 'alg' and 'enc' headers parameters. - Header: Required base64Url-encoded JSON key/values for the JWE. - EncryptedKey: Optional base64Url-encoded JWE of an encrypted symmetric key used to encrypt the payload. This is non-empty for envelope encryption (e.g. alg=a256gcmkw), or empty for direct encryption (e.g. alg=dir). - IV: Required base64Url-encoded Initialization Vector (IV) used for encryption. For AES-GCM or AES-GCM-SIV it contains a 12-bytes nonce. For AES-CBC it contains a 16-bytes IV. - Ciphertext: Required base64Url-encoded encrypted secret bytes. It is always non-empty. For AES-GCM or AES-GCM-SIV it contains same number of bytes as the plaintext. - AuthenticationTag: Required base64Url-encoded authentication tag used for encryption. For AES-GCM or AES-GCM-SIV it contains a 16-bytes authentication tag. For AES-CBC-HMAC it contains a N-bytes HMAC hash.
type DecryptRequest = string

// DecryptResponse Encrypted text to be decrypted. If you pre-encoded bytes to text before submitting them for encryption, remember to decode to bytes; ese the same encoding scheme you chose before submission (e.g. Hexadecimal, Base64, Base64-URL, Base64-MIME, etc).
type DecryptResponse = string

// EncryptRequest Clear text to be encrypted. If you need to encrypt bytes, encode them first as text (e.g. Hexadecimal, Base64, Base64-URL, Base64-MIME, etc).
type EncryptRequest = string

// EncryptResponse Base64Url-encoded JSON Web Encryption (JWE) of the encrypted bytes (and non-secret cipher parameters) in compact serialized format. See RFC 7516 JSON Web Encryption (JWE) for more details. Compact serialized format is 'Header.EncryptedKey.IV.Ciphertext.AuthenticationTag'. There are five Base64Url-encoded parts and separated by '.'. Some parts can be empty depending on the 'alg' and 'enc' headers parameters. - Header: Required base64Url-encoded JSON key/values for the JWE. - EncryptedKey: Optional base64Url-encoded JWE of an encrypted symmetric key used to encrypt the payload. This is non-empty for envelope encryption (e.g. alg=a256gcmkw), or empty for direct encryption (e.g. alg=dir). - IV: Required base64Url-encoded Initialization Vector (IV) used for encryption. For AES-GCM or AES-GCM-SIV it contains a 12-bytes nonce. For AES-CBC it contains a 16-bytes IV. - Ciphertext: Required base64Url-encoded encrypted secret bytes. It is always non-empty. For AES-GCM or AES-GCM-SIV it contains same number of bytes as the plaintext. - AuthenticationTag: Required base64Url-encoded authentication tag used for encryption. For AES-GCM or AES-GCM-SIV it contains a 16-bytes authentication tag. For AES-CBC-HMAC it contains a N-bytes HMAC hash.
type EncryptResponse = string

// HTTPError defines model for HTTPError.
type HTTPError struct {
	// Error HTTP status message
	Error string `json:"error"`

	// Message Detailed error message
	Message string `json:"message"`

	// Status HTTP status code
	Status int `json:"status"`
}

// Key defines model for Key.
type Key struct {
	// GenerateDate ISO 8601 UTC timestamp of Key generation.
	GenerateDate *KeyGenerateDate `json:"generate_date,omitempty"`

	// Id Unique UUID for a Key.
	Id *KeyId `json:"id,omitempty"`

	// Pool Unique UUID for a Key Pool.
	Pool *KeyPoolId `json:"pool,omitempty"`
}

// KeyGenerate defines model for KeyGenerate.
type KeyGenerate = map[string]interface{}

// KeyGenerateDate ISO 8601 UTC timestamp of Key generation.
type KeyGenerateDate = time.Time

// KeyId Unique UUID for a Key.
type KeyId = openapi_types.UUID

// KeyPool defines model for KeyPool.
type KeyPool struct {
	// Algorithm Cryptographic algorithm(s) used for Keys in the Key Pool. The first is the content encryption algorithm, and the second is the optional key encryption algorithm. If key encryption algorithm is 'dir', the Key Pool Key is directly used on values. direct encryption is useful for small values. If key encryption algorithm is 'K*W', a random Content Encryption Key (CEK) is used directly on values, and the Key Pool Key is used to encrypt the CEK. Key wrap is useful for large values (e.g. files, blobs, etc). If in doubt, it is safe to use 'A256GCM/A256KW' for all values; it is the default.
	Algorithm *KeyPoolAlgorithm `json:"algorithm,omitempty"`

	// Description Description for a Key Pool.
	Description *KeyPoolDescription `json:"description,omitempty"`

	// ExportAllowed Indicates if the Key Pool supports export.
	ExportAllowed *KeyPoolExportAllowed `json:"export_allowed,omitempty"`

	// Id Unique UUID for a Key Pool.
	Id *KeyPoolId `json:"id,omitempty"`

	// ImportAllowed Indicates if the Key Pool supports import (BYOK).
	ImportAllowed *KeyPoolImportAllowed `json:"import_allowed,omitempty"`

	// Name Friendly name for a Key Pool.
	Name *KeyPoolName `json:"name,omitempty"`

	// Provider Provider of the Key Pool management service.
	Provider *KeyPoolProvider `json:"provider,omitempty"`

	// Status Status of the Key Pool.
	Status *KeyPoolStatus `json:"status,omitempty"`

	// VersioningAllowed Indicates if the Key Pool supports versioning.
	VersioningAllowed *KeyPoolVersioningAllowed `json:"versioning_allowed,omitempty"`
}

// KeyPoolAlgorithm Cryptographic algorithm(s) used for Keys in the Key Pool. The first is the content encryption algorithm, and the second is the optional key encryption algorithm. If key encryption algorithm is 'dir', the Key Pool Key is directly used on values. direct encryption is useful for small values. If key encryption algorithm is 'K*W', a random Content Encryption Key (CEK) is used directly on values, and the Key Pool Key is used to encrypt the CEK. Key wrap is useful for large values (e.g. files, blobs, etc). If in doubt, it is safe to use 'A256GCM/A256KW' for all values; it is the default.
type KeyPoolAlgorithm string

// KeyPoolCreate defines model for KeyPoolCreate.
type KeyPoolCreate struct {
	// Algorithm Cryptographic algorithm(s) used for Keys in the Key Pool. The first is the content encryption algorithm, and the second is the optional key encryption algorithm. If key encryption algorithm is 'dir', the Key Pool Key is directly used on values. direct encryption is useful for small values. If key encryption algorithm is 'K*W', a random Content Encryption Key (CEK) is used directly on values, and the Key Pool Key is used to encrypt the CEK. Key wrap is useful for large values (e.g. files, blobs, etc). If in doubt, it is safe to use 'A256GCM/A256KW' for all values; it is the default.
	Algorithm *KeyPoolAlgorithm `json:"algorithm,omitempty"`

	// Description Description for a Key Pool.
	Description KeyPoolDescription `json:"description"`

	// ExportAllowed Indicates if the Key Pool supports export.
	ExportAllowed *KeyPoolExportAllowed `json:"export_allowed,omitempty"`

	// ImportAllowed Indicates if the Key Pool supports import (BYOK).
	ImportAllowed *KeyPoolImportAllowed `json:"import_allowed,omitempty"`

	// Name Friendly name for a Key Pool.
	Name KeyPoolName `json:"name"`

	// Provider Provider of the Key Pool management service.
	Provider *KeyPoolProvider `json:"provider,omitempty"`

	// VersioningAllowed Indicates if the Key Pool supports versioning.
	VersioningAllowed *KeyPoolVersioningAllowed `json:"versioning_allowed,omitempty"`
}

// KeyPoolDescription Description for a Key Pool.
type KeyPoolDescription = string

// KeyPoolExportAllowed Indicates if the Key Pool supports export.
type KeyPoolExportAllowed = bool

// KeyPoolId Unique UUID for a Key Pool.
type KeyPoolId = openapi_types.UUID

// KeyPoolImportAllowed Indicates if the Key Pool supports import (BYOK).
type KeyPoolImportAllowed = bool

// KeyPoolKeysQueryParams defines model for KeyPoolKeysQueryParams.
type KeyPoolKeysQueryParams struct {
	Id *[]KeyId `json:"id,omitempty"`

	// MaxGenerateDate ISO 8601 UTC timestamp of Key generation.
	MaxGenerateDate *KeyGenerateDate `json:"max_generate_date,omitempty"`

	// MinGenerateDate ISO 8601 UTC timestamp of Key generation.
	MinGenerateDate *KeyGenerateDate `json:"min_generate_date,omitempty"`

	// Page Page number starting at 0.
	Page *PageNumber `json:"page,omitempty"`

	// Size Page number.
	Size *PageSize  `json:"size,omitempty"`
	Sort *[]KeySort `json:"sort,omitempty"`
}

// KeyPoolName Friendly name for a Key Pool.
type KeyPoolName = string

// KeyPoolProvider Provider of the Key Pool management service.
type KeyPoolProvider string

// KeyPoolSort defines model for KeyPoolSort.
type KeyPoolSort string

// KeyPoolStatus Status of the Key Pool.
type KeyPoolStatus string

// KeyPoolUpdate defines model for KeyPoolUpdate.
type KeyPoolUpdate struct {
	// Description Description for a Key Pool.
	Description KeyPoolDescription `json:"description"`

	// Name Friendly name for a Key Pool.
	Name KeyPoolName `json:"name"`
}

// KeyPoolVersioningAllowed Indicates if the Key Pool supports versioning.
type KeyPoolVersioningAllowed = bool

// KeyPoolsQueryParams defines model for KeyPoolsQueryParams.
type KeyPoolsQueryParams struct {
	Algorithm *[]KeyPoolAlgorithm `json:"algorithm,omitempty"`

	// ExportAllowed Indicates if the Key Pool supports export.
	ExportAllowed *KeyPoolExportAllowed `json:"export_allowed,omitempty"`
	Id            *[]KeyPoolId          `json:"id,omitempty"`

	// ImportAllowed Indicates if the Key Pool supports import (BYOK).
	ImportAllowed *KeyPoolImportAllowed `json:"import_allowed,omitempty"`
	Name          *[]KeyPoolName        `json:"name,omitempty"`

	// Page Page number starting at 0.
	Page     *PageNumber        `json:"page,omitempty"`
	Provider *[]KeyPoolProvider `json:"provider,omitempty"`

	// Size Page number.
	Size   *PageSize        `json:"size,omitempty"`
	Sort   *[]KeyPoolSort   `json:"sort,omitempty"`
	Status *[]KeyPoolStatus `json:"status,omitempty"`

	// VersioningAllowed Indicates if the Key Pool supports versioning.
	VersioningAllowed *KeyPoolVersioningAllowed `json:"versioning_allowed,omitempty"`
}

// KeySort defines model for KeySort.
type KeySort string

// KeyUpdate defines model for KeyUpdate.
type KeyUpdate struct {
	// Id Unique UUID for a Key.
	Id KeyId `json:"id"`

	// Pool Unique UUID for a Key Pool.
	Pool KeyPoolId `json:"pool"`
}

// KeysQueryParams defines model for KeysQueryParams.
type KeysQueryParams struct {
	Id *[]KeyId `json:"id,omitempty"`

	// MaxGenerateDate ISO 8601 UTC timestamp of Key generation.
	MaxGenerateDate *KeyGenerateDate `json:"max_generate_date,omitempty"`

	// MinGenerateDate ISO 8601 UTC timestamp of Key generation.
	MinGenerateDate *KeyGenerateDate `json:"min_generate_date,omitempty"`

	// Page Page number starting at 0.
	Page *PageNumber  `json:"page,omitempty"`
	Pool *[]KeyPoolId `json:"pool,omitempty"`

	// Size Page number.
	Size *PageSize  `json:"size,omitempty"`
	Sort *[]KeySort `json:"sort,omitempty"`
}

// PageNumber Page number starting at 0.
type PageNumber = int

// PageSize Page number.
type PageSize = int

// SignRequest Clear text to be signed. Can be JSON-encoded to create a JWT, or freeform to create a JWS. If you need freeform, encode as text (e.g. Base64-URL, Base64-MIME, Base64, Hexadecimal, etc).
type SignRequest = string

// SignResponse Base64Url-encoded JSON Web Signature (JWS) of the clear text in compact serialized format. See RFC 7515 JSON Web Signature (JWS) for more details. Compact serialized format is 'Header.Payload.Signature'. There are three Base64Url-encoded parts and separated by '.'. - Header: Required base64Url-encoded JSON key/values for the JWS. - Plaintext: Required base64Url-encoded clear text. It is always non-empty. Can be freeform (JWS) or JSON-encoded (JWT). - Signature: Required base64Url-encoded signature.
type SignResponse = string

// SymmetricCipherAdditionalAuthenticatedData Base64URL-encoded Additional Authenticated Data (AAD). This is non-secret data used for authentication and integrity checking during decryption (e.g. namespace, context).
type SymmetricCipherAdditionalAuthenticatedData = string

// SymmetricCipherInitializationVector Base64URL-encoded Nonce (e.g. 12-bytes AES-GCM or AES-GCM-SIV) or Initialization Vector (e.g. 16-bytes AES-CBC). This is non-secret data used for encryption/decryption, as well as authentication and integrity checking during decryption (e.g. namespace, context).
type SymmetricCipherInitializationVector = string

// SymmetricEncryptParams defines model for SymmetricEncryptParams.
type SymmetricEncryptParams struct {
	// Aad Base64URL-encoded Additional Authenticated Data (AAD). This is non-secret data used for authentication and integrity checking during decryption (e.g. namespace, context).
	Aad *SymmetricCipherAdditionalAuthenticatedData `json:"aad,omitempty"`

	// Iv Base64URL-encoded Nonce (e.g. 12-bytes AES-GCM or AES-GCM-SIV) or Initialization Vector (e.g. 16-bytes AES-CBC). This is non-secret data used for encryption/decryption, as well as authentication and integrity checking during decryption (e.g. namespace, context).
	Iv *SymmetricCipherInitializationVector `json:"iv,omitempty"`
}

// VerifyRequest Base64Url-encoded JSON Web Signature (JWS) of the clear text in compact serialized format. See RFC 7515 JSON Web Signature (JWS) for more details. Compact serialized format is 'Header.Payload.Signature'. There are three Base64Url-encoded parts and separated by '.'. - Header: Required base64Url-encoded JSON key/values for the JWS. - Plaintext: Required base64Url-encoded clear text. It is always non-empty. Can be freeform (JWS) or JSON-encoded (JWT). - Signature: Required base64Url-encoded signature.
type VerifyRequest = string

// KeyPoolQueryParamAlgorithms defines model for KeyPoolQueryParamAlgorithms.
type KeyPoolQueryParamAlgorithms = []KeyPoolAlgorithm

// KeyPoolQueryParamExportAllowed Indicates if the Key Pool supports export.
type KeyPoolQueryParamExportAllowed = KeyPoolExportAllowed

// KeyPoolQueryParamIds defines model for KeyPoolQueryParamIds.
type KeyPoolQueryParamIds = []KeyPoolId

// KeyPoolQueryParamImportAllowed Indicates if the Key Pool supports import (BYOK).
type KeyPoolQueryParamImportAllowed = KeyPoolImportAllowed

// KeyPoolQueryParamNames defines model for KeyPoolQueryParamNames.
type KeyPoolQueryParamNames = []KeyPoolName

// KeyPoolQueryParamPageNumber Page number starting at 0.
type KeyPoolQueryParamPageNumber = PageNumber

// KeyPoolQueryParamPageSize Page number.
type KeyPoolQueryParamPageSize = PageSize

// KeyPoolQueryParamProviders defines model for KeyPoolQueryParamProviders.
type KeyPoolQueryParamProviders = []KeyPoolProvider

// KeyPoolQueryParamSorts defines model for KeyPoolQueryParamSorts.
type KeyPoolQueryParamSorts = []KeyPoolSort

// KeyPoolQueryParamStatuses defines model for KeyPoolQueryParamStatuses.
type KeyPoolQueryParamStatuses = []KeyPoolStatus

// KeyPoolQueryParamVersioningAllowed Indicates if the Key Pool supports versioning.
type KeyPoolQueryParamVersioningAllowed = KeyPoolVersioningAllowed

// KeyQueryParamIds defines model for KeyQueryParamIds.
type KeyQueryParamIds = []KeyId

// KeyQueryParamKeyPoolIds defines model for KeyQueryParamKeyPoolIds.
type KeyQueryParamKeyPoolIds = []KeyPoolId

// KeyQueryParamMaximumGenerateDate ISO 8601 UTC timestamp of Key generation.
type KeyQueryParamMaximumGenerateDate = KeyGenerateDate

// KeyQueryParamMinimumGenerateDate ISO 8601 UTC timestamp of Key generation.
type KeyQueryParamMinimumGenerateDate = KeyGenerateDate

// KeyQueryParamPageNumber Page number starting at 0.
type KeyQueryParamPageNumber = PageNumber

// KeyQueryParamPageSize Page number.
type KeyQueryParamPageSize = PageSize

// KeyQueryParamSorts defines model for KeyQueryParamSorts.
type KeyQueryParamSorts = []KeySort

// HTTP400BadRequest defines model for HTTP400BadRequest.
type HTTP400BadRequest struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP401Unauthorized defines model for HTTP401Unauthorized.
type HTTP401Unauthorized struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP403Forbidden defines model for HTTP403Forbidden.
type HTTP403Forbidden struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP404NotFound defines model for HTTP404NotFound.
type HTTP404NotFound struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP429TooManyRequests defines model for HTTP429TooManyRequests.
type HTTP429TooManyRequests struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP500InternalServerError defines model for HTTP500InternalServerError.
type HTTP500InternalServerError struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP502BadGateway defines model for HTTP502BadGateway.
type HTTP502BadGateway struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP503ServiceUnavailable defines model for HTTP503ServiceUnavailable.
type HTTP503ServiceUnavailable struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// HTTP504GatewayTimeout defines model for HTTP504GatewayTimeout.
type HTTP504GatewayTimeout struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbXPbOJL+KyjeVtnelRVZtnwTbd0HR3YyiseOL7Lj2p3JZSCyJWGHBDgAaFsz5f9+",
	"1QD4AklUKNnZ5K7yxRZBoNHdD9AvROPPIBRJKjhwrYL+n0FKJU1AgzRP5zC/EiL+7wzk/ArfnMRTIZme",
	"JeZ1BCqULNVM8KAfvGaxBknGcxLKearFVNJ0xkJC8zHtoBXAQxqLCIK+lhm0AoYDf0fyQSvgNIGgHxT9",
	"g1agwhkkFOdiGuykf5EwCfrBf7woGX9hu6kXjt+Cy+CxFeh5aqhKSef4rPQ8xoaJkOb9koxnD6mQ+iSO",
	"xT1E68S8n4GegSRgBhCmCLWDUNBVktmOn1wvT7wGUvl8Pa5ifRitxUXPgJzDnOAgMjwluzc3w9O9hrCw",
	"aGs8htFWQAyTDYFgSUMgbMdtgfD5WgnEJU2gORTIVUMUzL9tcUCutkLiik7hMkvGIM2UK/hK6RQa67FC",
	"7rFuuhH7A+omU/huk8kMsdVTSXHHImfu6sAqgEpd74Zg5d23BiznbivQRkLqFWKNUgjZZE6UkJrxKaGK",
	"/DphEEe4OvoRkxBiz1/JLrSn7Rb5FYXpUxX+utcm7yEFqknhJchESJJksWZpDIYkMbRUQw3hiK21gwJu",
	"pxlNdaY22KDKDGgqk+m8vVR2+DZyfQCpmOCMTzcwmnfFoAaGs+y8rfFc5tHty4292PD0y3quxl6r5Lzw",
	"d5u54SxjUVM3nAoRf3lHXIp0QR9YkiVvgIOkGk6phiayJXYYmbpxJMI/u4yHcabYHezVrbCEPnzKB33C",
	"QZssMI/LpXV1wfhWothhW4jC+JcS5Ys75H+TM35+b8Wib85XNfNTj61AgkoFd47px+vrq6NO5xWN3sPv",
	"GSiNjaHgGrj5SdM0ZiFF6V/8S6Gy/qzwRuP43STo/7yeOZzjTEqBAcafGK6kIDWz84Npxx8PNEkNo69o",
	"RHJmCnGUloxPUZ4ElMJV5425ngGRdgwJRRZHhAtNxkAyjmGXFiIiQpJ7qkjClEKMsTuTEJXQGYiW5nOO",
	"tjrdUafTCpztyZ/s9nVPjgjjGqZutbsmMf4XhDp4/PiIjf4qrAr+2HLQHNxwmumZkOwP62m/LjgeN03R",
	"Ocn0DLh2rJIJZTEYPDIFkkQClIFrRu+ApCANQoIrs5XQPkagDFLU7MLmKB14KB14KB1si5KngQKmw9dC",
	"jlkUAf/6GJWsbAmQysIQIIKIjDNtEKBlB4hWwUbDEJQiWpjuEpTIZAjNoTr0oDr0oDrcFqpSEQVOR5dC",
	"vxYZ/wa20qXQxLKyhZWDqFCyb/AmSLG53o88vR95ej/aVu+lZLneuy+vhbigfO7sm/r66r8WgiBHpGCp",
	"KQz/EJld9Aq4JloIkiAdh4wijBNKpuwOOKGJyLgmYkI0S5pvh+7LKizmqYAFn7aDZVliB0+v0xlyDZLT",
	"eATyDuRZrq6vC1HOFLFcETu0sVHjJOPwkEKIu8WQJyIMM4muRHBjqJQh3BSXnuf3e57f723v91eLWWDT",
	"fUWjN1TDPZ1/G8FZzswmZssqmkgIgd2hK+eE8TsaM2PHTDxKJlIkBpUsVVoCTTaGp+vB0/Xg6T4lLMtF",
	"LkA5RKxYCDec3lEW03EMXx8cxxOpMrUFSEwRs0u4juck40gGHfuM8gh/VULtKDNvNCSpkFTOibgDGQtq",
	"gruEoqI55c3jgJ4XB/S8OKC3fRywSi8FkkcO22uWgMi+gfzH8UNyhrZAMGI2HnDbjVDjfuL5c+61Iw+p",
	"Iw+prSOHRdmxh1MjTn8K5tCvkqoublUFx0c3Mt4HHgoMYN+O3l2SWxiTM26GYni7+/b2bM/45BkQsO0Y",
	"6841KLJLOeqO7ysIJWgSsnQGspIk7qF/R5RpqFFpjMaYCmCyklDdJiMA8v71gPxn7+B4zfTmM4GQmNxo",
	"ymLVJoM6mrghd34EGoFsn+XsnsO8PfzQHhj2NDzoth/EX9PpTptcz0ACoRLIBNfBsn5SKrUiKLMClNEq",
	"guy0d9pkJBJwHULKMbiEJNVzEkEKPMIc2nnRHRpPdwyRHeDhDpkZXlU1syb7xErQN9GHSefGq9H6DeYv",
	"7micQZkAvr09QwpV4fvknVEnjVfRuT1DfCmvwKvmSQJashAnwBQmQtPl3ptZUjpH24VaYwqVjsvAioyM",
	"AL+DWKTFkjFYQnvaJjSe/hft9o6nYfLb/V4LjV85zH49Wj0oYnIPBRt+WKuWIWfaLAmbnn2AUAtJdocf",
	"9qwclrucfpu8FpKcnI323wwuSPlzfzT8QJgmaN0o44pQctDdt6ueC7TSxcDBq8Fiz2PXc/gBGS6X3VrG",
	"K9q3u8nQaJOhOz69p/OKlhszrmgChJsviQizZYwqC2Js3M6DRjaXtsRabqmfBWs6fap6c6UtU/Z0vf/j",
	"xcmiwi/dUPNqRtWs/Qvm8ynVGCwG/eB/fj7Z/yfd/6Oz//LT/se//fJL22v462JDgx5/WWX8C5trPcey",
	"0S12JUG146Yao1VzjW0ynJC5yEgqodC0Fc1EDg+YtU7QEKpsnDBtvr/qGSQLam8RCQkYyLVA8iIysYch",
	"9XcCykYmZmmYaZCOcR1gpg9nQoE3lfnI5Dbjj/BAIwhZQuOWs5L5//2b9z8Vvy+GF2ctAjrcW+konSpq",
	"/dMgBiqraio2SKEmDr5hMvK1rEjgFMOk0ma9I6EvI0Ad2N897HcP+93Dfvew3z3s83nYMj/s16aHvhXG",
	"Ea5chOS5oEnAfgI+1bOgf7A+afSpnRr7WHwja0ywTAvruUPcg2qm+PJlg8Oy/Gwu6P9cFrqA+/qX8/dx",
	"KaM0h73LSvRPxzc9FG8FLGpcx2HqJppXSTyuFiFnwHxiiCJmrfBVRagJjRWsH7y68GA4ekd+OO4ckJvr",
	"gfkooDRNUtzj5zDPiw/cIVv5aaHb6fb2O4f7B0fXB91+p9PvdP4ZtALrPIN+gIrdR2qrlrdVzhInN5z9",
	"ngG5uRmemv1PkYN2lWqWsaiG4JXTsw90WdO7RQWvx12j4aeVEY+txbrbrcptGy62sspmocZ0q9LSvPZg",
	"o+rOoupw8xrD0m5sVKi2oirsKcVgq/aOvyiWw/fVFee7qhIlnMPcnABVy69MlOjCdmadqPvEWA1aCnot",
	"E+jZ44lQ8CgfI/JwDMOrVQNNElH30sS4EZM7Lb80DH8w5YKo2MVtghMbILZXRFdMYadJFhuBVULjuOj9",
	"OQbO/3q70yKUSMojkZCBU0MleEd+dgdn53tunqhkreCq1NCiGKuizsHZedu8v5c0XeA+pnIKjqoLGycs",
	"xhnGsRgrlyqhWIyTSGRj3cIwgmGINDEJaKaA7Jx0e8dvBhcv8P/57Y41aIVa/u6G2FqGCc1ibewrRx/4",
	"c+APDlrBycHL7kJD94fVPQ5edv0eyw3dH2xDZZY3g4ulicq2cq6lfvb/0ozLbea/N2/EZIVS/mT7u6du",
	"79jEaqPeQdeX1TYf/nDk68Q2d3vHtb2r6qj0rmuu6MrnpKoJn5mq7D4/NWMW9OVzVffG12fJW6nVcoZS",
	"tyUFbPtYdelLi67OzQ4kuEji/6Gz/T/oPZ/ZDVZDbXftowrOx3pHeepjuJhTFE9ldGedoRdZmg8BhRGv",
	"MeBXdC5FHJNTqikmlTahyFOTbq/32VRl5QJYDo55ZCqcFGGThdL8LMWRyt3C8mTwY/GxEDFQXpm0cfBb",
	"qKdpBPyZq0sNxHF3mXZf/ePd+d5GUmGcU9bVqmX7YAPZp5XBL5dpb569LddHb04jdXlz0+rmlq1Xblym",
	"3LJlv0+u9l0T1l46I7VQIScZ8Ciem8thazfq+j14fNh0C15VLJ/PS/4m/25crNaEcjqFBONEZU/yq9FT",
	"Xj3ju7eitZ6TkVN5TohF/ZPRIMAUrH96Zn6ZS0kn5U/XnFtv96p4dK8Lz+jel8+uw7IJdz1XvHBDfE+V",
	"M+o3uq6+a3RdFxpdV5uJuS7uwbz6uEZtNV99bPsieFWkQowkkFjBua0ERhXaz92fbHulId+5Qav8jFOM",
	"oqFmd8ZjMUXHPqUIYtDw6Z6qT3WTVbrUzl/pU8y24t16BpY5V5pKDZHrhCafcaZmZYu3mCuKq0PlJo1W",
	"RmlPDrQ2Dm6eFFM0uFvWwKuV28izYfbSRa1HW+/OvHD32a6JP+c3o6df0XrecPg57gxv7nirkfWzXYL9",
	"ws58/TXT3Nw+z/XOf8NXtEXH6i4T4r/cY+LP3LNF1uUu+t7FO23es+vtt63zXHX28Yt+26/aQacEFtWZ",
	"v+/R9JpN7VT/DLdQv5m43L9cuRAK02lx/GpCBXMpUZOO58+q5ecrztHsFPmlytoJPJLdnlfVWZmgu2qC",
	"EZvy5sUuik05RG0ysKUOb0fvLouTYS2IiXKAUPL29tqc8E8kAKbCCy9Hfq1M3quokfELY2prYPIiGa9y",
	"prYwxkq6RVUMDqQ6k0B2396OiqKYsFRO42KXXj3VLWtdrlw9RkHOK2jRMwmbVrQ8sQhlhBSu8gKDtURK",
	"DdZXO7iVViwkB4H0197u29trUyRSqGHtxCrvtWG9wN+aVQOM8ioaWwFyUpz/nlTv4GEaXrsO3/9UMFsO",
	"J954k8eT3ZOT0z2/GseVkUT4ujjUWqiuQOiNFZBMz0k4g/A3NFBRJs0/WKjDwYBQpTSElj32etBmj9Uq",
	"rola/IIdW6/TRB+Xgofg+Cpqc1aXmpiFUlMYZMcfV8YPXg2aaLI8GHtR6qmFNuse4hj/f0u6dsdytTkR",
	"/Wz0tMFqxgTkbkN6K5fBSnf7ASSbzLe5OfDdgn+34BtYcFx9jE9EXfkAeX82uiYnV0Mzt2baHsddDcvv",
	"f0E/6LQ77QNctyIFTlMW9IPDdqd9aNmdqaDPszh+/N8AAAD//4F61jhZTwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
